- src/components/navigation/conference/2019/navigation.jsx
- src/routes.json
- src/views/conference/2019/index/index.jsx
Four small fixes to 2019 conference page:
1. mailing list link links to correct form
2. "visit website" buttons open in new tab/window
3. /conference should redirect to conference/2019, not just show same content
4. main Scratch logo should link back to regular site
> corrected mail list form; links use _blank; redirect conference url; logo links to main site

- webpack.config.js
Support for dynamically loading translated images.
Fixes https://github.com/LLK/scratch-gui/issues/3632 
Copy over dynamic chunks for gui so that webpack can load the files.
> Copy the gui localized image chunks to static

- src/redux/preview.js
- src/views/preview/project-view.jsx
Together with https://github.com/LLK/scratch-api/pull/770, resolves https://github.com/LLK/scratch-api/issues/756
Must be merged at the same time as resolves https://github.com/LLK/scratch-api/pull/770 , as both change the URL for the same endpoint
Changes handling of the "studios for project" endpoint:
* URI now includes owner of project
* now passes auth token
* waits until after retrieving project info to request studios list, because we need to know ownership of project
* determines whether to hit admin endpoint or regular endpoint by checking if current user is admin
None
> change "studios for project" API request to include owner & token, determine endpoint using admin status

- src/redux/preview.js
- src/views/preview/project-view.jsx
Must be merged at the same time as https://github.com/LLK/scratch-api/pull/774, which changes the same endpoint on the backend.
Resolves https://github.com/LLK/scratch-api/issues/755
* adds `ownerUsername` to all 3 comment API endpoint URIs
* handles error responses to those requests in a less catastrophic way; before, we would crash the page with an "Oops" message; now, we just fail silently (this came up in development)
None
> add ownerUsername to comment API endpoint URIs

- .tx/config
- Makefile
- bin/build-locales
- package.json
- test/localization/check_valid_json.js
fixes #2665 
As a follow-up, we should add scripts to allow automated update of source files on a regular schedule (like gui, etc)
Removes `scratchr2_translations` dependency from the package.json, and updates build scripts to use data from `scratch-l10n` instead.
No functional changes, updated translations json test to use scratch-l10n.
> Remove dependency on scratchr2_translations

- src/redux/preview.js
Finishes resolving https://github.com/LLK/scratch-api/issues/755 by passing the `ownerUsername` parameter in places that https://github.com/LLK/scratch-www/pull/2859 left it out.
> pass ownerUsername in three places it was left out

- package.json
fixes #2873 
Update react-intl to latest version (2.8.0) which includes the māori locale data. 
- Manually tested that switching to māori no longer shows message ids, and no errors in the console.
> Update react-intl to bring in māori locale-data

- bin/build-locales
This change was made by @chrisgarrity in https://github.com/LLK/scratch-www/pull/2952/commits/3a651fa9fd1778fb80ce8f1d6b4a712bc3801610 , but we decided to move it to its own PR.
Hopefully, resolves https://github.com/LLK/scratch-www/issues/2959
When dowloading translations from transifex, don't overwrite local english defaults (contained in various `l10n.json` files).
This effectively fixes translations for new strings in the www build, so the english versions will be displayed by default, rather than the new string's IDs.
Don't know how we can add a test for `build-locales`. I added an issue to track this: https://github.com/LLK/scratch-www/issues/2968
> fix "make translations" command

- src/routes.json
Resolves https://github.com/LLK/scratch-www/issues/2837
changes `scratch.mit.edu/story` redirect from `tutorial=story` to `tutorial=tell-a-story`.
> change /story redirect from tutorial=story to tutorial=tell-a-story

- test/integration/smoke-testing/test-my-stuff.js
Integration tests fail periodically because they create projects whenever they are run but don't share them.  Eventually, the first page of "My Stuff" will not have any shared projects so the "Add To" test (add to studio) fails.  Previously I would have to manually delete projects to allow the tests to pass.
Before looking for the button, the test now clicks the "shared projects" button, guaranteeing a shared project will be visible.
> Make Add to studio test in test-my-stuff integration test look in shared projects

- src/views/preview/preview.scss
Resolves https://github.com/LLK/scratch-www/issues/2603
* fixes alignment of remix credit avatar by overriding its vertical alignment, to align to the top. 
* fixes alignment of remix credit text by aligning it to the left.
> fix alignment of remix credit avatar, text

- src/views/preview/presentation.jsx
- src/views/preview/preview.scss
Fixes one remaining formatting issue from https://github.com/LLK/scratch-www/pull/2973 / https://github.com/LLK/scratch-www/issues/2603
Instead of hardcoding notes & credits section to be formatted as the "last" description setting, let that style apply to whichever of instructions and notes&credits is last.
Before:
After:
> fix last instructions notes and credits alignment

- src/views/teachers/landing/landing.jsx
Resolves https://github.com/LLK/scratch-www/issues/2996
added missing slash to start of images link, to fix intermittent CDN issue
None. Unclear how to test this, since various methods of providing a string value to `<img src=...>` are possible.
> added missing slash to images link, to fix intermittent CDN issue

- src/views/download/download.jsx
Points `download.jsx` to new scratch-desktop file on S3
> [Master] Hotfix: update scratch-desktop link

- src/views/preview/preview.scss
Resolves https://github.com/LLK/scratch-www/issues/3011
Adds back the `min-height: 0;` line to the `description-block` class, per this explanation: https://stackoverflow.com/a/36247448
Tested in Mac Chrome, Firefox and Safari
> fix firefox instructions height overflow issue

- src/views/preview/preview.scss
Resolves https://github.com/LLK/scratch-www/issues/3013
Uses the relatively new `min-height: max-content` css setting for `remix-credit`, to make parent expand height to encapsulate children. Don't really understand why this is necessary! 
Before:
After:
Tested in Mac Chrome, Firefox, and Safari
> set min-height of remix credit to max-content

- package.json
- src/views/preview/preview.scss
Release notes:
- May Translations update LLK/scratch-blocks/pull/1946
- zu
- fa (lots)
- pt-br
- nb
- rap
- Sort list variables in context menu LLK/scratch-blocks/pull/1929
- Playground improvements LLK/scratch-render/pull/426
- ~Tweak scalingVector to make dots appear to be more circular LLK/scratch-render/pull/423~ LLK/scratch-render/pull/466
- Implement canvas-based TextBubbleSkin LLK/scratch-render/pull/451
- Update the built-in SVG assets for the default project LLK/scratch-gui/pull/4846
- ~Pause video on tutorial window shrink LLK/scratch-gui/pull/4835~ LLK/scratch-gui/pull/4877
- add timeouts & messages to all driver.wait calls LLK/scratch-gui/pull/4841
- ~Delay loading and rendering gui LLK/scratch-gui/pull/4800~ LLK/scratch-gui/pull/4874, LLK/scratch-gui/pull/4873
- Stabilize …
> [Master] Release/2019-05-29

- package.json
Release notes:
- May Translations update LLK/scratch-blocks/pull/1946
- zu
- fa (lots)
- pt-br
- nb
- rap
- Sort list variables in context menu LLK/scratch-blocks/pull/1929
- Playground improvements LLK/scratch-render/pull/426
- ~Tweak scalingVector to make dots appear to be more circular LLK/scratch-render/pull/423~ LLK/scratch-render/pull/466
- Implement canvas-based TextBubbleSkin LLK/scratch-render/pull/451
- Update the built-in SVG assets for the default project LLK/scratch-gui/pull/4846
- ~Pause video on tutorial window shrink LLK/scratch-gui/pull/4835~ LLK/scratch-gui/pull/4877
- add timeouts & messages to all driver.wait calls LLK/scratch-gui/pull/4841
- ~Delay loading and rendering gui LLK/scratch-gui/pull/4800~ LLK/scratch-gui/pull/4874, LLK/scratch-gui/pull/4873
- Stabilize …
> [Develop] Release/2019-05-29 

- src/redux/preview.js
- src/views/preview/project-view.jsx
Together with API PR https://github.com/LLK/scratch-api/pull/810, resolves https://github.com/LLK/scratch-api/issues/756
Must be merged at the same time as that API PR , as both change the URL for the same endpoint
Changes handling of the "studios for project" endpoint:
* URI now includes owner of project
* now passes auth token
* waits until after retrieving project info to request studios list, because we need to know ownership of project
* determines whether to hit admin endpoint or regular endpoint by checking if current user is admin
None
> change studios for project API request to use admin status, owner status and token

- test/integration-cypress/cypress/smoke-tests/test-footer-links.js
Preventative change to the Cypress tests, which are currently unused
In Cypress test file, skip all smoke tests that access external sites
> in (unused) Cypress test file, removed all footer link tests for external sites

- package.json
Reverts LLK/scratch-www#3055
-- npm failed to publish the gui version actually mentioned in this PR.
> Revert "Pull in latest scratch-gui"

- package.json
Essentially undo https://github.com/LLK/scratch-www/commit/edffa47f6586027a7a1363c2ba14d41706325042 since it wasn't the cause of any problems.
> Put GUI version back to what it was originally for this release.

- .tx/config
The Boost and Vernier pages were never added to the transifex config, and never pushed to transifex for translation. This adds them to the config. I also ran `tx push -s` to push the latest version of everything to transifex.
> Add Boost and Vernier landing pages to the transifex configuration

- src/redux/preview.js
- src/views/preview/project-view.jsx
Together with api counterpart https://github.com/LLK/scratch-api/pull/851, resolves https://github.com/LLK/scratch-api/issues/755 . 
A redo of pieces of reverted PRs https://github.com/LLK/scratch-www/pull/2871, https://github.com/LLK/scratch-www/pull/2859, and https://github.com/LLK/scratch-www/pull/2858.
passes owner username and token (if any is present) to comment endpoints, so API can verify that this user should have access to the comments.
> pass owner username and token to comment endpoints

- src/views/download/download.jsx
Scratch Desktop 3.4.0 release
This PR updates the version number in the Scratch Desktop direct-download links. Note that the linked files are already in place.
CC @BryceLTaylor
> update download links for Scratch Desktop 3.4.0

- src/views/preview/project-view.jsx
Resolves bugs identified in 6/27/19 bug hunt, where See All Comments did not work
Passes missing author username to proper comments API endpoints
> fix see all comments and load more replies, by passing author username

- src/views/boost/boost.jsx
- src/views/boost/l10n.json
Add a troubleshooting item to the LEGO BOOST extension landing page to address the recent firmware update.
> [master] Add troubleshooting item for boost firmware update

- src/components/join-flow/join-flow-step.jsx
in join-flow-step.jsx, use html form instead of formik form.
> use html form instead of formik form

- package.json
This is the hotfix associated with https://github.com/LLK/scratch-gui/pull/4962, that should prevent it appearing that your project has saved even when we are getting errors from the server.
> [Master] Hotfix for asset saving errors

- src/components/modal/addtostudio/presentation.jsx
- src/components/modal/base/modal-inner-content.jsx
- src/components/modal/base/modal-inner-content.scss
- src/components/modal/base/modal.scss
- src/components/modal/report/modal.jsx
- src/components/modal/social/presentation.jsx
Resolves https://github.com/LLK/scratch-www/issues/3112
* renames the `.modal-content` style when it is used inside another `.modal-content` style; now we'll call that inside one `.modal-inner-content`.
* refactors uses of that inner modal-content style, so they use a component instead of using the style out of scope.
> add ModalInnerContent component, use it in modals

- package-lock.json
Follow-on to https://github.com/LLK/scratch-www/pull/3094
Question about PRs like https://github.com/LLK/scratch-www/pull/3094, and this:
Now that we have package-lock.json tracked/checked in, if we make an update to a package.json line via greenkeeper, should we also make an update to package-lock.json?
If so, does that mean that the process of merging in greenkeeper PRs is more complicated now -- check out locally, npm install, maybe test the change, add package-lock.json changes, push to origin, merge? For ones that we don't typically test locally, will we still need to do all this, minus the local testing?
> update package-lock.json with newer google-libphonenumber

- src/components/join-flow/join-flow-step.jsx
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/next-step-button.jsx
- src/components/join-flow/next-step-button.scss
- src/components/modal/join/modal.scss
* use new ModalTitle, ModalInnerContent components in join flow
* set width, margins to make join flow modal look closer to spec
* use ModalTitle in the "Next" button at bottom
Now looks like:
> Format join flow using ModalTitle, ModalInnerContent, NextStepButton components

- src/components/join-flow/join-flow-step.scss
- src/components/modal/base/modal-inner-content.jsx
- src/components/modal/base/modal-inner-content.scss
Resolves https://github.com/LLK/scratch-www/issues/3139
In modal styling:
* use padding to avoid margin collapse
* drop previous approach, which used `overflow: auto`
> use padding to avoid margin collapse; drop approach that used `overflow: auto`

- src/components/formik-forms/formik-input.jsx
- src/components/forms/row.scss
- src/components/join-flow/join-flow-steps.jsx
Retry of https://github.com/LLK/scratch-www/pull/3116, after it was reverted in https://github.com/LLK/scratch-www/pull/3125
Resolves https://github.com/LLK/scratch-www/issues/3115
* Adds `validationClassName` parameter to `FormikInput` component
* Set formatting of validations in join flow using `validationClassName`
Note that unlike in https://github.com/LLK/scratch-www/pull/3116, I'm _not_ changing the css I use to prevent margins from collapsing. After this PR, I will consider ways to prevent margin collapse without interfering with other modals' formatting.
> Format validation; redo of PR 3116

- src/components/modal/addtostudio/modal.scss
- src/components/modal/addtostudio/presentation.jsx
Resolves https://github.com/LLK/scratch-www/issues/2472 AddToStudio modal can be weirdly tall
Resolves https://github.com/LLK/scratch-www/issues/2685 When add to studio modal has many studios, the ones on bottom have fade out overlay
* use fixed height, rather than 100%, for preferred height of add to studio modal; this is the main fix
* increase the max-height of add to studio modal, so that when the window is short, it is taller than it was before
* override height and max-height when window becomes too short, so it becomes flush with top and bottom of window
* add div with class `studio-list-footer-spacer` to the list of studios, so that when you scroll the list to the bottom, the bottommost studios are clear of the gradient overlay (this might be a nice fix to bring in to the sprite, …
> fix add-to-studio modal height, gradient interference

- package-lock.json
- package.json
Update GUI to the version that includes https://github.com/LLK/scratch-gui/pull/4960
> Greenkeeper/scratch gui 0.1.0 prerelease.20190723203336

- src/components/formik-forms/formik-select.jsx
- src/components/forms/validation-message.scss
- src/components/join-flow/birthdate-step.jsx
- src/components/join-flow/join-flow-steps.scss
* use `row-with-tooltip` class in formik-select component, so validations will be correctly positioned
* tweak css transform in validations so they are positioned in a way that will correspond to the select elements they refer to, without blocking user from clicking on the selects
* tweak css classes when window is narrow, so validations are no longer transformed to the right
when window is wide:
when window is narrow:
> better validation positioning on birthdate step

- src/views/download/download.jsx
Scratch Desktop 3.5.0 release
This PR updates the version number in the Scratch Desktop direct-download links. Note that the linked files are already in place.
CC @BryceLTaylor
> [Develop] update download link for Scratch Desktop -> 3.5.0

- src/views/download/download.jsx
Scratch Desktop 3.5.0 release
This PR updates the version number in the Scratch Desktop direct-download links. Note that the linked files are already in place.
CC @BryceLTaylor
> [Master] update download link for Scratch Desktop -> 3.5.0

- src/views/preview/project-view.jsx
Fixes #2550,  the issue where project reports did not correctly include the thumbnail
From that comment:
> from looking at the default thumbnail data we include in the reportProject reducer action https://github.com/LLK/scratch-www/blob/develop/src/redux/preview.js#L964-L967 it seems like maybe the problem is that we are including the data:image prefix in the POST instead of just the b64 encoded image. That is, we might be able to fix just by stripping data:image/png;base64, from the thumbnail we get back from the GUI.
> [Master] Fix project thumbnails for reporting

- bin/configure-fastly.js
Reverts LLK/scratch-www#3217
This may not have been the root cause of the deploy issues, it looks like travis was having network connectivity issues on their end.
It is hotfix branch just to test deploying, I think we can just merge it into develop if all looks good.
> Revert "Merge pull request #3217 from LLK/hotfix/fastly-concurrency"

- src/components/formik-forms/formik-select.jsx
- src/components/join-flow/country-step.jsx
- src/components/join-flow/join-flow-steps.scss
- src/components/join-flow/join-flow.jsx
* adds `country-step.jsx` 
* adds several additional functions to `lib/country-data.js` so that we have the ability to put various country options at the top of the list, and the ability to rename some country labels
This is just a first draft, and has placeholder text and a placeholder image.
Added tests of all the country data functions using jest
> Add join flow country step

- src/views/preview/comment/comment.scss
Fixes an issue where you cannot click on the user link on a comment when it is highlighted, for example when following a link from your messages.
The absolutely positioned :before highlight was eating clicks from the relatively positioned elements after it, like the avatar image. Disable pointer events to prevent this background element from receiving clicks.
This is due to a subtle issue with element ordering, even elements that are before other elements get automatically promoted above siblings that are relatively positioned. That is why the reply/delete buttons still work on highlighted comments (they are also absolutely positioned) but the avatar user link did not work.
> Fix click not working on highlighted comment avatar

- src/views/preview/comment/comment.jsx
- src/views/preview/comment/top-level-comment.jsx
- src/views/preview/presentation.jsx
Requested mod feature, do not show the "Are you sure you want to delete and not report?" modal for project comments if the user is an admin.
> Allow admins to delete comments without confirmation

- src/components/formik-forms/formik-input.jsx
- src/components/formik-forms/formik-input.scss
- src/components/join-flow/username-step.jsx
- src/lib/validate.js
- test/unit/lib/validate.test.js
* Focusing on a field clears the error (until field is blurred again)
* If username and password are the same, password field reports error right away (instead of waiting for user to click "Next")
* Design of inputs with an error that are focused on are no longer a weird combination of blue and orange borders!
Focusing on a field clears the error (until field is blurred again):
If username and password are the same, password field reports error right away (instead of waiting for user to click "Next"):
> handle username validation errors states better

- src/components/join-flow/birthdate-step.jsx
- src/components/join-flow/country-step.jsx
- src/components/join-flow/email-step.jsx
- src/components/join-flow/gender-step.jsx
- src/components/join-flow/join-flow-step.jsx
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/join-flow-steps.scss
- src/components/join-flow/username-step.jsx
- src/components/join-flow/welcome-step.jsx
* add join-flow-outer-content class, to make step heights consistent
* allow custom padding above join flow titles, to adjust for whitespace balance
* join-flow-step accepts a descriptionClassName which formats description; gender uses this
* allow steps to expand vertically as content is introduced, or translations run long
> make join flow steps' vertical size consistent, make vertical spacing more flexible

- src/components/join-flow/username-step.jsx
- src/l10n.json
Note: styling depends on https://github.com/LLK/scratch-www/pull/3265 being merged first.
Adds placeholders to username, password and passwordConfirm fields.
Note that these won't be formatted correctly until https://github.com/LLK/scratch-www/pull/3265 is merged.
> added placeholders to username step

- src/components/info-button/info-button.jsx
- src/components/info-button/info-button.scss
- test/__mocks__/react-responsive.js
- test/unit/components/info-button.test.jsx
* uses media queries in both jsx and sass to handle info button differently in small screen sizes
For small screen sizes, we keep the info message absolutely positioned, but instead of the reference parent element with `position: relative` being the info icon itself, we make a new div, a sibling to the icon, with `position: relative`.
This creates a new row, which is where the info message positions itself.
Since the message is absolutely positioned, it overlaps content below (rather than causing the enclosing modal or other element to have to change form).
wide window/screen (>= 942px):
small window/screen (< 942px):
> use media queries to make info message responsive

- src/components/formik-forms/formik-select.jsx
- src/components/formik-forms/formik-select.scss
* creates `formik-select.scss` file which contains orange fail state
* simplifies a few lines of `formik-select.jsx` where className is handled
> formik-select handles fail state with orange border

- src/components/join-flow/country-step.jsx
- src/components/join-flow/join-flow-steps.scss
* Adjusts vertical padding for the birthdate and country steps, including spacing around description
* Adjusts width of birthdate message, so info button won't wrap in English
> improve top and bottom positioning for multiple steps

- src/components/join-flow/join-flow-steps.scss
* use `margin: auto` to make gender radio rows center themselves horizontally within the modal
Before:
After:
> make gender radio rows center themselves horizontally within the modal

- src/routes.json
- src/views/join/join.jsx
Add a standalone page for the new join flow. It just includes the modal.  
WEIRD THING: The Page component is required but not used. Without that, webpack runs out of memory during UglifyJsPlugin step.
> Join flow standalone page

- src/_colors.scss
- src/components/join-flow/next-step-button.scss
restyles next button to:
* remove border
* add hover color
My only questions are for @kathymakes:
1. what do you think of the hover color? 
2. do you think this merits adding a color to _colors.scss?
Note that in _colors.scss, there are actually two different hue/saturation values both called "orange" -- I'm not sure what the intention was with the 25 percent and 10 percent values.
No hover:
Yes hover:
> restyle next button to remove border, add hover color

- src/components/navigation/www/navigation.jsx
- src/components/registration/scratch3-registration.jsx
- src/redux/navigation.js
Reverts LLK/scratch-www#3296 (which itself was a revert)
* adds prop to new join flow called `createProjectOnComplete`
* when `createProjectOnComplete` is true, on completing join flow, user will be redirected to the `/projects/editor/?tutorial=getStarted` page
none
> on complete join flow, take user to new project

- src/components/join-flow/email-step.jsx
- src/lib/validate.js
- test/unit/lib/validate.test.js
* moves local email validation into our own `validate.js` library
* adds remote validation using scratchr2 endpoint
* makes validation error remain on focus, and disappear on change (to make behavior match how we handle username/password inputs)
Added tests for local email address validation
> Join flow validate email remotely

- src/components/info-button/info-button.jsx
- src/components/info-button/info-button.scss
Shifts info button downwards to be more in line with text; extends the shadow that we added to the validation message when it is in "suggestion" mode, to the info rollover window
> move info button down, and give its message a shadow

- src/components/info-button/info-button.scss
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/join-flow-steps.scss
CSS tweaks to make text appear more natural when it's longer than the strings we're defaulting to, e.g. for internationalization
Make info button not affect text line height
> Join flow handle text overflow more flexibly

- src/views/preview/meta.jsx
This will tell crawlers that this page and all its exact duplicates (/fullscreen, /editor, /embed, etc...) should be considered the same and use the project page as the canonical crawled page. We had an issue before where by not selected a canonical, google was considering all the project pages duplicates :(
Hopefully resolves a problem with public scratch projects not showing up on google.
Add a canonical link to the project page …
> Include canonical link in project meta tags

- src/views/preview/comment/comment.scss
Keeps nefarious text from escaping the comment container on project pages. This was fixed once before, but the fix wasn't carried over to the project page.
> [Master] Contain zalgo text

- src/components/join-flow/email-step.jsx
- src/components/join-flow/join-flow.jsx
- src/l10n.json
- test/unit/components/email-step.test.jsx
- test/unit/components/join-flow.test.jsx
Some TODOs to handle captcha reloading.
Introduces a new function to JoinFlow to handle errors that happen in the middle of registration rather than on an explicit next step taking by the user
Added tests for new join flow function as well as for email-step.
> Handle errors of captcha loading by setting error state on JoinFlow.

- src/components/modal/base/modal.jsx
* on most browsers (not firefox), make close icon ("x") in modal not draggable.
> set modal close icon to draggable false

- src/components/join-flow/join-flow-steps.scss
* give join-flow validations more spacing from inputs they refer to
* unset width of Required message
Before:
After:
<br>
<br>
Before:
After:
<br>
<br>
Before:
After:
> Join Flow validation positioning/spacing fixes

- src/components/modal/join/modal.jsx
Set the flag `shouldCloseOnOverlayClick` to `false` in join modal, so clicks outside it don't close it.
I don't think this is testable yet -- smoke tests can be added after launch
> new join flow modal stays open on click outside

- src/components/modal/base/modal.jsx
- src/components/modal/join/modal.jsx
- src/views/join/join.jsx
- test/unit/components/modal.test.jsx
Sets the default value of the showCloseButton prop to true and pass it through as false from the new standalone join flow page. 
Added very basic tests for modal that the close button is hidden/shown appropriately.
> One approach to hiding the close button in the modal.

- src/views/join/join.jsx
- src/views/join/join.scss
Logo links back to scratch homepage. 
This will need some positioning css work if we want to match it to teacher registration, especially on small screens. Right now it is set to be 25% of the way across the screen until it gets small when it is set to be centered.
> Add Logo to join flow standalone page.

- src/components/join-flow/join-flow.jsx
- src/components/join-flow/welcome-step.jsx
- src/components/modal/join/modal.jsx
- src/components/registration/scratch3-registration.jsx
- src/l10n.json
- src/views/join/join.jsx
* use Scratch3Registration instead of JoinModal in /join
* pass createProjectOnComplete prop through join flow 
* in editor mode, last step says "Done" and not "Create a project ->"
(Note that we changed the text/icon in the button in the last step since taking this...)
> Join flow navigate when finished

- src/components/join-flow/gender-step.jsx
* use "male" and "female" for gender values, not "Male" and "Female". This matches the existing values in the database. (Users will still see capitalized versions.)
* use "non-binary" as value instead of "Non-binary", to better match what users are likely to have typed themselves in the past. (Users will still see capitalized version.)
* use a blank string when user skips gender step, rather than "Prefer not to say"
> gender step uses blank default, lcase values

- src/components/formik-forms/formik-checkbox.scss
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/username-step.jsx
* makes "Show Password" text bold, and moves it down slightly to look balanced
* makes email step terms of use statement only semi-bold
> join flow bold text and related design tweaks

- src/components/forms/validation-message.scss
* Makes all validation popups/tooltips semi-bold (font-weight: 500)
(previously, some were regular, font-weight: 400)
> make validations semi-bold

- src/components/join-flow/username-step.jsx
On username step, default to showing password content (rather than masking it).
> change password default; remove unused state var

- src/components/navigation/www/navigation.jsx
- src/redux/navigation.js
- test/unit/components/navigation.test.jsx
instead of popping up new join flow in a modal, this makes most pages redirect to /join. Except for editor.
> scratch3 join flow redirects to /join, outside editor

- src/components/join-flow/next-step-button.jsx
- src/components/join-flow/next-step-button.scss
- src/components/spinner/spinner.scss
* remove unnecessary --webkit prefix lines
* slow down spinner, and set timing with bezier (cleared with @kathymakes and @carljbowman)
* format size of spinner for join flow
> format and update timing of join flow spinner

- src/components/formik-forms/formik-radio-button.jsx
- src/components/join-flow/email-step.jsx
- src/components/join-flow/join-flow-step.jsx
- src/components/join-flow/username-step.jsx
* adds several attributes to the input fields in the new join-flow. These attributes tell the browser to disable autocomplete and suggestions of past input.
before:
after:
> turn off automplete and autocorrect for join-flow inputs

- src/components/join-flow/join-flow-steps.scss
Improves the vertical centering of the email step, so the checkbox text stays some margin away from the blue ToS text.
Done alongside @kathymakes .
> adjust join flow email centering

- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/next-step-button.scss
- src/components/modal/join/modal.scss
- src/views/join/join.scss
Several fixes to responsive appearance:
* correctly handle join flow modal's switch from rounded corners to square corners at small window sizes
* make modal occupy full width of window, and mo more, at small window sizes, to avoid horizontal scrolling or off-center appearance
* enable vertical scrolling when modal showing, if page is short
* make small sized windows bump the join flow modal down to accommodate Scratch logo
* rewrite join view scss to be simpler, without changing appearance
> Join flow responsive fixes

- src/components/join-flow/email-step.jsx
- src/components/join-flow/gender-step.jsx
- src/components/join-flow/username-step.jsx
* when user changes content of the custom gender input, truncate the value to 25 chars -- the limit of the field we store in the database.
* do the same for username (30 chars), password and passwordConfirm (128 chars), and email (254 chars)
these values would be truncated on the backend anyway, but this will reduce the network throughput.
> truncate custom gender, and other inputs

- bin/configure-fastly.js
- bin/lib/fastly-extended.js
- test/unit/lib/fastly-extended.test.js
Resolves https://github.com/LLK/scratch-www/issues/1342
When comparing fastly vcls to find most recent one, prefer one vcl to another if and only if it is both higher-numbered and active. (Previously, we only considered number.)
Added a test.
> when looking for latest fastly VCL to clone, use only active VCLs

- src/_colors.scss
- src/components/join-flow/birthdate-step.jsx
- src/components/join-flow/country-step.jsx
- src/components/join-flow/email-step.jsx
- src/components/join-flow/join-flow-step.jsx
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/join-flow-steps.scss
- src/components/join-flow/welcome-step.jsx
Adds colored backgrounds behind join flow header images, to act as a sort of preview if they are taking a while to load.
> Join flow image preview using background color

- src/components/formik-forms/formik-radio-button.scss
- src/components/join-flow/join-flow-step.scss
- src/components/join-flow/join-flow-steps.scss
* change how we handle the width of gender custom input
* change calculation for join flow modal inner content width, to be more friedly at small sizes
* custom birth month and year width for small window sizes
these changes should not cause changes in the appearance of the join flow at regular size, only at small window widths.
These are all at a window size of 320px wide:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
> Join flow responsive changes for input, button and select widths

- src/components/errorboundary/errorboundary.jsx
- src/components/page/www/page.jsx
- src/lib/sentry.js
- src/views/join/join.jsx
- src/views/preview/embed-view.jsx
- src/views/preview/embed.jsx
- test/unit/components/errorboundary.test.jsx
* Resolves https://github.com/LLK/scratch-www/issues/3443
* Step towards resolving https://github.com/LLK/scratch-www/issues/3053
* adds Sentry support to Join Flow, by making the standalone join view initialize Sentry
* makes www's Sentry reporting code report to Sentry:
* that the error was caught inside scratch-www
* which ErrorBoundary caught the error
Added some unsurprisingly complex tests :)
> Add Sentry to Join Flow; set Sentry tags on various ErrorBoundaries

- src/components/join-flow/email-step.jsx
- src/components/join-flow/username-step.jsx
- test/unit/components/email-step.test.jsx
- test/unit/components/username-step.test.jsx
adds simple local caches to username and email steps to memoize remote requests, so they are not repeated with the same data.
Note that I cleared this approach with @rschamp .
Added tests of cacheing remote requests for both username and email step
> Join flow cache remote

- src/components/join-flow/country-step.jsx
- src/views/preview/project-view.jsx
To test changes introduced in https://github.com/LLK/scratch-www/pull/3444 , this PR brings in test code to a hotfix branch.
Once we've tested this on staging, this hotfix branch should be deleted.
> Hotfix TEST ONLY: artificially throw errors in 2 places to test Sentry changes

- src/components/join-flow/join-flow-steps.scss
Makes text in join-flow modal selectable, so users can copy error messages if necessary.
> make text selectable, so users can copy errors

- src/lib/country-data.js
- test/unit/lib/country-data.test.js
Resolves https://github.com/LLK/scratch-www/issues/3467
Sends country name strings, rather than country codes, when user registers (both for teacher registration and regular user registration)
Added test to verify that options values are full country name strings
Choosing Brazil in join flow...
Before change:
After change:
> fixed country options to use full country name string as option value

- src/routes.json
This pattern works for building/deploying, but not for running locally. Split it up to deal with what express expects a path to look like.
`npm start` should now work instead of crashing due to the `(makeit)?fly` route.
> Fix dev server by splitting up redirect regex

- bin/build-locales
When the name of the view in `routes.json` does not match the name of the resource in transifex there needs to be a mapping added to the script that generates translations. _Note: the resource name in transifex is usually based on the name of the source file in the `views` directory. Usually the name of the view in the routes file matches._
Since `routes.json` is a JSON file that does not support comments there’s no way to add a warning to the file when someone is adding a route.
The sympton was the message that there were no translations for ‘vernier’ or ‘embed’ when running translate. The `vernier` route is actually the `gdxfor` view, and `embed` is just another version of `preview`
Adds a mapping for the `embed` and `vernier` routes to the correct transifex resources `preview` and …
> Add translation resource mapping

- package-lock.json
- package.json
Update gui. This version includes the latest translations.
> Greenkeeper/scratch gui 0.1.0 prerelease.20191030020251

- src/lib/country-data.js
- test/unit/lib/country-data.test.js
Reverting because while this change works on the backend, it needs more work to make the educator registration form usable on the frontend. 
#3468 had the unintended effect of making the country dropdown always fail validation, so it was impossible to advance past that step of the educator registration flow.
> Revert "fixed country options to use full country name string as option value"

- src/components/join-flow/email-step.jsx
- src/components/join-flow/username-step.jsx
- src/lib/validate.js
- test/unit/components/email-step.test.jsx
- test/unit/components/username-step.test.jsx
username step and email step caches ignore api failures
no change to tests, as these validations check external API functionality that is not testable here
> username step and email step caches ignore api failures

- src/components/join-flow/country-step.jsx
- src/components/registration/steps.jsx
- src/lib/country-data.js
- test/unit/lib/country-data.test.js
See original PR https://github.com/LLK/scratch-www/pull/3468 and revert https://github.com/LLK/scratch-www/pull/3495
From original:
Resolves #3467
* for new join flow, sends country name strings, rather than country codes, when user registers
* for existing www registrations (teacher, student), leaves them unchanged
* renames and adds country data functions to be specific about whether they use country code, or country name, as option value
Added test to verify that options values are either country codes, or full country name strings
> Revert "Revert "fixed country options to use full country name string as option value""

- src/components/join-flow/birthdate-step.jsx
- src/components/join-flow/country-step.jsx
- src/components/join-flow/email-step.jsx
- src/components/join-flow/gender-step.jsx
- src/components/join-flow/join-flow.jsx
- src/components/join-flow/registration-error-step.jsx
- src/components/join-flow/username-step.jsx
- src/components/join-flow/welcome-step.jsx
- test/unit/components/email-step.test.jsx
- test/unit/components/join-flow.test.jsx
- test/unit/components/registration-error-step.test.jsx
- test/unit/components/username-step.test.jsx
Each step will log a separate page view.
The email step does not log in standalone mode because we already get a page view for loading the /join.
> Add analytics logging to join flow.  

- src/lib/validate.js
There are some cleanspeak level differences with api that need to be resolved to make it match the scratchr2 version. Until then, we'll use the scratchr2 endpoint.
> Switch to using scratchr2 check_username endpoint instead of api. 

- src/views/download/download.jsx
- src/views/download/l10n.json
Two more questions related to bluetooth on ChromeOS/Android.
They should only be visible if either Chrome or Android is selected, and the `CHROME_APP_RELEASED` feature flag is true.
> Additional ChromeOS/Android FAQs for the download page

- src/l10n.json
- src/lib/validate.js
- test/unit/lib/validate.test.js
Partially addresses https://github.com/LLK/scratch-www/issues/3526
If, in join flow username field, user types a username with spaces in it, provide a validation message specifically pointing out that problem, rather than showing a general error
Revised relevant test.
> if username has spaces, provide validation message specifically mentioning that

- src/views/credits/credits.jsx
- src/views/credits/people.json
Resolves #3410 
Adds 5 members, moves 7 members to Past Contributors, and removes one. Also, this fixes a bug where some avatars linked to invalid page, by checking if userName is truthy.
Tested by me on Windows 10 with Cygwin
> Credits member update

- src/routes.json
Without this change, links shared from platforms that append tracking parameters will break
> [Master] Support url parameters for 3 redirects

- src/components/registration/steps.jsx
Fixes the issue #3182, Teacher Registration page having different font weights for username and password labels.
Uses label tage instead of div-b combination for 'Create a Username'. Also updated the classname of the parent element to match the bottom margin.
Opened the page http://localhost:8333/educators/register to confirm the font weight is normal for the username label. No automatic test scripts needed.
> fixed the issue "Create a Username" has different font weight

- src/views/credits/credits.jsx
- src/views/credits/people.json
Resolves https://github.com/LLK/scratchr2/issues/5503 and https://github.com/LLK/scratch-www/issues/3592
* Added Robyn Bosic to credits page
* Alphebatized credits list by last name
* Alphebatized contributors list by last name
Looks like: 
(Robyn hasn't set a profile image yet)
> added robyn bosic to credits page; alphebeatized credits, contributors

- src/components/join-flow/join-flow.jsx
- src/lib/session.js
- src/redux/navigation.js
- src/redux/session.js
- test/unit/components/join-flow.test.jsx
Alleviates the problem of https://github.com/LLK/scratch-www/issues/3539 , even if it doesn't really solve the underlying problem.
* introduces lib/session.js, which has a `requestSessionWithRetry()` function which retries fetching session until it either gets one with a registered user, or runs out of tries
* adds a `refreshSessionWithRetry()` function to /redux/session.js, which replicates functionality of `refreshSession()` but calls `requestSessionWithRetry()` instead
* changes `join-flow.jsx` to use `refreshSessionWithRetry()` instead of `refreshSession()`; this means only setting the `state.waiting` state variable to `false` after the refreshSessionWithRetry promise resolves
* changes redux/navigation.js's `handleCompleteRegistration()` function to use `refreshSessionWithRetry()` …
> Retry fetching session until it succeeds, when registering using join flow

- src/l10n.json
- src/views/boost/boost.jsx
- src/views/download/download.jsx
- src/views/download/l10n.json
- src/views/ev3/ev3.jsx
- src/views/gdxfor/gdxfor.jsx
- src/views/microbit/microbit.jsx
- src/views/wedo2/wedo2.jsx
Fixes #3570 (previously reviewed as https://github.com/LLK/scratch-www/pull/3593)
Updates the FAQ/Troubleshooting sections for the Download page and extension landing pages.
Also removed the `CHROME_APP_RELEASED` feature flag since it's released now. Make sure to review ignoring whitespace for the flag removal.
On the [downloads page](https://scratch.ly/download) with ChromeOS or Android selected, additional troubleshooting for no visible Bluetooth devices, and question about where projects are stored.
Extensions pages (e.g. [microbit](https://scratch.ly/microbit)) all have an additional item with more detail about enabling Location services on Chromebooks and Android. Answer is visible regardless of OS as someone could be looking for help on a different OS.
https://scratch.ly/microbit
> [MASTER] Update troubleshooting and FAQ sections for Scratch App and hardware extensions

- src/views/preview/preview.scss
Resolves https://github.com/LLK/scratch-www/issues/2853
Implements the fix that @Smrman proposed in https://github.com/LLK/scratch-www/issues/2853#issuecomment-550104414 , which is to apply the `word-break: break-word` style to the `project-description` class.
Chrome:
Before:
After:
Firefox:
Before: (narrow window size):
After: (narrow window size):
Safari:
Before:
After:
> break word in project description

- src/lib/session.js
- src/redux/session.js
- test/unit/lib/session.test.js
Follow-on to https://github.com/LLK/scratch-www/pull/3576 
* refactors lib/session.js's function `requestSessionWithRetry()` so that the session fetch can retry an arbitrary number of times
* adds `requestSessionOnce()` convenience function
* refactors redux/session.js to reduce code duplication
* introduces tests for lib/session.js 
Lots of tests introduced for lib/session.js
Still no testing for redux/session.js though
> Refactor session fetching to reduce code duplication, make more testable

- package-lock.json
- package.json
Updates url-loader, generated from https://github.com/LLK/scratch-www/pull/3433
Note: url-loader has a major version release, 3.0.0 https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0 , but it requires node 10.13.0 or later, which I don't think everyone has.
> Greenkeeper/url loader 2.3.0

- src/components/page/www/page.jsx
- src/components/title-banner/warning-banner.jsx
- src/components/title-banner/warning-banner.scss
- src/views/splash/presentation.jsx
(develop PR: https://github.com/LLK/scratch-www/pull/3624)
Resolves #3620
Adds a "warning-banner" component and shows it, with a warning message about Mandrill outage banner, if user's local time is during the planned Mandrill outage.
Note that page styling is not consistent, so some pages have a margin above the banner, while others don't.
> [Master] Hotfix/mandrill outage page banner

- src/components/page/www/page.jsx
- src/components/title-banner/warning-banner.jsx
- src/components/title-banner/warning-banner.scss
- src/views/splash/presentation.jsx
Resolves #3620
Adds a "warning-banner" component and shows it, with a warning message about Mandrill outage banner, if user's local time is during the planned Mandrill outage.
Note that page styling is not consistent, so some pages have a margin above the banner, while others don't.
> [Develop] Hotfix/mandrill outage page banner

- src/components/join-flow/join-flow.jsx
- src/lib/session.js
- src/redux/navigation.js
- src/redux/session.js
- test/unit/components/join-flow.test.jsx
- test/unit/lib/session.test.js
Partially addresses https://github.com/LLK/scratch-www/issues/3539 , even if it doesn't really solve the underlying problem.
* introduces lib/session.js, which has a `requestSessionWithRetry()` function which retries fetching session until it either gets one with a registered user, or runs out of tries
* adds a `refreshSessionWithRetry()` function to /redux/session.js, which replicates functionality of `refreshSession()` but calls `requestSessionWithRetry()` instead
* changes `join-flow.jsx` to use `refreshSessionWithRetry()` instead of `refreshSession()`; this means only setting the `state.waiting` state variable to `false` after the refreshSessionWithRetry promise resolves
* changes redux/navigation.js's `handleCompleteRegistration()` function to use `refreshSessionWithRetry()` instead …
> Retry of the change that retries fetching session

- .travis.yml
Resolves https://github.com/LLK/scratch-www/issues/3215 , to correct a mistake in https://github.com/LLK/scratch-www/pull/3643 .
Second attempt to configure .travis.yml file to cause Travis's develop branch cron job to trigger our translation push script.
> attempt to get travis cron job to only run translations

- package-lock.json
- package.json
Hotfix to master with https://github.com/LLK/scratch-gui/pull/5333
This fix ensures that the full-screen "unsupported browser" modal does not show for the googlebot crawler when it fails to load full projects. To repro what this looks like, you need to do two things:
1. Enable "Request Blocking" for `assets.scratch.mit.edu/*` in the chrome dev tools to mimic what happens to the crawler, which is it automatically kills requests from the asset server when there are too many. 
2. Under "Network Conditions", uncheck "select automatically" and choose of the googlebot user agents. 
Now load any project page. You'll see the full screen "Your browser is not supported" screen:
Now do the same for request blocking on staging, and try to load a project as googlebot UA. You should not see the full …
> [Master] Hotfix project page indexing fix

- src/components/languagechooser/languagechooser.jsx
Part of fixing #3325 
Add leading `.` to the current hostname for the language cookie domain.
The scratchlanguage cookie was being set as `scratch.mit.edu` rather than `.scratch.mit.edu`, note the leading `.` Other backend servers processing the project creation did not have access to the cookie.
**Manual testing prerequisites:**
* access to the database where project metadata is stored
* open dev tools and delete the scratchlanguage cookie
- open browser settings and add another language, place it first in the language list
- click create
- editor loads in the new default language, and the project in the database has the same language in metadata
Delete the cookie in between these tests:
- On a www page (e.g., home, explore...), choose a language in the language menu
- create a project
- …
> Set language cookie domain to allow for cross-domain cookies

- src/init.js
- src/views/preview/project-view.jsx
Fixes issue with https://github.com/LLK/scratch-www/pull/3647 where having the old cookie left around prevents you from changing language.
On init, remove the old cookie if it exists.
On the project page, make sure `handleSetLanguage` also sets the domain.
Difficult to test locally due to hostname rules. See https://github.com/LLK/scratch-www/pull/3647 for testing steps.
> Ensure that the old scratchlanguage cookie is removed if it exists.

- src/init.js
It appears that setting the domain on the cookie prevents it from actually deleting the cookie.
> Really delete the cookie

- src/l10n.json
We were missing a string for the case where a user has not confirmed their email address. These string IDs are interpolated directly from the error code, so no other change is needed.
Resolves https://github.com/LLK/scratch-www/issues/2861 in a minimal way
Add a string for the error code that comes back `isNotPermitted`, which corresponds with a user who has not confirmed their email address.
This is the way it is now.
> Add comments.isNotPermitted string

- src/lib/validate.js
* Reverts the core change of https://github.com/LLK/scratch-www/pull/3507
* Sets up https://github.com/LLK/scratch-api/pull/884 to be tested/merged, after this is deployed
* uses api endpoint, rather than scratchr2, to validate usernames.
> use api instead of scratchr2 to validate usernames

- src/components/install-scratch/install-scratch.jsx
(Replaces #3736)
Release scratch-desktop 3.9.0 for Windows direct download. Also, for convenience, move the download URLs into a `const` near the top of the file.
The macOS build is not updated due to a problem with accessing the camera and microphone: LLK/scratch-desktop#109. Hopefully that fix will not take long and we'll get version 3.9.1 out soon, but we'll see.
If either of you would prefer not to move the URLs into a `const` like that, let me know and I can back that part out so we can discuss without blocking this release. Thanks!
> [Develop] hotfix/scratch desktop 3.9.0

- src/components/install-scratch/install-scratch.jsx
(Replaces #3736)
Release scratch-desktop 3.9.0 for Windows direct download. Also, for convenience, move the download URLs into a `const` near the top of the file.
The macOS build is not updated due to a problem with accessing the camera and microphone: LLK/scratch-desktop#109. Hopefully that fix will not take long and we'll get version 3.9.1 out soon, but we'll see.
If either of you would prefer not to move the URLs into a `const` like that, let me know and I can back that part out so we can discuss without blocking this release. Thanks!
> [Master] hotfix/scratch desktop 3.9.0

- src/components/helpform/helpform.jsx
- src/routes.json
- src/views/contact-us/contact-us.jsx
- take captcha off the helpform url
- use encodeUriComponent to make sure semicolons in the agent string don’t mess up the form parameters
- take the `$` end matcher off the route to allow for parameters to be passed
- fix forum links
- fix faq link `/faq` => `/info/faq`
> Fix contact-us mistakes

- package-lock.json
- package.json
We decided not to release the gui changes from this week. Removing the scratch-gui update so that the contact us page can be updated.
> revert gui to previous version

- src/components/modal/base/modal.scss
- src/components/modal/report/form-step.jsx
- src/components/modal/report/modal.jsx
- src/components/modal/report/modal.scss
- src/components/modal/report/report-options.js
This code splits the project report action into two separate panels, separated by a "next" button. It does not change the categories shown or anything else. This lays the groundwork for future changes to report flow, including adding subcategories and adding informational steps to help scratchers understand our community guidelines.
The major components of work are:
- Separated out the single `form` element into a reusable `FormStep` that can be given child elements to render and have submit handled. This allows us to build a multi-step form that accumulates data. This is inspired by the `Progression`/form usage in the join flow. 
- Separate the "report options" object and use PropTypes to make sure its structure is strictly managed. The reason for this is that I want to add subcategories …
> [Hotfix/Master] Split project report flow into two steps

- src/lib/route.js
- src/routes.json
- src/views/studentregistration/studentregistration.jsx
- test/unit/lib/route.test.js
Step towards resolving #5463
Step towards resolving #5463
* adds /signup/TOKEN route that points to src/views/studentregistration/studentregistration.jsx ( /class/ID/register/TOKEN will also still point to it)
* add lib/route.js library to parse URI pathname
* refactor URI path parsing in studentregistration.jsx to extract fields from either route above
* make studentregistration.jsx use available info to send request to /classtoken/TOKEN 
Added a unit test of route library function
locally, we can both:
* create a new classroom
* note the classroom ID
* generate sign-up link
* log out
* visit the sign-up link URL and try to register
* also visit the old version of the sign-up link URL, by changing it to classes/ID/register/TOKEN
response from API, when visiting www at …
> added /signup/TOKEN route; handle route alongside existing student signup route

- src/views/conference/2020/index/index.jsx
- src/views/conference/2020/index/l10n.json
This resolves #3781 
The Scratch Conference was delayed to 2021, so this pull request changes the Scratch Conference page in order to reflect the changes made to the dates of the Scratch Conference.
I didn't really understand how to test this, and when I tried to test it, it wouldn't work, so instead, I re-read the changes that I made twice in order to try and catch anything that I might have broken.
> Fix gh-3781: Delay Scratch Conference

- src/components/helpform/helpform.jsx
- src/components/helpwidget/helpwidget.jsx
- src/l10n.json
- src/lib/feature-flags.js
- src/views/contact-us/contact-us.jsx
- src/views/contact-us/contact-us.scss
- src/views/contact-us/l10n.json
Initial version of the Freshdesk widget that replaces the form with a pop-up widget that includes the ability to search the knowledge base for help. 
Copy is not final.
* current Contact Us with form continues to display
* redundant browser field has been removed
* redirects from scratchr2 will display the form with subject and body pre-filled
on staging server
add `?CONTACT_US_POPUP=true` to the Url to see the new contact-us page
* Get Help button and link open the widget
* redirects from scratchr2 will open widget already on the form with the fields pre-filled
_Note: running locally, run your server with `SCRATCH_ENV=staging`_
When this launches consider adding an integration test that clicks the Get Help button and confirms that the widget launches.
> Freshdesk widget

- src/routes.json
removes extraneous parenthesis from the student signup route's routeAlias field. Fastly was throwing an error because of it, understandably!
> remove extraneous parenthesis from student signup route

- src/components/install-scratch/install-scratch.jsx
Update Scratch Desktop download links for version 3.10.2
> [Develop] release Scratch Desktop 3.10.2

- src/components/install-scratch/install-scratch.jsx
Update Scratch Desktop download links for version 3.10.2
See also #3854
> [Master] release Scratch Desktop 3.10.2

- src/views/credits/credits.jsx
- src/views/credits/people.json
Resolves #3848 
Removes Andrew Sliwinski and Abisola Okuk from the current Scratch Team members section and adds them to the past contributors section.
> Move Andrew and Abisola to past contributors

- src/views/contact-us/contact-us.jsx
Enable Helpwidget, but keep showing the form for iOS 10 and lower.
Issue found during bug hunt where the help widget was not working on iOS 10
Checks the operating system and continues to show the form on the contact-us page if the OS is 'iOS' and version is <11.
I am not able to test this because I don't have and iOS 10 device. I was able to see it working by switching the condition to `iOS < 13` (since I have iOS 12 on my iPad)
> Enable Help widget

- src/components/registration/steps.jsx
- src/views/studentregistration/studentregistration.jsx
When a student is registering with a class, pre-fill the country selection drop-down with that of the educator attached to the class.
There are a few things I would like feedback on, including:
- I stopped short of removing the country selection drop-down entirely, which was suggested in the Trello card. I imagine there are a few situations where the student might legitimately want to register a different country compared to the educator, but I suspect they're very rare. On the other hand it doesn't seem harmful to have the drop-down visible, especially if it's usually pre-filled with the correct option. Thoughts?
- The first time the `StudentRegistration` component renders, it doesn't yet have the classroom's data; that's the reason for `this.state.classroom &&` when passing the …
> default student's country to educator's during reg

- src/components/install-scratch/install-scratch.jsx
Update the Scratch Desktop download links to release version 3.11.1
See also #4070
> [Master] update scratch-desktop download links for 3.11.1

- src/components/install-scratch/install-scratch.jsx
Update the Scratch Desktop download links to release version 3.11.1
See also #4071
> [Develop] update scratch-desktop download links for 3.11.1

- src/views/preview/preview.scss
Resolves, at least partially: https://github.com/LLK/scratch-www/issues/2513
Resolves https://github.com/LLK/scratch-www/issues/2853
(https://github.com/LLK/scratch-gui/pull/4827 will also help resolve, but this PR does not require it)
* Flexibly allows the project page player stage width to be controlled by gui, rather than enforced to a particular width
* changes overflow handling so that the page width stays matching the window width (rather than becoming out of step, as seen in the screenshot from #2513)
None
> Fix page width by hiding overflow, letting stage width be flexible

- package-lock.json
- package.json
- src/views/preview/preview.scss
Features
- Adding points in the middle of segments with the reshape tool no longer affects those segments’ shapes
- In reshape mode, points should now have larger hitboxes and hence be easier to drag
- The space between paint editor scrollbars and canvas edges now counts as part of the scrollbar hitbox
Bug fixes
- Gradient outlines now render properly on the stage
- Prevent memory leaks when dragging huge sprites around
- The pen should now draw long lines instead of dots on tablets where long lines weren’t working before
- Fewer AudioContext warnings (thanks, @watilde and @JinXJinX!!)
- Project Instructions and Notes and Credits should obey page width more consistently
- Project page background should extend fully across project page
> [Master] Release/2020-06-11

- src/components/registration/steps.jsx
- src/lib/country-data.js
- test/unit/lib/country-data.test.js
Small refactor as follow-up to https://github.com/LLK/scratch-www/pull/3856
Moves country code lookup logic into the country data library
> move country name lookup to library

- package-lock.json
- package.json
Fix #4025 Build failed in Node 12
Upgrade Node-Sass to 4.12.0
N/A
> Add node12 support, Fix #4025

- package-lock.json
- package.json
Reverts LLK/scratch-www#4026
It looks like LLK/scratch-www#4026 causes a problem with our SASS media queries and/or SASS variables. 
You can see this when the screen gets narrow:
Production:
With this change:
Some relevant issues and posts:
* https://sass-lang.com/blog/sass-35-release-candidate
* https://github.com/sass/node-sass/issues/2358
* https://github.com/sass/node-sass/issues/1886
* https://github.com/sass/node-sass/issues/2889
* https://github.com/sass/node-sass/issues/2762
* https://github.com/LLK/scratch-www/pull/4026/files
> Revert "Add node12 support, Fix #4025"

- src/views/credits/credits.jsx
Resolves #4051.
Updates the link to the Translators page on the Scratch Wiki.
// cc @benjiwheeler
> Update Translators page URL

- src/views/splash/splash.scss
Resolves #4023
Adds `overflow-wrap: anywhere` to fix text overflow (in "what's happening"). I'm not sure if it works on all browsers. If it does not, please tell me a fix.
Manually tested with inspect.
\
\
\
@benjiwheeler
> Fix text overflow in what's happening

- src/lib/decorate-text.jsx
Resolves #4072 
Mentioning welcomingcommittee creates link to the studio, not the user profile.
> Fix welcomingcommittee mention link href

- src/components/modal/addtostudio/modal.scss
Resolves #3775
Always applies `min-height: 0` for outer container. See also: https://moduscreate.com/blog/how-to-fix-overflow-issues-in-css-flex-layouts/
I manually added the CSS on the main website on Firefox and it showed the button as expected. I also tested it on Chrome and it worked just like before.
> Always apply min-height: 0

- src/views/preview/preview.scss
Resolves https://github.com/LLK/scratch-www/issues/4098
Resolves https://github.com/LLK/scratch-www/issues/4089
Resolves https://github.com/LLK/scratch-www/issues/4090
* Per @adroitwhiz's suggestion, moves `overflow: auto` and removes use of the deprecated `word-break: break-work`
* reverts change to guiPlayer's `max-width` which seems to coincide with a Safari rendering bug
These were introduced in https://github.com/LLK/scratch-www/pull/2518 .
Should be tested in multiple browsers. I have tested on Mac Chrome, Safari, and Firefox.
Test plan:
* on project page:
* go in and out of fullsrceen. confirm that fullscreen mode looks correct.
* go into fullsrceen, reload, click the back button. confirm that instructions/notes and credits take up normal width.
* resize page width and confirm all …
> fix Safari fullscreen CSS bugs

- src/components/install-scratch/install-scratch.jsx
Future Scratch Desktop releases will use redirects to point a stable URL for each platform to the latest version of that platform's installer. This means we will no longer need to make a `scratch-www` change for each Scratch Desktop release. This change is also the first of many steps toward renaming "Scratch Desktop" to "Scratch".
See also #4145
URLs tested by hand.
> [Master] use 'evergreen' URLs for Scratch Desktop downloads

- src/components/install-scratch/install-scratch.jsx
Future Scratch Desktop releases will use redirects to point a stable URL for each platform to the latest version of that platform's installer. This means we will no longer need to make a `scratch-www` change for each Scratch Desktop release. This change is also the first of many steps toward renaming "Scratch Desktop" to "Scratch".
See also #4146
URLs tested by hand.
> [Develop] use 'evergreen' URLs for Scratch Desktop downloads

- src/views/preview/preview.scss
Follow up to https://github.com/LLK/scratch-www/pull/4149 and https://github.com/LLK/scratch-www/pull/2518
* Added `overflow: auto` and `overflow-wrap: break-word` to credit-text class
Before:
After:
I tested in Mac Chrome, Firefox and Safari.
> add overflow settings to css for remix credit

- package-lock.json
- package.json
- src/components/join-flow/username-step.jsx
- src/components/modal/addtostudio/modal.scss
- src/lib/decorate-text.jsx
- src/routes.json
- src/views/credits/credits.jsx
- src/views/credits/people.json
- src/views/download/l10n.json
- src/views/preview/preview.scss
- src/views/splash/splash.scss
> [Master] Release 2020-07-08

- src/components/footer/www/footer.jsx
- src/lib/scratch-wiki.js
- test/unit/lib/scratch-wiki.test.js
Resolves #815 
This is similar to #4114 except two things:
- `getScratchWikiLink` is a library.
- `xx-yy`  fallbacks to `xx` first, then `en`
Added a unit test
> Set wiki link per user's selected language

- src/views/preview/meta.jsx
- src/views/preview/project-view.jsx
Resolves #3798 
Previously, if `projectInfo.author` is not available, there were no meta-tags. It was not a problem for logged-in users, because when they create new project, a new project is created immediately and author is passed. However, when not logged in, projects are not "created", so there is no author. In this case, check `userPresent` and if it doesn't exist, returns a helmet with `Scratch - Imagine, Program, Share` title. Other meta tags are omitted.
Manually tested
> Fix editor title when not logged in

- package-lock.json
- package.json
Pulls https://github.com/LLK/scratch-render/pull/660 (which reverts some changes to scratch-render) into the release branch.
> Update gui version hotfix/rever-scratch-render branch version.

- src/lib/jar.js
- test/unit/lib/jar.test.js
https://github.com/LLK/scratch-www/issues/3874
Changes the default behavior of the cookie jar library to set the sameSite cookie. This should be the right value for all of our existing cookies set from www. Browsers (e.g. Chrome and Firefox) have recently (or are about to) defaulted to sameSite=Lax. If we ever need another value, the library supports that via the opts object just like it does the expires value.
Added a new unittest for the jar library. I'm only testing Jar.set in this PR since that's what I changed.
> Make the cookie library set the SameSite cookie value to strict by default

- test/integration-legacy/smoke-testing/test_footer_links.js
https://github.com/LLK/scratch-www/issues/3027
Deletes the skipped tests from the footer integration tests.  These all link to external sites and are being tested separately.
> Removed skipped footer integration tests

- test/integration-legacy/smoke-testing/test_footer_links.js
The tests were failing on Travis, this should make them work smoothly.
Just removes the tap.plan() option.  After removing some tests, it didn't like that the number didn't match.
> Remove tap.plan() from footer links test

- .travis.yml
- package-lock.json
- package.json
Updates node version used by travis, which is necessary for this pr: https://github.com/LLK/scratch-www/pull/4261
Also updates the version of node-sass, which is required after updating node.
> Update node version used by travis and node-sass

- src/_frameless.scss
This used to work, even though it shouldn’t have. Upgrading node-sass caused our breakpoints to … break.  Without this, the compiler outputs invalid CSS including the "- 1", which causes the media query definitions to be ignored.
Resolves #4168 
Update syntax for operations in frameless.scss …
> Fix bad variable interpolation/calculation in frameless scss

- src/lib/jar.js
- test/unit/lib/jar.test.js
Changes the default behavior of the cookie jar library to set the sameSite cookie to Lax. Browsers (e.g. Chrome and Firefox) have recently (or are about to) defaulted to sameSite=Lax. If we ever need another value, the library supports that via the opts object just like it does the expires value.
If we default to strict here, the language for scratchr2 pages will be wrong when the user navigates to a scratchr2 page via a 3rd party (e.g. a Google search link)
Test Coverage:
Added a new unittest for the jar library. I'm only testing Jar.set in this PR since that's what I changed.
This is a the same as #4219, except with a default value of Lax instead of Strict.
Resolves #3874
> Make the cookie library set the SameSite cookie value to Lax by default

- src/components/navigation/www/navigation.jsx
- test/unit/components/navigation.test.jsx
This stops us from checking every 2 minutes. We'll still check each time a user navigates to another page.
(This is a copy of https://github.com/LLK/scratch-www/pull/4169 made against the hotfix branch instead of develop)
Back off how often we poll for new messages
> Exponentially back off the time between message polling.

- src/components/navigation/www/navigation.jsx
- test/unit/components/navigation.test.jsx
Release notes:
Instead of polling for messages every 2 minutes, back off the time exponentially -- i.e. 2min, 4min, 8min, etc.
> [master] Hotfix/messages

- package-lock.json
- test/integration/sign-in-and-out.test.js
An issue where updating chromedriver caused the sign-in-and-out integration tests in Jest to fail sometimes.  
Increases the timeout time when running locally and adds some waits in the tests to get them to pass more reliably.
> Update sign-in-and-out integration tests for new chromedriver

- src/components/thumbnail/thumbnail.scss
Partially addresses #3998.
Adds overflow, white-space, and text-overflow CSS elements
Tested with Inspect Element for both project and studio search.
Studio:
Project:
//cc @benjiwheeler
> Add overflow, white-space and text-overflow CSS elements

- src/routes.json
Resolves #4203 
This Pull Request adds redirects for the [Animate a Character](https://scratch.mit.edu/projects/editor/?tutorial=animate-a-character) and [Video Sensing](https://scratch.mit.edu/projects/editor/?tutorial=video-sensing) tutorials. https://scratch.mit.edu/animate-a-character will redirect to the Animate a Character tutorial, and https://scratch.mit.edu/video-sensing will redirect to the Video Sensing tutorial.
> Add redirects for Animate a Character and Video Sensing Tutorials

- .travis.yml
Motivation: stop running them on dependapot branches/PRs since they don't make sense.
Dependabot makes PRs from branches on LLK/scratch-www and travis was running the smoke tests there needlessly.
We're still running builds twice on these PRs... but this is progress.
> Stop running smoke tests unless the branch pushes to prod or staging.

- test/integration/selenium-helpers.js
Occasionally newer versions of chromedriver will not work with older versions of Chrome and vice versa.  Remote tests will then fail due to a mismatch between Chrome and Chromedriver.   
This change will cause the automated tests that run through Saucelabs to always use a version of chrome based on the chromedriver version.  Chromedriver versions are numbered to match the chrome versions they support, so it extracts the first two version number from the chromedriver package number to get the chrome version.  
This way we only need to update the version in one place.
> Pin chrome version for saucelabs to chromedriver version

- .travis.yml
This keeps the integration tests from running on PRs that are made from branches on LLK/www (e.g. all dependabot PRs)
It is a redo of #4450 that's regex had messed up slashes. In this one, /'s are escaped in the appropriate places (I think at least!) 
Thanks to @BryceLTaylor for pointing at the / problem.
> Only run integration/smoke tests on specific branches

- src/components/modal/mute/modal.jsx
- src/components/modal/mute/modal.scss
- src/components/modal/mute/mute-step.jsx
- test/unit/components/mute-modal.test.jsx
- test/unit/components/mute-step.test.jsx
Adds a 2 step modal for giving information about what it means to be muted. 
This is a step towards #4447. 
This is just the skeleton. The CSS is pretty solid, but there are still lots of things to do including:
- Wire up the modal to show at the right time
- Update to reflect final content & put the text in messages so it can be translated
- Add final images
- Correctly inject information about about time muted
> Initial skeleton of mute modal. 

- src/views/faq/l10n.json
Resolves #4299 
Fixes minor grammar mistake in the cloud section of the FAQ, @benjiwheeler
> Minor grammar fix in FAQ

- package-lock.json
- package.json
- test/integration/project-page.test.js
The Project Page integration test that checks the Copy Link modal fails on staging.  Also Chromedriver is getting out of date.
Skips the failing project page test for now until the underlying issue can be addressed.  (The test is new, the problem has been there for a while).  It also updates the version fo Chromedriver to match the newest version of Chrome.
> Skip failing project page test

- src/components/registration/steps.jsx
#4308 
I added a non breaking space, so the teacher account request form name warning should now have a space (assuming I did it correctly)
unfortunately, I do not have a setup where I can easily test scratch-www, but this is a small change and my fingers are crossed that I didn't mess up
> add missing space to teacher request form

- src/views/explore/explore.scss
- src/views/messages/messages.scss
- src/views/preview/preview.scss
Resolves #4260
Currently Load more buttons incorrectly scroll the page down in Chrome. This pull request should fix that.
cc @benjiwheeler
Manually tested.
> Fix "Load more" scrolling

- src/views/scratch_1.4/scratch_1.4.jsx
#4374 
I replaced each http link with an https link on the 1.4 download page.
i do not currently have a setup where i can test scratch-www but i made sure each link works in https and does not display the warning
> replace http links with https links on the 1.4 download page

- src/views/about/l10n.json
Resolves #4188.
Replace "Tips Page" with "Ideas Page" in the About page.
//cc @benjiwheeler
> Replace "Tips Page" with "Ideas Page"

- package-lock.json
- package.json
Reverts LLK/scratch-www#4602
It looks like the render bug we found in bug hunt already exists on production, see discussion here: 
https://github.com/LLK/scratch-render/issues/719
> Revert "Revert "Bump scratch-gui from 0.1.0-prerelease.20201025103629 to 0.1.…"

- src/views/about/about.jsx
- src/views/about/l10n.json
Resolves #4273
Changes the URL of the translation guide from [https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch](https://en.scratch-wiki.info/wiki/How_to_Translate_Scratch) to [https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators](https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators)
> update translation URL

- src/views/about/about.jsx
- src/views/about/l10n.json
Follow up from the annual report work, add a link to the Annual Report page from the About page.
- Tested locally:
> Add link to annual report from about page

- src/views/preview/comment/compose-comment.jsx
This is minor step towards correct time formatting. More coming later!
Work towards #4447
> Convert mute timestamp to always show in minutes.

- src/views/microbit/microbit.jsx
The firmware download URL on the micro:bit page no longer contains a version number. The download bucket has been configured to treat this new URL as a redirect to the actual file, including the version number. This way we'll be able to deploy firmware updates without needing to change any content in this repository.
Tested that the new URL redirects correctly. Right now it should redirect to `scratch-microbit-1.1.0.hex.zip`, the same file that was explicitly listed before this change.
> remove version number from micro:bit firmware URL

- src/views/teachers/landing/landing.jsx
Changes: 
-  On the Educators page, changes the "Teacher Account Setup Guide" link from a .doc link to a PDF link: https://resources.scratch.mit.edu/www/guides/en/scratch-teacher-accounts-guide.pdf 
This link can be found in the Teacher Accounts section of the Educators page: https://scratch.mit.edu/educators#teacher-accounts
> Change link to Teacher Account Setup Guide on Educators page

- src/views/preview/comment/comment.scss
- src/views/preview/comment/compose-comment.jsx
- test/unit/components/compose-comment.test.jsx
Also, keep showing the blue comment status box based on when the mute 
expires rather than basing it on the status of the comment box itself.
Thanks to @seotts for pairing!
> Disable comment box functionality when you've just been muted.

- src/views/sec/l10n.json
Replace the phrase "historically underrepresented in computing” with “ historically excluded from computing.”
Change requested from KO.
/cc @chrisgarrity I asked about the l10n update process about this on slack, but my understanding is that this will clear out existing translations, which I think is appropriate for this situation, since it is a meaningful change and not just a typo.
> Update the SeC page wording

- src/views/sec/l10n.json
Include the "with help from Google.org" in the SEC intro paragraph.
> [hotfix/master] Include funding support on Education Collaborative intro

- src/views/preview/comment/compose-comment.jsx
- test/unit/components/compose-comment.test.jsx
Don't show the compose box if they're muted, but do show it, but greyed 
out, if they just posted a comment that resulted in a mute.
Still TODO: handle reply link. 
More progress toward https://github.com/LLK/scratch-www/issues/4459
The unittests I wrote for the last pass of this work were already in place. I just had to change the values of what is shown and not to reflect the updated behavior.
> Show the comment status box on project page loads if the user is muted.

- src/components/modal/mute/modal.jsx
- src/l10n.json
- src/views/preview/comment/compose-comment.jsx
- src/views/preview/l10n.json
- test/unit/components/compose-comment.test.jsx
- test/unit/components/mute-modal.test.jsx
resolves #4691 
Wraps the MuteModal in the Intl HOC and moves all strings into l10n files.
The strings about muting are in the general `l10n.json` because they will be used in both the commenting status and mute modal components. `next`, `back`, and `close` were already in the general strings, so just reused them.
Strings needed for the compose-comment component are only on the project page (preview view), so they are in the view's `l10n.json` file.
Updated the mute modal tests to handle being wrapped in the intl HOC. For the tests that actually mount the component, it meant finding and checking the `MuteModal` component within the wrapper instead of testing the wrapper component.
> Localize mute

- src/components/registration/steps.jsx
- src/lib/validate.js
Step towards resolving https://github.com/LLK/scratchr2/issues/5563
This is step 1 of 2. Step 2 will be to remove the deprecated check_username code from scratchr2.
In educator registration, uses the newer api checkusername endpoint rather than the older scratchr2 check_username endpoint.
Adds some logic (and comments) to make the handling more robust to errors.
It's not clear to me whether there's a good way to add tests for this.
> switch educator registration checkusername endpoint from scratchr2 to api

- src/components/people-grid/people-grid.jsx
- src/views/annual-report/annual-report.jsx
Clicking on a Scratch Team member in the Annual Report Team section opens their profile in a new tab
* Clicking on a Scratch Team member in the Annual Report Team section opens their profile in a new tab
* Clicking on a Scratch Team member in the Credits page opens their profile in the _same_ tab
> In the Annual Report Team section, open link to Scratch Team members in new tab

- src/components/world-map/world-map.jsx
- src/views/annual-report/annual-report.jsx
- src/views/annual-report/annual-report.scss
* Decreases the thickness of country borders on the map so small countries and islands are more visible (see Hawaii and Indonesia for examples)
* Show data for the country Eswatini. This required changing the way we display country name in the map so that the display name can be different than the country name Plotly uses, as Plotly only knows Eswatini by its old name (Swaziland)
* Remove untested CSS for RTL
* Compare the country border thickness to production. It should be thinner. You should be able to see more of Hawaii and Indonesia.
* Eswatini (east of South Africa) should have data and should be called Eswatini.
> World map fixes - Border thickness, Eswatini, remove unused css

- src/components/modal/mute/modal.scss
- src/views/preview/comment/compose-comment.jsx
- src/views/preview/l10n.json
- test/unit/components/compose-comment.test.jsx
This adds back the reverted change with additional automod messaging. It fixes the issue that resulted in an error about 'currentMessageType.'
To test when variable muting is not enable, check that you can comment regular comments and that you get a regular orange error when you try to comment vulgarity.
When variable muting is enabled, test that different types of inappropriate comments result in different messaging.
> Add back new automod messaging

- src/views/annual-report/annual-report.jsx
Removes all usage of FormattedHTMLMessage in Annual Report and replaces them with FormattedMessage. All of the uses were in the Supporters section and had no actual HTML in the strings. There should be no visible changes to that or any section.
**In bughunt...**
* Test that the Supporters section text is the same in production and staging when language is English
* Test that production and staging are the same amount translated when language is not English (Italian, French, and Korean have a lot of translations)
> Remove use of FormattedHTMLMessage in Annual Report

- src/components/modal/mute/modal.scss
This reduces the vertical padding in the mute modal to better fit on shorter screens.
> Update vertical spacing on mute modal

- src/views/search/search.scss
Resolves #4624 
Fixes a bug where clicking "Load more" on search results would scroll the page down.
None
> Fix "Load more" scrolling on search results

- src/views/preview/comment/compose-comment.jsx
Fixes #4868 and #4869
Fixes the issue where the "general" mute message is shown before refresh. Also fixes the translation id issue in the vulgarity message. 
When you get muted for vulgarity, unconstructive language, or PII, you should see the correct messaging.
> Show correct mute messaging instead of always the general message

- src/views/preview/comment/compose-comment.jsx
- test/unit/components/compose-comment.test.jsx
They already had a disabled style applied to them, but now they are not clickable either.
#4918 
> Set comment post and cancel buttons to be disabled when user is muted.

- src/views/sec/l10n.json
In the section "Eligibility," the first bullet point should say:
Primarily focused on supporting traditionally underrepresented youth, including Black, Latinx, and Indigenous people in the United States and/or globally
Key changes:
- This PR changes "Indigenous Americans" to "Indigenous people"
- This PR makes the 'x' in Latinx be lowercase
> Hotfix - Changed text on SEC page

- src/lib/format-time.js
- test/unit/lib/format-time.test.js
#4886 
Round to the nearest minute, except for when there is less than 1 minute. In that case pin to 1.
Unit test added for 15sec remaining.
> Change time library to default to 1 minute when the time remaining is less than 30 seconds.

- package-lock.json
- package.json
- src/lib/format-time.js
- src/lib/relative-time-polyfill.js
Safari < 14 does not support Intl.RelativeTimeFormat which is used in the moderation messaging. Adding this polyfill to support it.
make sure to test on a variety of browsers and versions. Specific ones to test:
> Add @formatjs/relativetimeformat-polyfill

- src/components/modal/mute/modal.jsx
- src/views/preview/comment/comment.jsx
- src/views/preview/comment/compose-comment.jsx
- test/unit/components/compose-comment.test.jsx
https://github.com/LLK/scratch-www/issues/4741
There are a few cases this tries to handle:
- User is already muted and clicks to reply to a comment:  The mute modal should open to the page that tells them how long they are muted for. The blue box with comment info should no longer show under the reply since it should already be at the top of the list of comments. 
- User replies to a comment with content that gets them muted: The user should get the mute modal opened on the first page and show the blue box since it won't be shown at the top of the list of comments.
There are unittests for this new logic
> Open mute modal from reply button if you're muted.

- src/components/forms/phone-input.jsx
- src/components/forms/validations.jsx
- src/components/registration/phone-number-step.jsx
- src/components/registration/steps.jsx
- src/views/teacherregistration/teacherregistration.jsx
Paired on this with @picklesrus 
This fixes an issue (unfiled) where the `libphonenumber` dependency was being loaded on every page, even though only one of our pages actually uses phone number validation (teacher registration). 
There are two parts: 
1. da2ca40 moves the `isPhone` formsy validation out of the common validations registered from `forms/form.jsx` out into the `forms/phone-input.jsx` component itself so that the `isPhone` validation is only registered when you require the `PhoneInput` component. This allows forms that do not use that validation (e.g. login, language switcher) to not load the 500k+ libphonenumber dependency. This change removed that library from the `common.bundle.js` and made it only get required from `teacherregistration.html` but also `teacher waiting …
> Don't require a big phone number validation library on every page

- src/components/world-map/world-map.jsx
This reduced the size of the library that we are loading for WorldMap, by creating a Plotly bundle that only supports the choropleth visualization type.
To test, we should verify that this decreases the size of Plotly in www. We should also check that the world map continues to show up on the annual report.
> Create Plotly bundle to load only choropleth

- src/views/preview/comment/compose-comment.jsx
- src/views/preview/l10n.json
Adds a mute message for spam comments: https://docs.google.com/document/d/1FNEB8LN-VrlzcKwRATRjYjqT45buHDQ6bBEBErFJ6OA/edit#
To test, we should try making spam comments on projects (example comment: "10 facts about you") to see the new modal messaging. Other types of muted comments should work the same as before.
> Add spam mute message

- package-lock.json
- package.json
- test/integration/my-stuff.test.js
- test/integration/sign-in-and-out.test.js
Redo of https://github.com/LLK/scratch-www/pull/5077 , this time with more care not to make unnecessary changes to package-lock.json
Allows integration tests to pass locally while running chrome version 88
Updates chromedriver to 88.
Increases the timeouts for certain jest tests from 10 seconds to 20 seconds when running locally. The new version of chromedriver was causing these tests to timeout, but increasing the timeout allowed them to pass.
> Bump chromedriver version to 88, increase jest integration timeouts

- src/redux/studio.js
- src/views/studio/lib/fetchers.js
- src/views/studio/studio-info.jsx
- src/views/studio/studio.jsx
Create a reducer for the studio info and studio roles data. Nothing too interesting, changed the `useState` call that was previously there to use redux instead. The roles information is based on an upcoming API for getting the logged in users relationship to the studio. 
With the role information in redux, we can start making selectors to slice permissions information out of the store, like whether the current user can add/remove projects, edit the studio description, invite/promote curators, etc... That is next up.
> Fetch studio info and roles in redux

- .circleci/config.yml
- .travis.yml
Turns on the deploy and integration jobs for develop, hotfix/*, and release/* branches for CircleCI and turns them off for those same branches in Travis.
Includes running integration tests for the deploy to staging.
> circleci deploy to staging with circle instead of travis

- src/routes-dev.json
- src/routes.json
Allows the in progress www studios page to be viewable on staging and production.
Moves the studios route from routes-dev.json to routes.json
These routes are being blocked by fastly if you are not coming from certain specific ip addresses.
> Move the studio route from routes-dev.json to routes.json

- src/redux/studio-comment-actions.js
- src/views/preview/comment/comment.jsx
- src/views/preview/comment/compose-comment.jsx
- src/views/preview/comment/top-level-comment.jsx
- src/views/preview/presentation.jsx
- src/views/studio/studio-comments.jsx
- src/views/studio/studio.jsx
This PR starts some of the studio comments work, fetching the top level comments and displaying them on the comments tab of the studios playground.
- Create a studio comment actions creator using the one from project comment actions as a model.
- Hook up the comments reducer and actions to the studio comments tab
- Generalize the comment components (still currently located with the Project page code) so that they can also be used with studios. The main piece of work here was just to pull out the comment POST URI out as a component prop.
- Update project page to pass in the `postURI` prop instead of the `projectId` prop
- Add the UI for composing a comment and the list of comments to the studio comments tab
- Start to hook up some initial state controlled rendering (only displaying the …
> Studio Comments Fetching & Initial UI

- src/views/scratch_1.4/l10n.json
#4913 
l10n string changed from "Compatible with Mac OSX 10.4 or later" to "Compatible with Mac OSX 10.4 through 10.14".
I also checked to make sure that there weren't any other instances of "Compatible with Mac OSX 10.4 or later" left in the repo, seems that there was only this one instance.
(Though notably, the "through 10.14" substring was already present in the same l10n file, on line 25: https://github.com/LLK/scratch-www/blob/develop/src/views/scratch_1.4/l10n.json#L25 )
No tests were conducted since this is just a simple l10n string change.
> Fix gh-4913: MacOS version string update

- src/views/studio/studio-comments.jsx
@kchadha looks like we forgot to include the `onAddComment` prop for the studio comments (I think we must have missed a last commit, postURI was also missing but I caught that before the previous PR)
> Include onAddComment for studio comments

- src/redux/comments.js
- src/redux/studio-comment-actions.js
- src/redux/studio.js
- src/views/studio/studio-comments.jsx
- src/views/studio/studio-info.jsx
- src/views/studio/studio.jsx
This is a proposal of sorts, to start using a capability we don't use anywhere else in our codebase.
We often extract data from the redux store, give it to a component via props, not so that it can be rendered, but so it can be used as the arguments to a callback that calls dispatch ([see this for example](https://github.com/LLK/scratch-www/blob/develop/src/views/studio/studio-info.jsx#L47-L58)). This clutters our components with props that aren't used for rendering. It also isn't necessary: the state is available to redux thunks via the `getState` function. The redux-thunk readme shows how this works: https://github.com/reduxjs/redux-thunk#motivation
Use `getState` inside of thunks to retrieve the data we need (often username/token/permissions) instead of passing that data out of the …
> Use getState in thunks instead of passing props around

- src/redux/studio-comment-actions.js
- src/redux/studio.js
- src/views/studio/studio-comments.jsx
- test/unit/redux/studio.test.js
This PR hooks up the remaining actions for studio comments:
- Loading more replies for a thread
- Deleting a comment
- Restoring a comment
- Reporting a comment
This PR also adds permissions selectors and extensive testing for them. The idea of the extensive testing is not that the selectors are particularly complex, but that they may change over time (they are not intended to be 100% accurate right now even), and we want to be very confident about both the current state of permissions and making changes to those permissions. The structure/format of these tests should be considered experimental, I don't think we've used [`test.each`](https://jestjs.io/docs/api#testeachtablename-fn-timeout) anywhere yet. The goal primarily is ease of answering the question: _can X do Y?_
This PR also …
> Hook up remaining comment actions for studio comments

- .circleci/config.yml
- .travis.yml
Adds the deploy-production and integration jobs to the circleci config.
Removes the deploy step from travis entirely.
Removes the smoke job from travis entirely.
Includes running integration tests against production after the deploy
> Move deploy and integration tests to circle

- src/redux/session.js
- src/redux/studio-mutations.js
- src/redux/studio-permissions.js
- src/redux/studio.js
- src/views/studio/studio-comments-allowed.jsx
- src/views/studio/studio-comments.jsx
- src/views/studio/studio-description.jsx
- src/views/studio/studio-follow.jsx
- src/views/studio/studio-image.jsx
- src/views/studio/studio-info.jsx
- src/views/studio/studio-open-to-all.jsx
- src/views/studio/studio-projects.jsx
- src/views/studio/studio-title.jsx
- src/views/studio/studio.jsx
- test/unit/redux/session.test.js
- test/unit/redux/studio-permissions.test.js
- test/unit/redux/studio.test.js
This PR introduces a new reducer, studio-mutations, which includes data about client-side editing of studio information like following, title, description, etc. This PR also includes 3 new wireframed components for editing studio title, description and follow status. 
I found it made more sense to keep the loading/error states for mutating data in a separate place from where we are initially fetching and storing that data. The main studio reducer listens for `COMPLETE_STUDIO_MUTATION` to update the actual data in redux, and the studio-mutations reducer just tracks an in-progress flag (per field) and a mutation error property (per field). 
This PR also includes an additional permission selector (canFollowStudio) which right now is just "isLoggedIn", but can be modified as needed in the …
> Add client-side editing of studio info

- src/views/studio/studio-comments.jsx
- test/unit/components/studio-comments.test.jsx
Resolves an issue we found in testing where an admin user might navigate directly to /studios-playground/123/comments and would see the comments as if they weren't an admin. The reason is that comments do not wait to load for the user session to return, because for almost all users it doesn't matter. But admins see reported comments, so the comment list either has to wait for the user session to return (slowing down the experience for all users) or reset the comment list when the session returns as an admin (possibly causing a layout shift only for admins as their logged out comment list gets replaced by the admin one). I chose the second option, since it will provide the fastest experience for far more people.
_Describe what this Pull Request does. Be sure to include a brief description …
> Reset studio comments when admin logs in

- src/redux/studio.js
- src/views/studio/studio-description.jsx
- src/views/studio/studio-follow.jsx
- src/views/studio/studio-image.jsx
- src/views/studio/studio-info.jsx
- src/views/studio/studio-tab-nav.jsx
- src/views/studio/studio-title.jsx
- src/views/studio/studio.jsx
- src/views/studio/studio.scss
Implement the first round of styling for the studio "info" bar on the left with the title/image/description/follow action.
The bulk of the code change is layout refactor. I tried to make it so that each component exported a single element, using css classnames to indicate fetching/mutating state so those can be styled. The layout is implemented using css grid, since that is the easiest way to add gutters between elements, even though this is a 1d layout right now. 
The first commit also removes some unneeded status state transitions that I found while stepping through the redux dev tools to look at the loading progress.
/cc @seotts this is a pretty css-heavy PR, i'm happy to assign it elsewhere or walk through the css with you. There is some fun stuff there :)
> Studio info styling

- .circleci/config.yml
The translation push is still happening on Travis.  This is a step towards moving off travis and onto circle.
This turns on a cron job that runs the push translations job.  It runs at midnight UTC (8pm EDT).  It does not stop Travis from running the same job, so they should both be pushed.  This is so we can test to make sure Circle is doing it correctly before turning off the Travis cron job.
> circleci turn on translation push cron job

- src/redux/studio-permissions.js
- src/redux/studio.js
- src/views/studio/lib/fetchers.js
- src/views/studio/lib/studio-member-actions.js
- src/views/studio/lib/studio-project-actions.js
- src/views/studio/studio-curator-invite.jsx
- src/views/studio/studio-curator-inviter.jsx
- src/views/studio/studio-curators.jsx
- src/views/studio/studio-managers.jsx
- src/views/studio/studio-member-tile.jsx
- src/views/studio/studio-project-adder.jsx
- src/views/studio/studio-project-tile.jsx
- src/views/studio/studio-projects.jsx
- src/views/studio/studio.jsx
- src/views/studio/studio.scss
- test/helpers/state-fixtures.json
- test/unit/redux/studio-permissions.test.js
This is an initial pass at the functionality for:
- Adding / removing studio projects
- Inviting, accepting invite, promoting and removing studio curators and managers
I know there is a lot here @seotts and a fair amount of the redux related stuff is subject to some churn. The difference from previous PRs is that I'm not attempting to manage all of the mutation/error state in redux, i'm letting the react components handle that by using the fact that thunks are promises. I tried a few different ways to manage mutation state for all the different actions in redux, and it was a lot of code for little benefit (there are no other consumers of an individual curators "removal in progress" state, so it isn't worth keeping in redux). I may revisit the choice to keep other mutation state in redux, …
> Add functionality for adding/removing projects and managing curators

- .circleci/config.yml
The cron job that pushes translations to transifex failed with the error: 
Error: Cannot find module 'glob'
We weren't running install (or CI in this case) in the job so it did not have access to the glob package.
Adds a run step that runs npm ci to the update-translations job
> Run npm ci in update-translations cron on circle

- src/redux/studio-report.js
- src/views/studio/studio-info.jsx
- src/views/studio/studio-report.jsx
- src/views/studio/studio.jsx
This PR adds a basic wireframe of the studio report action. I included open/close states since it'll be a modal, but didn't actually make it a modal yet. You can select the field to report.
> Studio reporting using legacy endpoint

- src/redux/session.js
Reverts LLK/scratch-www#5220
Turns out we did need those redundant entries with the slashes after all!
Fix seems to be to either strip the trailing slash from the pathname, or reverse the order of the indexOf and use some kind of reducer to check if the pathname contains any of the goodlist entries.
> Revert "Add privacy policy and terms of use to allowlist"

- src/_colors.scss
- src/components/forms/button.jsx
- src/components/forms/button.scss
- src/views/splash/donate/donate-banner.jsx
- src/views/splash/donate/donate-banner.scss
- src/views/splash/l10n.json
- src/views/splash/presentation.jsx
- src/views/splash/splash.jsx
Resolves https://github.com/LLK/scratch-www/issues/5318
* adds donate banner component and css
* modifies button component to have "close" version, to be reusable
* modifies splash/splash.jsx and splash/presentation.jsx to collect similar banner handling in one place
* adds handling for closing the banner and for redirecting user to donate page
Closing the banner doesn't persist for long -- if you browse away from the splash screen and come back, it will reappear.
unclear if it makes sense to add tests?
> add donate banner, make close button a mode of button component

- src/components/forms/button.jsx
- src/components/forms/button.scss
Follow-on to https://github.com/LLK/scratch-www/pull/5345 , which used an existing classname, `.close-button`, that conflicted with the modal close button used in the add to studio and copy link modals.
Renames it to `.forms-close-button`.
> rename .close-button style to not conflict

- src/views/splash/splash.jsx
Follow up to https://github.com/LLK/scratch-www/pull/5345 , fixing logic around when to show intro banner.
Originally, the logic was:
* if user is logged out, AND we're not showing hour of code banner, show intro banner
https://github.com/LLK/scratch-www/pull/5345 mistakenly changed the logic to:
* if we're not showing hour of code banner, show intro banner
This change changes the logic back to:
* if user is logged out, AND we're not showing hour of code banner, show intro banner
> fix logic for when to show intro to users

- src/views/developers/developers.jsx
In the last fix, we introduced a problem where "Contact Us" was not a FormattedMessage. This PR fixes that
> Fixed problem introduced by previous fix

- src/views/preview/comment/comment.scss
Round and outline avatars for comments. The spec actually wants these outlines to be black and inset, but having such an outline that is also rounded is not supported on most browsers yet (see https://bugs.chromium.org/p/chromium/issues/detail?id=81556) so I put the border outside the avatar instead and instead made it the color of the dotted line around editable fields
Spec:
Current:
Proposed:
> Outlines for avatars

- src/redux/session.js
- src/redux/studio.js
- src/views/studio/l10n.json
- src/views/studio/lib/user-projects-actions.js
- src/views/studio/modals/user-projects-modal.jsx
This PR connects the "students" filter up to the new api endpoints for getting projects shared by students who are in the classroom the studio is a part of (phew, that was a mouthful). @seotts this uses both the endpoints you introduced, first if the user is an educator, check if the studio is part of a classroom. Then the user-projects-modal shows a "students" filter, which requests projects from the other endpoint. 
As a bonus, i also updated the "recent" filter to have the correct uri and also send authentication along. That endpoint isn't in production yet, but i tested it locally and it was working well /cc @cwillisf.
> Show "students projects" filter on studio project browser

- src/components/forms/validation-message.jsx
- src/redux/studio-mutations.js
- src/views/studio/l10n.json
- src/views/studio/studio-curator-inviter.jsx
- src/views/studio/studio-description.jsx
- src/views/studio/studio-image.jsx
- src/views/studio/studio-project-adder.jsx
- src/views/studio/studio-title.jsx
- src/views/studio/studio.scss
Include the existing `<ValidationMessage />` component when rendering the project adder and curator inviter. Show some basic error messages. Although there are some more specific messages we can include in the future, this is enough to get us started and we can come back to more later. Part of the reason I'm leaving the project one generic is because we need to resolve some issues with the backend before returning richer error messages.
> Add error display for studio curator and project adder inputs

- src/components/overflow-menu/overflow-menu.jsx
- src/redux/studio-permissions.js
- src/views/studio/lib/studio-member-actions.js
- src/views/studio/modals/user-projects-modal.jsx
- src/views/studio/modals/user-projects-tile.jsx
- src/views/studio/studio-member-tile.jsx
- src/views/studio/studio-title.jsx
- src/views/studio/studio.scss
- test/unit/redux/studio-permissions.test.js
7 quick fixes from the test on may 14. 
- Fix loadMore not working for user-projects-modal
- Fix awkward project thumbnail layout issues
- Fix issue where multiple overflow menus could be opened at once
- Allow curators to remove themselves
- Trim whitespace from username input
- Allow space to trigger submit on project tiles in modal because they are buttons and should act like it to the keyboard
- Make enter submit title field instead of adding newlines
Definitely recommend reviewing this in the "commit-by-commit" view.
> Bugfixes for studio playground test May 14

- .circleci/config.yml
Lets us run checks on branches before merging PRs
The deploy step was called "deploy staging" even when pushing to production
Pushing up the artifacts from the build step was quite slow
Makes build-develop job run on circle for all branches except master
Renames the name of a run step to be more generic
compress artifacts before storing them
> Finalize Circleci setup

- src/redux/studio-mutations.js
- src/views/studio/studio-image.jsx
This PR addresses an issue where the thumbnail image may not update after submitting a new studio thumbnail file.
The fix is to make the studio thumbnail update action to return a promise with a base64 encoded image source, read directly from the uploaded file. The thumbnail component will prefer to use that preview, instead of the response from the server, if available. This is because the image is uploaded but may not be available from the CDN immediately. 
The upload action does purge the image cache, but that is an async thing and can take a variable amount of time, so cannot be relied on. This is the equivalent to a "don't GET after POST-ing" replication-lag-esq problem, but instead of a lag between the primary and the replica db, it is between the primary image store and the edge …
> Use client-side image preview for studio thumbnail instead of server response

- test/integration-legacy/selenium-helpers.js
- test/integration/selenium-helpers.js
The tap and jest integration tests were expecting a travis build id which didn't exist since we switched to travis.  
Both the integration and the integration-legacy selenium-helpers.js file now set the buildID to the Circle workflow id.  The text of the name passed to saucelabs also has been updated to say CircleCI instead of Travis.
The integration tests should still pass and on saucelabs they should report the workflow id from circle.
> Use circleCI build ID for saucelabs test names instead

- test/integration-legacy/selenium-helpers.js
- test/integration/selenium-helpers.js
The workflow ID is a long string of characters that isn't particularly useful in identifying which build is being used.
Uses the CIRCLE_BUILD_NUM environment variable instead, which will be a 4 digit number that is findable in CircleCI's UI and easy to associate with the build
Saucelabs tests will present a useful build id during integration tests.
> use Circle’s BUILD_NUM instead of WORKFLOW_ID in saucelabs tests

- src/views/studio/studio-admin-panel.jsx
- src/views/studio/studio.jsx
- src/views/studio/studio.scss
- test/unit/components/studio-admin-panel.test.jsx
Render an iframe of the adminpanel for admin users alongside the page. This follows the pattern from projects with a couple deviations.
- There are no modals on the studio admin panel, so logic/styling around that was removed. Additionally the iframe can only cause a panel close, not a panel open, so only the `closePanel` event is listened for. 
- I grouped together the local storage logic with setting the class on the `#view` element, which is needed since it is rendered outside the tree but needs to have a css class to prevent overlapping items.
- I added tests for the behavior including localstorage and iframe messaging.
/cc @rschamp i'll also assign you the backend side of this as well to take a look at.
> Studio admin panel

- src/components/subnavigation/subnavigation.scss
- src/views/studio/modals/user-projects-modal.jsx
- src/views/studio/modals/user-projects-modal.scss
Keyboard navigation works with interactive HTML elements, like links and buttons. Our subnavigation component expects list items as children, for styling. In many places on www, these list items are wrapped in `<a>` elements, so keyboard navigation does work (e.g. on the "explore" page). 
This change:
- changes the subnavigation styling so it can apply to list items or to buttons
- changes the studio page's "add to studio" modal subnav to use buttons instead of list items, so that keyboard nav can work
> Fix keyboard navigation in "add to studio" modal

- src/routes.json
Resolves #5197
To test:
- /conference redirects to /conference/2021
- /conference/2020 redirects to /conference/2021
- /conference/2021 shows the same content as /conference/2020 does currently
- /conference/2019 (and below) still works as it did previously
> Bump conference URL one year

- test/integration/footer-links.test.js
One of our integration tests depends on /conference/2020, so update to the new date
> Fix integration test broken in #5476

- src/redux/session.js
- src/views/studio/studio-comments.jsx
- test/unit/components/studio-comments.test.jsx
This PR fixes an issue we found in testing where admins could not always see the deleted comments list. 
The cause is trying to fetch studio comments without waiting for the session, because the `isAdmin` flag is becoming true after the initial non-admin comment request went out, but before any comments are loaded. Since the logic for re-requesting admin comments only works if there is a change in the number of comments in the list, and the reset is being triggered before any comments are loaded, there is no change and no comments are re-requested. I was hoping to avoid this, but I think for consistency sake we need to wait until the user session is fetched to start the comment request, so we can know for sure which endpoint to use. this is how the project page works as well.
It takes a …
> Wait for session to be fetched before loading comments

- src/views/studio/l10n.json
- src/views/studio/studio-project-adder.jsx
Fixes an issue where all "add project" errors were being flattened into a single error message. I added text for more of the errors, which will definitely help with testing, even if we don't choose to keep all the messaging.
This uses the same `errorToMessageId(error)` pattern from the curator adder
> Handle more types of project add errors

- bin/configure-fastly.js
- package.json
Resolves https://github.com/LLK/scratch-www/issues/4791
* when deploying static assets to S3, sets the "Surrogate-Key" header to value "static-assets".
* when finished with upload part of deploy, purges Fastly surrogate key "static-assets", instead of purging all.
none
> set, purge static_assets surrogate key on deploy

- src/l10n.json
- src/views/preview/comment/comment.jsx
- src/views/preview/comment/comment.scss
- src/views/preview/comment/top-level-comment.jsx
- src/views/studio/studio-comments.jsx
Towards the Studios migration work. 
- Introduce a comment thread limit and display messaging when a user tries to add to a comment thread that has reached the limit.
- The user should not see more than one thread limit messaging box on a comments page.
Tested locally.
For easier local testing you might want to adjust the thread limit number.
On the studios page:
- Ensure that clicking reply on a comment thread that has reached the limit displays the blue messaging box.
- Clicking reply on any comment thread that has reached the limit should display the blue messaging box below the comment the user tried to reply to
- If there was another open, it should go away.
- Ensure that clicking reply on a comment thread that hasn't reached the limit still displays the comment compose box.
The …
> Comment thread limit

- src/views/preview/comment/top-level-comment.jsx
Updates a reference to an old l10n string id that we're no longer using.
> Fix l10n string ID where it previously got missed.

- src/views/preview/comment/comment.scss
Fixes the alignment of the reply status box which appears when the comment thread limit has been reached. The status box should align with the comment bubbles.
**After this change:**
> Fix reply status box alignment.

- src/views/preview/comment/top-level-comment.jsx
- src/views/studio/studio-comments.jsx
Resolves an issue found during the bug hunt:
> In studios-playground comments, can add more than 25 replies to a comment
> 
> Steps:
> add 25 replies to a top level comment
> reload page so that replies are hidden like this:
>  ![image2](https://user-images.githubusercontent.com/1786240/120556212-2f576980-c3ca-11eb-8a87-b88fddbad33a.png)
> click reply on the top level comment, or on any reply
> you’ll see the comments form appear normally
Add `totalReplyCount` prop to TopLevelComment component, and pass it in from StudioComments. Use this new prop to check whether thread has reached limit instead of checking only the 20 we load on the first try.
Follow the repro steps described above. In the last step, instead of seeing the comments compose box appear, you should see the reply status box …
> Use reply_count to check whether reply limit is reached

- src/redux/session.js
- src/views/preview/comment/compose-comment.jsx
Previously, if you got muted while in a studio, and then stayed in the studio, the frontend would behave as if you were not muted, because the mute status was not yet in the session. This PR updates the session with the mute status when you get muted.
To test, get muted in a studio that you curate/manage/own and then try to interact with it in other ways.
This change also impacts comments on project pages, so we should double check that the behavior on project pages is the same (or better, but not worse!) For example, the behavior when you try to reply after just getting muted is slightly improved, as it no longer lets you compose.
> When a user gets muted, update mute status in the session

- src/redux/studio-mutations.js
- src/views/studio/studio-description.jsx
- src/views/studio/studio-image.jsx
- src/views/studio/studio-title.jsx
Previously, if you encountered validation error messages on the studio title, thumbnail image or description, they would be stuck on. This change makes them hide when you click outside them. The "hide" state is reset to false on each change so that they can be shown again for later errors. 
I thought it might be simpler to put this hiding behavior into the ValidationMessage component itself, but I couldn't figure out how to give it that reset behavior.
> Hide validation message on click outside 

- src/views/studio/studio.scss
When logged out, the title would not wrap long words, and could occupy arbitrarily much space vertically
before 
after
> Make the title scroll after a certain length, and long words wrap

- src/views/studio/modals/studio-report-modal.scss
- src/views/studio/studio.scss
Make thumbnails 195 * 300 and stretch to fit to match old studios.
Thumbs have a 15% black 2px border.
Transparent thumbs now have a white background.
Before:
After:
> Adjust thumbnail css

- src/redux/session.js
- src/views/preview/l10n.json
- src/views/preview/preview.scss
- src/views/preview/subactions.jsx
- src/views/preview/subactions.scss
- src/views/studio/studio-mute-edit-message.jsx
This prevents muted users from adding projects to a studio using the "Add to Studio" button on the project page. The message should show on hover.
> Muted users can’t add projects to studio via project page

- src/redux/studio-permissions.js
- src/views/studio/studio-comments.jsx
- test/unit/redux/studio-permissions.test.js
Updates comment deletion permissions for studios to match existing studio behavior.
Studio creators and managers can delete their own comments on a studio.
Updated the studio permissions test.
Tested locally including with teacher accounts.
> Studio creators and managers can delete their own comments

- src/lib/admin-requests.js
- src/redux/studio.js
- src/views/studio/l10n.json
- src/views/studio/lib/studio-activity-actions.js
- src/views/studio/lib/studio-member-actions.js
- src/views/studio/lib/studio-project-actions.js
- src/views/studio/studio-deleted.jsx
- src/views/studio/studio-info.jsx
- src/views/studio/studio.jsx
- src/views/studio/studio.scss
This PR allows admins to view studios that have been deleted.
1. Add the `withAdmin()` helper to API requests for studio info, curators, managers, projects and activity feed. This will add the `/admin` prefix to the URL and the `authentication: token` property if the user is an admin. Comments already do this. 
2. Move the `getInfo` call up from the studio info component to the top level component, and make it rerun if `isAdmin` changes. This is because we show the `oops` page if you get a 404 for studio info, which prevents StudioInfo from re-rendering on isAdmin changes. 
One thing to note: in order to get data rendered as fast as possible, the studio info request does not wait for the session to be fetched first. This means studio info will always be fetched as a normal user first, and …
> Admins can view deleted studios

- src/redux/studio-comment-actions.js
- src/views/studio/studio-comments.jsx
- src/views/studio/studio.scss
Add the ability to load a view of the studio page showing a single comment. This happens when you receive a message notifying you of someone's reply to a comment that you made on a studio. The link in the message has a comment id in the URL. The page loads only the thread containing this comment, highlights the comment, and scrolls to it. A button lets you view the full set of comments. This should match the functionality of single comment view on the project page.
> Studio single comment view

- src/redux/session.js
- src/views/preview/l10n.json
- src/views/preview/preview.scss
- src/views/preview/subactions.jsx
- src/views/preview/subactions.scss
- src/views/studio/studio-mute-edit-message.jsx
This change was previously reverted from the deploy because it sometimes crashed the project page by checking for permissions the studio in state-- that failed since we are on the project page, not the studios page.
The only difference between this and the previous PR is that it uses `selectIsMuted(state)` instead of `selectShowProjectMuteError(state)` to decide whether to prevent the user from adding projects.
> Fix preventing muted users from adding projects via project page

- src/views/studio/studio-description.jsx
- src/views/studio/studio-title.jsx
- src/views/studio/studio.scss
Per feedback from design pairing.
Before
After
> Make the border of editable fields dashed gray for studios. Otherwise, make them match the fields on project pages

- src/views/studio/studio.scss
1-across-grid is not needed since the min width is now 300.
> Adjust responsive boundaries for grid reflow

- src/routes.json
We need to switch the studios playground route to the real /studios/ route in order to do more realistic testing. We'll need to make sure we aren't accidentally stomping on any other backend route that still exists at /studios/... (I'm combing through scratchr2 now)
Since this PR is likely to be reverted after testing to unblock other deploys, just a note @BryceLTaylor if we need to unroll this from staging we'll have to manually clear out the route (reverting/re-deploying won't clear out an old route per @rschamp).
> Switch studios route to real version for testing on staging

- src/views/studio/modals/user-projects-modal.jsx
- src/views/studio/modals/user-projects-modal.scss
Styling fixes for the "add to studio" modal:
- Add loading spinner
- Improved responsive sizing: modal has same responsive height regardless of content
- Improved layout of empty state content
- Improved text color contrast on nav buttons to match studio nav buttons
- Removed extra padding below "load more" button
- Add faint gray border at top and bottom of scroll area
> Style fixes for "add to studio" modal

- src/views/studio/studio-comments.jsx
Fixes an issue where comments still showed the `reply` button in studios even if the studio owner had turned off comments. This is inconsistent with the project page and would cause some confusion (even though trying to submit a comment _does_ return an appropriate message).
> Only show reply button when comments are allowed on a studio

- src/views/studio/studio-admin-panel.jsx
- test/unit/components/studio-admin-panel.test.jsx
We were incorrectly calling the `storeAdminPanelOpen` function any time the studio page was rendered, even if the user wasn't an admin. This caused two issues:
1. Non-admin users got a value of `{adminPanelToggled_studios: 'closed'}` set in localstorage, even if they weren't an admin. Nobody really noticed this, but we shouldn't be storing things in localstorage that users don't need (even if they aren't technically "false", just unapplicable).
2. Admin users who had the admin panel open and then logged out would still see the space where the admin panel would go, because `storeAdminPanelOpen` would cause the CSS class to be applied. It wasn't checking if the admin panel should even be rendered at all.
I put in tests for both of these and fixed the issue with a one line change.
> Fix admin panel space remaining after logging out

- src/redux/comments.js
- test/unit-legacy/redux/comments-test.js
This resolves issues where things that rely on a `comment.reply_count` won't work correctly after the user has left one or more replies to a thread.
Added a couple tests for this, which also uncovered an issue where calling `addNewComment` before initializing the reply array `replies[id] = [];` would cause an error. This currently doesn't happens because we always call `setReplies()` on every top level comment, but if we stop calling setReplies, e.g. in https://github.com/LLK/scratch-www/pull/5630, replying to a top level comment that didn't have replies already wouldn't work. Glad we caught this, since it didn't come up in that PR.
> Update the reply_count when you leave a reply

- src/redux/project-comment-actions.js
- src/redux/studio-comment-actions.js
Instead of always requesting a top-level-comments replies, now that we have `reply_count` in the comment response, use that to decide whether to try loading the replies. 
For both studios and project comments.
/cc @kchadha I think we talked about this a while back, but now seems like a good time to make a bit of an optimization. 
Also /cc @picklesrus @benjiwheeler if this has any overlap with your work, but I don't think it will. 
This resolves https://github.com/LLK/scratch-www/issues/5134
> Only request replies if reply_count > 0

- src/redux/project-comment-actions.js
- src/redux/studio-comment-actions.js
Reverts LLK/scratch-www#5630 due to a bug found in the bug hunt where the single comment view only shows the top-level comment for the reply that is linked, as opposed to the reply itself.
> Revert "Only request replies if reply_count > 0"

- src/views/studio/l10n.json
- src/views/studio/studio-project-adder.jsx
Changes the placeholder text and button text for adding projects by url, to match the text in existing studios.
> Match Add Project placeholder & button text to old studios

- src/redux/project-comment-actions.js
- src/redux/studio-comment-actions.js
Revert #5660 which reverted #5630, so actually apply #5630. There was no bug with the code in this PR, it was just incompatible with our backend which was incorrectly telling the frontend that every comment loaded by id had a reply_count of 0, which caused notifications linking to project replies to not actually load the replies. 
This PR will reduce the number of requests for replies proportionally with how many comments have 0 replies, which is a win for the client side and the server side. 👑
This PR should has to be deployed _after_ the backend fix is in. 
/cc @kchadha lets keep this revert chain alive
> Reduce reply requests, for real this time I promise

- src/routes.json
Reverts LLK/scratch-www#5655, bringing back the real studio urls for more testing on staging
> Revert "Revert "Switch studios route to real version for testing on staging""

- src/views/studio/modals/user-projects-tile.jsx
- src/views/studio/studio-project-adder.jsx
Instead of showing generic "error adding project" in the studio page "add to studio" modal, use the `errorToMessageId` logic from the "add by url" component. This will let users see specific errors like rate limits, as well as rare occurrences like other users adding a project to the studio after you opened up the modal. 
I left the generic "remove" errors, because we don't have any additional info on those right now.
I also added comments and clarified the logic somewhat because i was getting confused by the booleans.
> Use errors from project adder in the add to studio modal

- src/redux/studio-permissions.js
- test/unit/redux/studio-permissions.test.js
Update the permissions for managers on studios. Only the studio creator can edit the title/description/thumbnail of the studio.
Tested locally.
CC/ @paulkaplan
> Update manager permissions for studios.

- src/views/studio/lib/studio-member-actions.js
- src/views/studio/lib/studio-project-actions.js
- src/views/studio/modals/user-projects-modal.jsx
- src/views/studio/modals/user-projects-modal.scss
- src/views/studio/studio-activity.jsx
- src/views/studio/studio-curators.jsx
- src/views/studio/studio-managers.jsx
- src/views/studio/studio-projects.jsx
- src/views/studio/studio.scss
Fixes an issue where we loaded 20 per page, but we are showing rows of 3, so even when there was more to load the row would appear incomplete. I changed the max load to 24, so it will be divisible into 1,2,3 (or even 4). Aren't twelves grand?
Also change the markup/css to make the load more buttons full width, per design spec
> Load full rows for projects, curators, managers

- src/lib/configure-store.js
- src/lib/render.jsx
- src/views/studio/lib/studio-activity-actions.js
- src/views/studio/lib/studio-member-actions.js
- src/views/studio/lib/studio-project-actions.js
- src/views/studio/studio-redux.js
- src/views/studio/studio.jsx
- test/unit/redux/project-comment-actions.test.js
- test/unit/redux/studio-activity-actions.test.js
- test/unit/redux/studio-comment-actions.test.js
- test/unit/redux/studio-member-actions.test.js
- test/unit/redux/studio-project-actions.test.js
This PR attempts to construct an example of how to test the complex async action creators that we use with redux-thunk. These often involve API requests (often multiple) and dispatching events to the redux store. 
The first couple commits just move out some code for use in test helpers. Instead of using redux-mock-store, I thought it would be a better approach to use the actual redux store that we use on the studio view. One big reason for this is that it allows us to use the redux selectors to interrogate the resulting store state after calling the actions, as opposed to looking at the actions sent to the store or the trying to look at the store directly. I think this is good because it allows us to exercise the redux store in the same way in the tests as we use it in the view, only …
> Create detailed unit tests for studio-member-actions

- test/integration/my-stuff.test.js
Ensures that the integration tests don't run into the rate limit for studio creation when run in CI.
adds a check to the test that creates a studio from the my-stuff page.
> check rate limit for studio creation integration test

- test/unit/redux/studio-permissions.test.js
@seotts fixed that issue where certain "creator" tests were failing mysteriously. There was a test that mutated global fixture data, causing future tests to fail. Instead of mutating, I made it make a copy and modify that using object spread syntax.
This uncovered a test that was incorrectly passing, that stated that creators couldn't add curators, which isn't true. Fixed that.
> test(studios): fix failing permissions tests for studios

- bin/tx-push-www
1. rename the resource on transifex: `conference-2021-index-l10njson` to `conference-index-2021-l10njson` so that we don't lose any current translations.
2. merge the PR. Nightly update-translations job will execute the script.
3. rename or remove [conference-2021-index-l10njson](https://github.com/LLK/scratch-l10n/tree/master/www/scratch-website.conference-2021-index-l10njson) in scratch-l10n.
Fixes #5912  : handling of the conference 2021 translation updates.
The conference views do not follow the conventions for naming the route based on the view. Translation files need to match the route, so they have to be overridden in the `tx-push-www` script. When we changed the 2020 conference view to 2021 we forgot about updating the script, so the resource in transifex doesn't match the route …
> Fix tx-push script for conference 2021 page

- src/views/studio/l10n.json
- src/views/studio/studio-activity.jsx
This adds record of studio transfer to the activity feed, with two slightly different messages depending on whether it was done by an admin or the former host.
This should be fine to merge at any time, including before launch of the feature. (If there are no becomehoststudio notifications, they will not be displayed.)
> Add studio host transfer notification to the activity feed

- src/views/studio/modals/studio-report-modal.scss
https://github.com/LLK/scratch-www/issues/5710
It's been 10 days since the last comment lol
Adds `white-space: pre-wrap;` to the text boxes in the studio report modal
Before
After
> Add line breaks to description

- src/components/alert/alert-provider.jsx
Increase the default amount of time that alerts for success and errors are shown, from 3 to 6 seconds. Currently all alerts use this default time. The aim is to help ensure that people have enough time to read the alert message before it disappears.
> Increase default alert duration to 6 seconds

- src/views/studio/lib/studio-member-actions.js
- src/views/studio/modals/transfer-host-confirmation.jsx
- src/views/studio/modals/transfer-host-modal.scss
- src/views/studio/modals/transfer-host-selection.jsx
- src/views/studio/studio-managers.jsx
- Responsive style for password validation alert
- Responsive style for transfer outcome tiles (on the confirmation step)
- Reload the manager list before closing the modal, so you immediately see the new host shown first
- Fix load more buttons
> More transfer host modal fixes

- src/views/credits/credits.jsx
Changes: 
- Add "Nasir Khan Saikat (বাংলা)" as a language organizer for Bengali (added to the Credits page)
- sort the language organizers by first name:
- Brenda
- Farshid
- Hans
- Karin
- Nasir
Fixes issue: https://github.com/LLK/scratch-www/issues/5957
> Added Nasir and reordered lang organizers alphabetically by first name

- src/views/studio/l10n.json
Changes the error message for when a studio has been transferred too recently, to reflect that the limit is _per studio_ not _per user_.
> Change copy of transfer rate-limit error

- bin/configure-fastly.js
This should eliminate the issue where querystrings would cause URLs to skip S3 and fall back to scratchr2.  I opted to update every relevant instance of `req.url` -> `req.url.path`, but not all of them are strictly necessary. It should just help set a pattern to follow.
> Ignore querystrings when matching routes

- src/redux/studio-permissions.js
- src/redux/studio.js
- src/views/studio/lib/studio-member-actions.js
- src/views/studio/modals/transfer-host-confirmation.jsx
- src/views/studio/modals/transfer-host-selection.jsx
- src/views/studio/studio-member-tile.jsx
- test/helpers/state-fixtures.json
- test/unit/redux/studio-member-actions.test.js
- test/unit/redux/studio-permissions.test.js
This switches over to using "host" (instead of "owner") terminology in the redux state for studio. It also allows www to accept a field called "host" from api. It falls back on "owner," so this can be merged anytime before the change is made in [api](https://github.com/LLK/scratch-api/pull/1669).
There should be no changes to functionality as a result of this change.
> Use studio "host" in state, and accept "host" from api

- .github/workflows/main.yml
Update the PR titles created by the github action that creates the release branch and makes PRs against develop and master. Use [Develop] and [Master] so that these PR titles are easier to differentiate from the others in the list.
> Update the PR Title in the PRs created by the github action

- src/redux/studio-permissions.js
- test/unit/redux/studio-permissions.test.js
This gives admins permission to promote curators to managers, even if they are not a manager. This is a feature request by the community team.
To be consistent with other permissions, admins do not have permission to do this if they happen to be muted.
I modified the test of this permission.
In bughunt, we should test that admins can promote curators (including themselves.) Other non-admin, non-managers should not be able to promote curators.
> Allow admins to promote curators to managers

- .github/workflows/main.yml
Add --no-ff flag to `git merge` line in the release branch creation workflow. This should ensure that we're always creating a merge commit on the release branch when pulling in changes from develop to stage for the release.
> Update Release Workflow

- src/views/studio/studio-member-tile.jsx
The logic that decides whether to show "Studio Host" on the host's tile was looking for "owner." I changed it to host.
> Show "Studio Host" on manager tile

- src/components/navigation/www/navigation.jsx
Resolves: #5487
When the search form is submitted, don't redirect when the `q` field is an empty string. This prevents clicking the icon/pressing enter from redirecting to the blank results page.
- Pressing the icon with something in the field correctly searches for the item
- Pressing enter with something in the field correctly searches for the item
- Pressing the icon with an empty query field does not do anything
- Pressing enter with an empty query field does not do anything
> Prevent searches for empty strings

- src/components/text-and-media-snippet/text-and-media-snippet.jsx
- src/components/video-preview/video-preview.jsx
- src/views/annual-report/2020/annual-report.jsx
- src/views/annual-report/2020/annual-report.scss
Fix video disappearing after fullscreen is entered and exited
Fix tweet alignment on ios
Sets a width on the parent container so that the video (which has `videoFoam=true` property) will not disappear after entering and exiting fullscreen.
> Annual Report Fixes

- test/integration/comments.test.js
Adds a partial integration test for leaving a reply to a profile comment.  It leaves the comment but does not check to see if the comment appears.  There was some trouble with finding the comment by xpath that I could not resolve, so it seemed better to have a partial test than no test.
> Add a partial profile reply integration test

- .circleci/config.yml
The Jest integration tests were not being run on Circle because they were trying to run the old npm script.
Uses the correct npm script: test:integration:remote.  test:integration:jest:remote is no longer valid
This should allow the Jest integration tests to run
> CircleCI use correct integration test command

- package-lock.json
- package.json
- test/integration/comments.test.js
- test/integration/my-stuff.test.js
- test/integration/project-page.test.js
- test/integration/selenium-helpers.js
- test/integration/sign-in-and-out.test.js
- test/integration/studios-page.test.js
The Integration Tests that check comments were failing sometimes.  
Makes a number of adjustments to the Integration Tests to try to improve their stability locally and in CI.
* Updates Chromedriver
* Updates the Helper SignIn function to use sendKeys(ENTER) rather than clicking the post button.  This more reliably waits until the username and password have been typed before submitting the form.
* The SignIn function is called slightly differently, so changes were made to those calls.
* Changes how several of the other tests sign in to use the Helper SignIn function
* Sign in with the enter key in tests that don't use the Helper SignIn function
* Use WaitUntilVisible Helper function in several places rather than just checking once if an element is visible (Project Page and sign-in-and-out …
> Fix flaky comments tests

- package-lock.json
- package.json
- test/integration/join.test.js
There is a new version of Selenium-Webdriver that we haven't updated to yet.
Also, the Join integration tests were failing sometimes.
Updates Selenium-Webdriver to version 4.1.0
Adds an await to the BeforeEach() function in the Join tests.  It was hard to see the effects of the Selenium update when the tests failed.
Integration tests pass with the new version fo Selenium-Webdriver.
> Update selenium webdriver

- src/views/studio/studio-activity.jsx
Fixes https://github.com/LLK/scratch-www/issues/6367
https://github.com/LLK/scratch-www/issues/6367
Corrected username for profile link in studio host transfer log entry.
To test:
1. Open https://scratch.mit.edu/mystuff/
2. Create studio
> I created a bookmarklet to automate this.
> ```javascript
> javascript:if(window.location.href=="https://scratch.mit.edu/mystuff/") {document.getElementById("new_studio").children[1].click();}
> ```
3. Invite user to new studio
4. Promote user to manager
5. Give user `host` privileges
6. Observe (authentication is not required) the `href` of the user profile links on the `/activity` endpoint of the studio. If the usernames correspond to the link destinations, this PR works.
> Correct link href for studio host transfer message

- .circleci/config.yml
build jobs were storing artifacts and caches when running on PRs, wasting resources.
Makes a new version of the build job, build_pr, that will be run on PRs only.
Stops running the old build job on PRs.
> circleci add build_pr job that runs on prs, old build doesn't run on prs

- .circleci/config.yml
Builds have been failing because we've run out of RAM in Circle
Upgrades to the Large resource_class for the build job
> use large resource_class in CircleCI build job

- src/redux/studio-comment-actions.js
Resolves #5989 
Adjust the studio reply comment load batch size to 25 instead of 20.
Searched for test cases that interact directly with this value, didn't find any.
> fix(gh-5989): adjust comment load batch size

- src/redux/comments.js
- src/redux/project-comment-actions.js
- test/unit-legacy/redux/comments-test.js
Resolves an issue with a regression introduced by #6311 where older studio comment threads with more than 25 replies did not have a "See more replies" button so users could not fetch more comments in the thread.
This change is a forward fix which introduces an update to project comment threads as well. Project comment threads now also fetch 25 replies at a time to match studio comment threads.
Both types of comments display a "See more replies" button after loading batches of 25 replies at a time.
Updated the comments redux test for when the moreRepliesToLoad flag is true.
> [Hotfix][Master] Fix issue with "see more replies" button on old studio comment threads with > 25 replies

- src/components/forms/radio-group.jsx
- src/components/registration/steps.jsx
- src/components/registration/steps.scss
Resolves #3589
Adds CSS to set the font weight of labels with help text and the "Gender" label to 500 to match the weight of other labels in the teacher registration form.
All labels have the same weight after this change:
> Use font weight bold consistently for teacher registration form labels

- webpack.config.js
We were running out of memory on Circle CI builds which caused the build to fail.
This PR decreases the parallelism used for running the minifiers to 4 rather than the default. Webpack default uses TerserPlugin, which is what we will continue to do, but in order to not use the default setting we have to add it specifically.
> webpack config make limit TerserPlugin to parallel: 4

- .circleci/config.yml
We're using too much storage in circleci.
Moves the run steps into aliases so they can be easily called in multiple steps
Removes all caching, which leads to high storage usage
Make a new alias called Build_and_deploy which combines the existing build, deploy, and integration jobs
Replace the existing jobs needed for deploys with only build-and-deploy-staging and build-and-deploy-production
> circle remove having separate jobs and caching

- package-lock.json
- package.json
- src/_colors.scss
- src/_frameless.scss
- src/components/card/card.scss
- src/components/carousel/carousel.scss
- src/components/dropdown-banner/banner.scss
- src/components/dropdown/dropdown.scss
- src/components/extension-landing/extension-landing.scss
- src/components/forms/validation-message.scss
- src/components/info-button/info-button.scss
- src/components/modal/base/modal.scss
- src/components/navigation/conference/2019/navigation.scss
- src/components/tooltip/tooltip.scss
- src/views/annual-report/2020/annual-report.scss
- src/views/developers/developers.scss
- src/views/download/download.scss
- src/views/parents/parents.scss
- src/views/studio/modals/studio-report-modal.scss
- src/views/studio/modals/user-projects-modal.scss
- src/views/teachers/landing/landing.scss
node-sass has been deprecated, so updating it any further will require us to switch to using sass (dart-sass)
Replaces node-sass with sass (dart-sass)
updates the 2019 conference page's .scss file which had invalid sass
Update many .scss files to fix deprecated syntax.  hsl and hsla now require a % for the saturation and lightness values.  Division is now handled with the function math.div() rather than a slash. 
This removes many deprecation warnings
> Replace node sass

- package-lock.json
- package.json
Updates sass-loader to ~~version 7.0.3.~~ (see comment blow)  
Higher versions (starting with 7.3.1) fail with node-sass version 7.0.1 but succeed with version 4.14.1.  This should be addressed in a followup PR, especially since node-sass has been replaced with sass (formerly dart-sass).
> update sass-loader to version 10.2.1

- package-lock.json
- package.json
- webpack.config.js
Update postcss-loader to version 4.2.0 (more recent versions require webpack 5)
Requires an update to the webpack config
Now plugins needs to be nested inside an object called postcssOptions
> update postcss-loader to 4.2.0

- package-lock.json
- package.json
Webpack related dependencies are out of date.
Warnings appear when running `npm run start`
Updates webpack-dev-middleware to 4.0.4 (latest version)
Update bunyan to 1.8.15 (latest version)
This change causes warnings to go away when running "npm run start"
These had to be updated together otherwise errors appear
> Update webpack-dev-middleware and bunyan

- package-lock.json
- package.json
- webpack.config.js
10.4.2 is the most recent version
To update past version 9.6.0 the broser list needs to be passed in through the package.json rather than as an argument in the webpack.config.
> Update Autoprefixer to 10.4.2

- src/components/forms/select.scss
fixes styling of dropdown buttons which looked 3d.
adds `-webkit-appearance: none;`
> Fixes styling of dropdown menu buttons for safari

- src/views/preview/comment/compose-comment.jsx
Resolves #2668
Adds `autoFocus` to the textarea for replying to a comment.
Tested manually by clicking "reply" on comments on a project and in a studio. I was able to start typing a reply immediately after clicking the button.
> Focus comment reply textarea when it appears

- src/views/preview/preview.scss
Resolves #4151
Makes project instructions and Notes and Credits always left-aligned on 768px viewport or wider.
Tested on different window widths.
> Left-align project instructions and notes on medium window widths

- src/l10n.json
Fixes #4969
Adds missing period to the end of the `comment.unconstructive.header` string.
No tests changed or performed, since it's just a l10n string edit.
> fix(gh-4969): add missing period to l10n string

- package-lock.json
- package.json
- webpack.config.js
Updates dependencies
Updates copy-webpack-plugin to version 6.4.1.  Higher versions require Webpack 5.
Updates the webpack config to use the new pattern
> Update copy-webpack-plugin to version 6.4.1

- package-lock.json
- package.json
packages are out of date
updates webpack-bundle-analyzer to version 4.5.0 (the latest version.)
Adds a script to the package.json to easily run the analyzer
> update webpack-bundle-analyzer and add build:analyze script

- src/components/forms/select.scss
also caret-hover.svg
The caret on the language selector in the footer was not showing up.  
Updates the urls provided to the url() function in select.scss to the correct format.
Changes it for caret.svg and caret-hover.svg
Checked on Chrome and Safari
> Fix format of url of caret.svg in language selector

- src/views/conference/2022/index/index.jsx
- src/views/conference/2022/index/l10n.json
- Fixes inconsistent date on 2022 conference page.
- Add conference time.
- Fix padding around "stay tuned" sentence
> Update date and time for conference and padding around 'stay tuned'

- src/components/ttt-tile/ttt-tile.scss
Fixes #6002 
Update styling the TTTTile object to make the cursor a pointer on hover of the TTTTile image.
Tried getting the local environment working, but there were some errors. 
I did test manually adding the css attribute to the `ttt-tile-image` class using inspect element, and everything seemed to be working.
> fix(gh-6002): fix cursor for ideas tile images

- src/components/grid/grid.scss
Resolves #4823
Makes project author usernames on Explore and in search results always left-aligned when the viewport width is below 942px.
Tested on different widths on Explore and search pages.
> Make author username alignment consistent on Explore and search

- src/views/annual-report/2020/people.json
- src/views/credits/people.json
- Update the team members on the credits page. There should be 66 people in total.
- I also fixed a typo I noticed in a team member's name on the 2020 annual report page.
Tested locally that the some of the links open up to the correct profiles.
> Update credits page

- .circleci/config.yml
we're setting up dockerhub credentials in each repository.
resolves a warning that we are not supplying dockerhub credentials to the build-test-no-deploy workflow
Uses the dockerhub-credentials context that is used across repos, making it easier to maintain.  Now there will be only one place to update them.
Use dockerhub credentials in the build-test-no-deploy workflow as well
> circleci use dockerhub-credentials context

- src/components/commenting-status/commenting-status.scss
- src/views/preview/comment/comment.scss
- src/views/studio/studio-comments.jsx
- src/views/studio/studio.scss
Resolves #5889
Makes changes to CSS to make the padding above and below the comment compose box always exactly 32px.
Tested on project and studio pages by checking the padding values using Inspect.
> Correct comment compose spacing

- src/views/splash/l10n.json
Actual banner changes to use these messages coming in a later PR. This is just so the messages can get translated.
Here's how it'll looks ![image](https://user-images.githubusercontent.com/15675877/165172138-5f680deb-2cd5-46e3-be6d-d73bbfaca375.png)
> Add messages for scratch week banner so they can be translated. 

- src/views/splash/donate/donate-banner.jsx
- src/views/splash/donate/donate-banner.scss
- test/unit/components/donate-banner.test.jsx
Switches the banner text to mention Scratch celebration and puts back the regular one after Scratch week is over
.
> Update donate banner for Scratch celebration.

- src/routes.json
- src/template.ejs
The /annual-report route uses the same view as the current annual report (so right now, /annual-report/2020) but is not configured to use that intl.js file, so if you visit the page from the /annual-report url it is not translated.
- `src/template.ejs` now looks for an optional `intlName` route attribute
- The annual-report route now has that attribute that points to 'annual-report-2020' (when new report launched, will change it to 'annual-report-2021')
Note: There are other routes that have fixes for similar problems that take place in other parts of the scripts, such as [here](https://github.com/LLK/scratch-www/blob/develop/bin/build-locales#L134). I'm going to make a backlog ticket for standardizing using routes.json as the source of truth for localization file names in www.
In …
> Make /annual-report use localization file of 2020 report

- src/routes.json
This changes /annual-report to use the 2021 view and intl file instead of the 2020 ones. 
We are planning to launch the Annual Report in the regular deploy cycle this week. If we have decide to not launch it (because of a blocking bug, for example) we will need to revert the merge of this PR.
In bughunt, we should test:
- /annual-report shows the 2021 report
- /annual-report/2021 shows the 2021 report
- /annual-report/2020 shows the 2020 report
- /annual-report/2021 and /annual-report are equally translated
> Switch /annual-report to 2021 report!

- src/views/about/about.jsx
Fixes #6316 
- if a link is a) external, or b) embedded within a paragraph, make the link open in a new tab
Tested on local build, Chrome on MacOS.
> fix(gh-6316): make links open in new tabs

- src/views/annual-report/2020/l10n.json
Fixes #6377 
Fixes the typos as per the comments in the issue.
- `wiht` -> `with`
- `th` -> `the`
Didn't conduct any testing, but it's also only a l10n file edit.
> fix(gh-6377): fix typos in alt text

- test/unit/components/donate-banner.test.jsx
It worked before because the actual date was before may 22.
> Actually set the date in one of the tests. 

- src/views/annual-report/2021/l10n.json
The copy for the Creative Expression value was a duplicate of the one for Equitable Opportunities. I fixed it to the copy on the content doc.
> Fix “Creative Expression” description copy in annual report

- src/components/grid/grid.scss
Resolves #4822
Adds `overflow: hidden` to avatars on Explore and search.
Tested by manually setting an invalid URL.
> Fix Explore/search tile overflow when avatars don't load

- package-lock.json
- package.json
Update `scratch-gui` directly instead of waiting for Renovate.
> chore(deps):update dependency scratch-gui to 0.1.0-prerelease.20220706173215

- src/views/parents/parents.jsx
Resolves #6933 
* Replaces outdated CleanSpeak url with a link to https://cleanspeak.com/products/profanity-filter
> fix: use correct CleanSpeak product url

- src/views/faq/l10n.json
Resolves #3454
Removes reference to Echo sound editor effect from the FAQ.
> CE-141 Remove reference to Echo sound editor effect

- src/views/annual-report/2020/annual-report.jsx
Resolves #6305
Replaces `u/` prefixes with `@` in the 2020 Annual Report to be consistent with the rest of the website.
Tested manually.
> CE-178 Use correct username prefix in 2020 Annual Report

- src/views/preview/l10n.json
Resolves #6030
Changes the message shown on projects if comments are disabled to be more similar to the studio page message.
Tested manually by opening a project with comments disabled.
> CE-177 Change "commenting is off" message for projects

- test/integration/join.test.js
IBE-401
Fixes a failing integration test that was formerly dependent on Cleanspeak bad word list
Ran all the join flow integration tests locally.
> Change username test to something actually rejected

- package-lock.json
- package.json
Updated scratch-gui version for www release to `0.1.0-prerelease.20220914163646`.
N/A
> build: Updated scratch-gui version for www release

- src/components/join-flow/username-step.jsx
- src/lib/validate.js
- test/unit/lib/validate.test.js
Compliments the ability of the frontend check on username validity with a check on password weakness. This requires the deployment of changes to scratch-api before this change is deployed.
> Add check on password complexity by using a backend call

- src/views/studentregistration/student-registration-meta.jsx
- src/views/studentregistration/studentregistration.jsx
https://scratchfoundation.atlassian.net/browse/CE-207 (private link; "Add meta noindex tag to student registration page")
Adds meta robots noindex tag to student registration page's <head> section
This should cause any search engine crawlers who encounter these pages to be aware that we do not wish these pages to be indexed.
example of additional tags within <head>:
The meta "description" and "og:description" tags have already been provided elsewhere, so the page ends up with two of each; one whose content reads simply "Scratch is a free programming language and online community where you can create your own interactive stories, games, and animations.", and now this new set, whose content reads "Scratch registration page for a particular class". I thought it was better to include this new …
> CE-207 add meta tags to student signup page to prevent search indexing

- .circleci/config.yml
private Jira ticket: https://scratchfoundation.atlassian.net/browse/CE-211
separates integration tests into a separate job within deploy workflow.
as of the initial version of this change, I'm not sure of a few things:
* this code will currently not automatically run integration tests as part of the deploy steps. But we probably want to put those back in, so that integration tests run as part of the deploy. What I'm wondering is, is it better to have separate build/deploy and integration test jobs, which run in sequence? Or is it better to just put the integration tests back into the deploy jobs?
* I'm not totally clear on when to store test results, and when not to. In the deploy steps, we have linting and unit tests; should we attempt to store test results at the end of the deploy …
> CE-211 separate integration tests into separate job within deploy workflow

- .circleci/config.yml
Changes circleci configuration to make integration test jobs wait for deploy jobs before running.
Follow-up to https://github.com/LLK/scratch-www/pull/7088 , which left the integration test jobs running in parallel with deploy jobs, which defeats the purpose!
> Make integration tests sequential

- src/components/box/box.jsx
Unlabeled and unfocusable header elements should not be present. The box component accepts a prop for the text inside of the h5 element. However, no attribute is passed to the box component for the h5 element in the source code. I added a conditional that checks for the prop and renders the h5 element if a prop exists but does not render the h5 element if the prop does not exist. Resolves #7176.
I passed a prop to the box component for the h5 element and the h5 element rendered with the text from the prop.
I did not pass a prop to the box component for the h5 element and the h5 element did not render
After making the changes, I ran `npm test` and found that nothing was broken
> Fix gh-7176: Fix empty h5 elements in the homepage

- src/components/languagechooser/languagechooser.jsx
- src/l10n.json
AT users will have a difficult time figuring out what the select element in the footer is for because there is no proper aria label for it. Resolves #7173.
I added an arial-label attribute to the element that gives context for what the element is for to AT users. The screen reader announces the aria-label attribute.
> Fix gh-7173: The select element in the footer needs proper aria labeling

- src/components/extension-landing/extension-landing.scss
- src/views/ev3/ev3.jsx
Fixed the title's overlapping issue that was happening on Firefox, this fixes issue [#6423.](https://github.com/LLK/scratch-www/issues/6423) 
I tried changing this issue before, but I was working on the wrong branch. I tried to undo those commits, but I wasn't able to delete them from the issue's history. Sorry for all the confusion! 
I also added some text to one of the images, since I've seen a lot of issues regarding accessibility.
> CE-310 Fixes title overlap of EV3 for Firefox 

- src/views/preview/stats.scss
follow-on to https://github.com/LLK/scratch-www/pull/7264
sets opacity of the new project page stats icons to default of 100% (instead of 50%), to match the intention behind their design.
> Make project stats icons always opaque

- src/components/extension-landing/extension-landing.scss
- src/views/boost/boost.jsx
- src/views/download/scratch-link/download.jsx
- src/views/ev3/ev3.jsx
- src/views/ev3/ev3.scss
- src/views/gdxfor/gdxfor.jsx
- src/views/microbit/microbit.jsx
- src/views/microbit/microbit.scss
- src/views/wedo2/wedo2.jsx
Follow on to https://github.com/LLK/scratch-www/pull/7291
Maintains #7291's original fix: here is production now on firefox,
and here is the page with this fix:
But this change additionally addresses a problem that #7291 did not address, which left this page:
WIth this change, that page looks like:
* ensures the classname "headline-icon" is present on all headline icon images on the pages:
* /boost
* /download/scratch-link
* /ev3
* /microbit
* /vernier
* /wedo
To test manually, open each of the above pages in both local (or staging) and in production. They should appear the same in Chrome and Safari. In Firefox, you should see improvement on the /ev3 page, and everything else should appear the same.
_styling issue, not directly testable with automated tests_
> Make extension landing page title icon class constant

- src/_colors.scss
- src/views/explore/explore.scss
Partially addresses #7182. Scratch product & design are currently thinking through further changes to the color palette to reach compliance.  
These changes affect the splash section on the `/splash` page and the tabs on the `/explore` to make them WCAG 2.1 AA compliant. Specifically, the aqua colors are darkened and darker text with outlines are used around grey button-like UI elements. See screenshots for previews of the changes:
No tests changes and all automated tests currently pass.
> CE-297: Update aqua and gray colors

- src/lib/render.jsx
- test/helpers/intl-helpers.jsx
- Fixes [ENA-205](https://scratchfoundation.atlassian.net/browse/ENA-205)
Part of the `react-intl` upgrade includes the following:
> Change default textComponent in IntlProvider to React.Fragment. In order to keep the old behavior, you can explicitly set textComponent to span.
This broke some [integration tests](https://app.circleci.com/pipelines/github/LLK/scratch-www/10855/workflows/7f6b8f52-d6b4-474c-b749-00bfdc494e67/jobs/13439) that were specifically targeting the `<span>`. Used the `textComponent` property to restore original behavior. This should also ensure any css that was depending on the spans also works.
Unit tests still pass.
[ENA-205]: https://scratchfoundation.atlassian.net/browse/ENA-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> fix: use span for localized messages

- test/integration/footer-links.test.js
- test/integration/selenium-helpers.js
- Investigated while working on [ENA-263](https://scratchfoundation.atlassian.net/browse/ENA-263)
- Use a different `selenium-webdriver` page loading strategy so that we don't have to wait for the page to completely load. There are a couple of pages that navigate to the About page. The TED talk iframe is taking a long time to load. (This may be going away soon because of the cookies it uses.) It is then causing some following tests to fail.
- Wait for the landing page to load for the `footer-links.test.js`. Not sure if this is happening in CircleCI, but locally I am seeing periodic failures of these tests. The test attempts to click on a link and nothing (no error) happens. Not completely sure, but my theory is the page is reflowing right when the click is attempted and it misses. Added a …
> test: change page load strategy to improve integration tests

- src/components/privacy-banner/privacy-banner.jsx
- src/components/privacy-banner/privacy-banner.scss
- Fixes an issue where the privacy policy link did not work in Chrome.
- Adds `position: sticky` to the `aside` element containing the banner to prevent the margin of the main page `div` from blocking the link.
> hotfix: make banner aside use sticky position

- src/components/privacy-banner/privacy-banner.jsx
The scratchpolicyseen cookie is supposed to expire after 3 weeks, but due to a typo in the expiry time, it doesn't have a valid expiry, and falls back to expiring in Session. This has led to a lot of complaints by people about closing the popup but seeing it again later. This fixes that problem
> Fix cookie expiring in session

- src/template-config.js
- src/template.ejs
Related to ENA-317
- Document all GA/GTM-related variables in `template-config.js`
- Add `gtm_env_auth` variable (from `GTM_ENV_AUTH` environment variable) to enable alternative GTM environments
This will let us test new versions of our production GTM configurations in staging without sending the data to our production data stream.
`GTM_ENV_AUTH` should be blank for production (the default environment). I've already set the correct value in the CI context for staging.
Because `GTM_ENV_AUTH` is blank for production, this should not affect production other than a harmless `+''` in the GTM script snippet.
This can't be tested until it's deployed to staging since the GTM config depends on the hostname. Deploying to staging should wait until after the current release window.
> build: enable GTM environments feature

- src/views/about/about.jsx
The annual report link on the about page pointed to a previous year's annual report, instead of the [current report ](https://www.scratchfoundation.org/annualreport) on the Scratch Foundation website. This PR changes the link URL to point to the correct page.
- REQ-56
- Updates link URL
> REQ-56: update annual report link

- webpack.config.js
Fixes placement of the micro:bit HEX file for the new in-editor micro:bit update feature.
Also eliminates unnecessary instances of `CopyWebpackPlugin`. One instance of the plugin can handle many patterns, so there's no need to create separate instances like we were doing.
Tested locally:
1. `npm start`
2. visit `http://localhost:8333/static/30d09ba32a17082ef820b57d52d60b7b.hex`
3. visit `http://localhost:8333/projects/editor/` and use the micro:bit update feature (requires a WebUSB-enabled browser)
I also compared the `/build` output before and after consolidating the `CopyWebpackPlugin` instances to make sure I wasn't missing some hidden reason to separate them.
> Fix microbit hex

- src/views/about/about.jsx
issue in bug hunt
fixes link to incorrect annual report on about page
> fix: add link to annual report in correct place

- README.md
- src/components/join-flow/join-flow.jsx
- src/template-config.js
- src/template.ejs
- src/views/splash/donate/donate-banner.jsx
- test/unit/components/join-flow.test.jsx
Part of ENA-317
- Remove references to previous UA/GA
- Update join flow event reporting to use GA4 through GTM
- Update donation banner button click event to use GA4 through GTM
Those were the only two places where we were using analytics in this codebase.
Tested locally by running through GTM's Tag Assistant. This is how I found out that my initial approach wouldn't work. Since GTM supports automatic click reporting, including outbound links, I initially intended to remove the hook from the donate button (use `onClick=navigateToDonatePage` instead). It turns out that it doesn't work in this case, which I discovered through testing. It's probably my mistake somehow, but I decided to back off and keep the structure that's been working so far.
> chore: replace UA with GA4 through GTM

- package-lock.json
- package.json
Resolves ENA-343
Update `scratch-gui` dependency to a fixed version
Tested locally on Chrome, Firefox, and Edge on Windows 11.
Manually tested by QA through BrowserStack.
> fix: pull in scratch-gui fix for ENA-343

- src/components/extension-landing/extension-troubleshooting.jsx
- src/components/extension-landing/install-scratch-link.jsx
- src/l10n.json
- src/views/boost/boost.jsx
- src/views/download/scratch-link/download.jsx
- src/views/ev3/ev3.jsx
- src/views/gdxfor/gdxfor.jsx
- src/views/microbit/microbit.jsx
- src/views/wedo2/wedo2.jsx
ENA-348
- Move "If [Scratch Link] does not appear" advice from the installation steps (`install-scratch-link.jsx`) down into the troubleshooting section (`extension-troubleshooting.jsx`).
- Add a `currentOS` property to the `ExtensionTroubleshooting` component, since this info is the first OS-specific content in that component.
- Now that `ExtensionTroubleshooting` has a `currentOS` property, it can make the browser compatibility item show only for platforms which connect to Scratch Link from a browser.
Tested locally with multiple browsers on Windows 11.
> fix: move the 'if Scratch Link is not running' advice into the Troubleshooting section

- test/integration/footer-links.test.js
- test/integration/project-page.test.js
- test/integration/search.test.js
- test/integration/selenium-helpers.js
Makes `scratch-www` integration tests reliable.
- Resolves #3038 and #3324 (or maybe those issues are already stale)
- Add `SeleniumHelperError` and a filter on `Error.prepareStackTrace` to improve debug info associated with test failures
- Adjust timeouts and messages for consistency throughout `SeleniumHelper` methods
- Fix a variety of specific problems with existing tests (I'll add inline comments on the PR)
I tested these changes by temporarily telling CI to run integration tests without deploying. For example:
https://app.circleci.com/pipelines/github/scratchfoundation/scratch-www/12490/workflows/2a2a2dde-63ce-4f00-84c3-43025afa06c6/jobs/15681
> Fix tests and improve test debugging

- README.md
- src/redux/preview.js
- webpack.config.js
Add configurable Thumbnail endpoint host and URI.
N/A
> feat: Replace hardcoded thumbnail URI and host with configurable ones

- src/routes.json
Temporarily reset `routes.json` to the state it was in before any redirects related to our new website.
This should give us some breathing room to implement and test a proper fix tomorrow/later.
> fix: temporarily revert all routing changes for the new site

- webpack.config.js
ENG-458 Extension Badges failing to appear on project pages
Fix the incorrect `Buffer` polyfill configuration in `webpack.config.js`. This polyfill is required because webpack 5 no longer automatically polyfills all the things that webpack 4 did in the past.
See also: <https://viglucci.io/articles/how-to-polyfill-buffer-with-webpack-5>
The incorrect `Buffer` polyfill was roughly equivalent to no `Buffer` polyfill, leading to this error, which you can see in your browser console by visiting any project page in production right now:
```text
www Unhandled project parsing error: ReferenceError: Buffer is not defined
```
That error was coming from the code that parses the project information to create those badges. Honestly, I was a little surprised that a) this was so easy to track down, and …
> Fix project badges by correcting Buffer polyfill

- webpack.config.js
For some reason, the build output is looking for extension images and tutorial images in `js/static/...`. Until we figure out how to fix that, this change will put the files in that location.
> fix: make sure scratch-gui images are where the JS is looking

- .github/workflows/tx-push.yml
- bin/tx-push-www
- Add a new GHA workflow to run the `i18:push` npm script
- Fix (remove) the path to `tx-push-src` in the `tx-push-www` script
The new workflow is triggered on push to `develop`, `master`, and release branches. Back when we used Travis, we had it set up on an interval. I think this approach will still push any time we need it, but probably still less often than our Travis approach.
> ci: add job to push Transifex strings

- src/components/welcome/welcome.jsx
- src/views/splash/presentation.jsx
- src/views/splash/splash.jsx
Display guide to users when they select the "Learn how to make a project" button from the welcome screen if the user is eligible to view the guides
> fix: display guide from learn how to make project button

- src/components/intro/intro.jsx
- src/components/intro/intro.scss
- src/components/video/video.jsx
**Jira ticket:**
[UEPR-118](https://scratchfoundation.atlassian.net/jira/software/c/projects/UEPR/boards/92?selectedIssue=UEPR-118)
[UEPR-118]: https://scratchfoundation.atlassian.net/browse/UEPR-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug: [UEPR-118] Player sound playback

- src/views/parents/parents.jsx
There's a new version of the "What is Scratch?" video. This change updates the ID used to embed that video at the top of the "For Parents" page.
I pulled the video ID out into a variable and added a comment with search terms so that it's easier to find (if there is a) next time.
> fix: update "For Parents" video ID

- src/components/helpwidget/helpwidget.jsx
**Ticket:**
[UEPR-105](https://scratchfoundation.atlassian.net/jira/software/c/projects/UEPR/boards/92?selectedIssue=UEPR-105)
**Changes:**
Removed the code that hides the inappropriate report link in widget on Contact us page
[UEPR-105]: https://scratchfoundation.atlassian.net/browse/UEPR-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [UEPR-115] Show inappropriate link in freshdesk widget on contact us page

- .github/workflows/ci-cd.yml
Resolves the current build failure preventing both staging and production deploys.
Before:
* If we plan to deploy,
1. Install a version of `pip` that is compatible with Python 3.5, then
2. Use `pip` to install `s3cmd==2.3.0`
After:
1. Use `actions/setup-python` to ensure availability of a version of Python that is compatible with v3.5, then
2. Use `pip` to install `s3cmd==2.3.0`
Since these commands are relatively quick, I moved them earlier in the workflow. Also, while they're only necessary in the case of a deploy, running them even when not deploying means that if a PR breaks them, we'll know about it before we try to deploy.
Tested by manually running the GHA workflow on the branch. See also the checks on this PR.
> Use setup python action

- .github/workflows/ci-cd.yml
GitHub workflow failing
https://github.com/actions/runner-images/issues/10636 - the default Ubuntu version for Github workflows changed from 22 to 24. This introduces a new python version, which is not compativle with s3cmd. As a temporary solution bring back the older ubuntu version to preserve the same workflow behaviour until a more permament solution is implemented.
> fix: reintroduce ubuntu-22 as workflow version

- .github/workflows/ci-cd.yml
- Move the `ci-cd.yml` workflow back to `ubuntu-latest` (see scratchfoundation/scratch-www#9127)
- Use `s3cmd` version 2.4.0 (current latest) and Python 3.12 (the latest Python that is officially compatible with `s3cmd` 2.4.0)
GHA's `ubuntu-latest` tag recently moved from Ubuntu 22 to Ubuntu 24. GHA's `ubuntu-24.04` image includes several versions of Python, but it defaults to Python 3.12 (and does not include Python 3.5). This caused our deploys to stop working for at least two reasons:
1. We were installing `pip` via a script that was designed specifically for Python 3.5
* The script was downloaded from this hard-coded URL: <https://bootstrap.pypa.io/pip/3.5/get-pip.py>
* This script is no longer compatible with Python 3.12
2. We were installing `pip` version 21.0.1, specifically
3. We …
> Fix s3cmd deploy on ubuntu-latest

- README.md
- package-lock.json
- package.json
- src/lib/storage.js
- src/views/faq/faq.jsx
- src/views/preview/embed-view.jsx
- src/views/preview/presentation.jsx
- src/views/preview/project-view.jsx
- webpack.config.js
[UEPR-54](https://scratchfoundation.atlassian.net/browse/UEPR-54)
Install scoped dependency for scratch-gui. Revert to using old paths for assets in webpack configuration
[UEPR-54]: https://scratchfoundation.atlassian.net/browse/UEPR-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [UEPR-54] update to scoped dependency for scratch-gui

- src/components/footer/www/footer.jsx
- src/l10n.json
- test/integration/footer-links.test.js
MIT now requires that pages hosted on domains ending in `mit.edu` link to their Accessibility site.
- Closes #9129 
- ~All changes from #9129 are included here so that we can... y'know... deploy at all.~ These were merged separately
Add a footer link to the MIT Accessibility site.
This PR adds one new test, which verifies that clicking the link goes to the expected site.
> Hotfix: MIT Accessibility link

- src/views/become-a-scratcher/become-a-scratcher.jsx
[UEPR-150](https://scratchfoundation.atlassian.net/browse/UEPR-150)
For the endpoint Django returns as response string so the response type of the request header should be text. This was the reason the callback for become a new scratcher to not get executed.
[UEPR-150]: https://scratchfoundation.atlassian.net/browse/UEPR-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [UEPR-150] fix bad response type

- src/views/starter-projects/l10n.json
- src/views/starter-projects/starter-projects.json
- src/views/starter-projects/starter-projects.jsx
- src/views/starter-projects/starter-projects.scss
Fixes typo in project name and changes sizes of images to be clearer
Before:
After:
> fix: project name typo and changed images resolution

- .github/workflows/ci-cd.yml
I wasn't sure who would be best to review this, so I just assigned a bunch of people. :partying_face:
- Resolves POD-116
I recommend looking at this diff with "Hide whitespace" turned on (or add `?w=1` or `&w=1` to the end of the URL).
This will allow us to re-run a deploy. The primary use case I have in mind is if we need to switch our staging environment between different things we want to test, but it also means we can rerun a deploy if anything went wrong. Also also, we can now re-run integration tests without repeating the build and deploy steps, which might be useful in case of flaky tests.
By default, GHA prevents a push from one workflow triggering another workflow. That's meant to protect against infinite loops and such, but it also means that as of migrating to GHA, making …
> CI/CD improvements: repeatable deploy, auto-deploy prepared releases

- src/views/splash/donate/donate-banner.jsx
- src/views/splash/l10n.json
- test/unit/components/donate-banner.test.jsx
[POD-182]
Update the text of the banner that shows when a user is logged out. Remove the logic that differentiated between the regular banner and the end of year campaign banner.
Relevant tests are updated, all tests pass
[POD-182]: https://scratchfoundation.atlassian.net/browse/POD-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat[POD-182]: Update text of donation banner

- src/views/become-a-scratcher/become-a-scratcher.jsx
- src/views/contact-us/contact-us.jsx
- src/views/messages/message-rows/comment-message.jsx
- src/views/messages/message-rows/favorite-project.jsx
- src/views/messages/message-rows/love-project.jsx
- src/views/messages/message-rows/remix-project.jsx
- src/views/splash/activity-rows/favorite-project.jsx
- src/views/splash/activity-rows/remix-project.jsx
- src/views/splash/activity-rows/share-project.jsx
- src/views/studio/studio-activity.jsx
- src/views/studio/studio-member-tile.jsx
- src/views/studio/studio-project-tile.jsx
hrefs for /users/:username without a trailing / lead to django kicking back a redirect to /users/:username/ This activity leads to scratch-www-production having an extremely high number of redirects when compared to all other requests. It would be useful to clear this noise up for SRE related operations.
I have kept edits away from `preview` routes as I believe they are no longer in use.
> Lower excessive redirects

- src/redux/session.js
- src/redux/studio-permissions.js
https://scratchfoundation.atlassian.net/browse/POD-220
Hide the 'Invite Curators' section in the Curators view in the studio view if the user is a student, even in the case where the user is the owner of the studio.
> feat: disallow students from creating notifications

- package-lock.json
- package.json
- Resolves POD-225 "Remix notifications broken when for all languages but English"
Update `scratch-l10n` to the latest version.
The reason this broke is that #9472 changed the placeholders in the remix message but did not change the message ID. If the message lookup had failed, the English text (with correct placeholders) would have been used. Since the message ID didn't change, looking up non-English versions of the message in `scratch-l10n` succeeded, but resulted in the old translated message with the old placeholders. Since the placeholders didn't match up, variable replacement didn't work correctly, and the message ended up looking something like this:
Updating `scratch-l10n` gets the new placeholders, which will cause variable replacement to work correctly. Most languages don't have …
> fix non-English remix notifications (update scratch-l10n)

- src/components/grid/grid.jsx
- src/components/thumbnail/thumbnail-remove-button.jsx
- src/components/thumbnail/thumbnail-remove-button.scss
- src/components/thumbnail/thumbnail.jsx
- src/components/thumbnail/thumbnail.scss
- src/views/explore/explore.jsx
- src/views/search/search.jsx
Work related to POD-251. Depends on https://github.com/scratchfoundation/scratch-api/pull/1891
* Searches now wait for session data to be ready
* If the signed in user is an admin, switch to the /admin/search/ endpoint
* Send along token in these cases
* This should have no impact on caching for regular user queries, as we're only sending the token if the user is an admin.
Need to test:
* Admin users can search (and the new endpoint is used)
* Logged in users can still search
* Logged out users can still search
* ?
> feat: [POD-251] Search/explore admin

- src/l10n.json
- src/views/preview/presentation.jsx
- src/views/studio/l10n.json
- src/views/studio/studio-follow.jsx
[UEPR-332](https://scratchfoundation.atlassian.net/browse/UEPR-332)
- Pass flag for displaying the U16 modal copy when attempting to share a project
- Add different error message for unverified U16 accounts attempting to comment (depends on [scratchr2 changes](https://github.com/scratchfoundation/scratchr2/commit/12e40380083f2a591712477777633abbd1bfefa5))
- Update error message when an unverified U16 user attempts to follow a studio
Attempting to share a project:
Commenting:
Following a studio:
[UEPR-332]: https://scratchfoundation.atlassian.net/browse/UEPR-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UEPR-332] Align copy for parent confirmation prompts
