scratchfoundation/scratch-www

src/main.scss

Fixes issue #300.
To fix the horizontal scrollbar showing on the homepage (and other pages), I've set the horizontal padding on the view element to 0 in main.scss.
**Test Cases**
To test the fix, I checked that when scrolling vertically and attempting to scroll horizontally, no horizontal scrollbar appeared on the front page and credits page. My tests succeeded on Chrome 50, Firefox 44, and Safari 9.0.3 on OS X 10.11.3. 
~~**Possible problems**
I applied the fix to the main.scss file, which might cause problems if a horizontal scrollbar is desired on other pages that inherit from that file. I can't think of any page that would need a horizontal scrollbar, though.~~

Fix gh-300: Horizontal Scroll Bar Shows on Front Page

---

src/views/credits/credits.scss

Should fix #354.
Can someone test this on Firefox? (I only have Chrome)

Fix gh-354: 'Supported Organizations' in credits overflows

---

src/views/credits/credits.jsx

I removed Megan Haddadi from the Community Moderators section, and added her name to the Previous Scratch Team Members section, and added Linda Fernsel and Lily Kim (along with Scratch avatars) in the Community Moderators section (as per issue #333 ).
Tested on Chrome 50.0.2636.0 (canary) and Safari 9.0.3 on OS X 10.11.3 and found no issues regarding functionality.
I wasn't sure if there was a specific order for the people on the credits page, so I added Linda and Lily at the end of the Moderators section and put Megan Haddadi somewhere in the middle of the previous members section.

Fix gh-333: Add/Remove Moderators on Credits Page

---

README.md

Fixes #358 by changing the svg url.
* visit https://github.com/mewtaylor/scratch-www/tree/issue/gh-358-travis-badge to see the badge working correctly, compared with  https://github.com/LLK/scratch-www

Fix GH-358: Add new travis badge to readme

---

.travis.yml

Migrate environment for continuous deployment to `scratch-www-stage-v208`.
Resolves GH-351

Swap environments for CD

---

custom-locales.json

It seems that some languages have been removed from `intl-messageformat`'s locale-data configuration, so we need to add them manually. Fixes #381.

[Master] Fix GH-381: add languages to custom config

---

src/components/intro/intro.jsx
src/views/splash/l10n.json
src/views/splash/splash.jsx

`toLocaleString()` is not supported in Safari, but react-intl has a polyfill, and so it is. Fixes #356. This also localized the intro description string, which wasn't previously. This also fixes #366 by doing as @rschamp suggested and checking if the count is the default count before setting the value.
Local browsers tested:
* Chrome 49
* Safari 9
* Visit the homepage in any non-Safari browser, not logged in. There should not be a console error about propTypes.
* Visit the homepage in any non-Safari browser not logged in. The project count in the top right should appear as it does in production.
* Visit the homepage in safari not logged in. The project count in the top right should have commas in it.

Fix GH-356: Use `formatNumber` to localize project count

---

Makefile
bin/build-locales
bin/lib/locale-compare.js
test/localization/spot_check_about_has_strings.js
test/localization/spot_check_general_has_strings.js
test/localization/spot_check_nav.js
test/localization/spot_check_splash_has_strings.js
test/localization/spot_check_wedo2_has_strings.js

This cleans up the localization stuff in a couple of ways:
1. Adds localization spot checks
1. checks the localization for a few reference languages for the nav bar
2. for our localized pages (splash, about, wedo2), it checks to see that there are locale strings, whether or not they're english (to make sure at least something is on the page).
2. Make `build-locales` throw errors it catches
* The catch there before was meant to catch in the event that a file doesn't exist, and just continue (in which case the language will default to english). However, it was not specific enough, and was silencing other errors – now, it only catches the error if the file doesn't exist, and throws anything else, preventing a build.
* travis-ci should pass
* translations should still show up in all …

Cleanup: catch more localization errors that might arise

---

.sass-lint.yml
package.json
server/template.html
src/components/adminpanel/adminpanel.scss
src/components/banner/banner.scss
src/components/box/box.scss
src/components/carousel/carousel.scss
src/components/intro/intro.scss
src/components/languagechooser/languagechooser.jsx
src/components/languagechooser/languagechooser.scss
src/components/login/login.jsx
src/components/login/login.scss
src/components/modal/modal.scss
src/components/navigation/dropdown.scss
src/components/navigation/navigation.jsx
src/components/navigation/navigation.scss
src/components/news/news.scss
src/components/spinner/spinner.scss
src/components/subnavigation/subnavigation.scss
src/components/thumbnail/thumbnail.scss
src/components/welcome/welcome.scss
src/main.scss
src/views/about/about.scss
src/views/credits/credits.scss
src/views/hoc/hoc.scss

These warnings were annoying me because the noise makes it easy to miss real issues.
The `no-mergeable-selectors` rule is one that we do want to have, but right now it asks that you merge selectors in different `@media` blocks.  When the next release happens we should put that back.
https://github.com/sasstools/sass-lint/issues/307
Similarly, we want `force-element-nesting` but there is a problem with that because there's no easy way to have a nested selector in a list of selectors.
https://github.com/sasstools/sass-lint/issues/575
Finally, until they implement per-line overrides, we have to silence `class-name-format` because we don't have control over the `ReactModal` class names.  It's a useful rule to keep class names consistent though.  Per-line ignores should be coming soon. …

Upgrade sass-lint, quiet various warnings

---

src/views/jobs/jobs.jsx

Fixes #398 by adding the new `Page` component introduced this iteration
* Visit `/jobs` page – the page should display correctly

Fix GH-398: Add page component to jobs view

---

src/views/jobs/jobs.jsx

Fixes #406. The page linked to is currently non-existent, as it is implemented for this release in scratchr2. Assuming we deploy scratchr2 first, as usual, it will exist by the time this is live.
/cc @rschamp

GH-406: Add community counselor job

---

package.json
webpack.config.js

These depended on postcss<5, which caused webpack to output the errors like
```shell
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Node#_value was deprecated. Use Node#raws.value
Container#remove is deprecated. Use Container#removeChild
```
The autoprefixer-loader package is deprecated now and recommends using postcss-loader + autoprefixer itself.

Upgrade css-loader and autoprefixer-loader

---

src/components/footer/www/footer.jsx

Redo of #428 to fix the conflicts, as per https://github.com/LLK/scratch-www/pull/428#issuecomment-213577987
Fixes #427
Tested locally on Chrome.
Summary of change: 
https://wiki.scratch.mit.edu/ -> http://wiki.scratch.mit.edu/

Fix gh-427: Footer Wiki Link not working

---

src/views/conference/expect/expect.jsx

Since we don't have one yet.
* Visit `/conference/expect` – there shouldn't be a link to "View Full Schedule" in the schedule section

Bugfix: Temporarily remove "View Full Schedule" link

---

bin/configure-fastly.js

Otherwise, any URL beginning with static path names go to S3.
Resolves https://github.com/LLK/scratchr2/issues/3545

End static directories with / in Pass condition

---

src/routes.json
src/template-config.js
src/template.html

So that we can allow some pages to be responsive (i.e. conference, which is responsive at the moment).
* View splash page on a desktop – it should show up as usual
* View conference page on a desktop – it should show up as usual
* View splash page on a mobile device – it should be zoomed out to a desktop view
* View conference page on a mobile device – it should be responsive

Make viewport width a variable value

---

bin/configure-fastly.js

This avoids a situation where going to http://staging.scratch.mit.edu/hoc will redirect to https://staging.scratch.mit.edu/hoc.html.

Raise priority of rewrite conditions

---

server/template.html

Fixes mobile side of #356.
[Documentation of meta tag here](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW5)
As per https://github.com/LLK/scratch-www/pull/373#issuecomment-193934786
@mewtaylor 
Tested locally on Chrome.

Fix gh-356: Facetime Phone Numbers

---

src/components/login/login.scss

Fix cosmetic issue reported in #457 
Tested locally on Chrome.
4.4px is the max margin to the right of the button without the "Forgot password?" text wrapping to the next line.

Fix gh-457: Log In Margin

---

.travis.yml
package.json

Use the newly published to npm version of po2icu, which uses i18next-conv 2.2.5 which uses iconv-lite rather than iconv.  This avoids the node-gyp rebuild step.  Because of that, we can remove the gcc add-on step.
Also cache the pip requirements so they aren't installed each time.

Improve performance of Travis builds

---

src/views/privacypolicy/privacypolicy.jsx

I noticed on the new [privacy policy page](https://staging.scratch.mit.edu/privacy_policy/) there were some spacing issues beside links. (Some links didn't have a space between a word before or after)
Also, I noticed that bolding doesn't seem to work on the staging site. The `h3`s aren't bolded (very well if at all), and neither are anything that I put in `<b>` tags. Is this just an issue on the staging site or will changes need to be made for the page?

Fix Spacing Issues on Privacy Policy

---

src/components/footer/www/footer.jsx
src/l10n.json
src/template.html

Fixes #419 by doing the following:
* Makes `About Scratch` localizable by removing a duplicate react-intl key
* Localizes title tags after javascript is loaded onto the template page
The solution for the title tags is only half complete – it does not solve the issue of making title tags localizable for crawlers. However, that requires further thinking in the long term as we think about new localization systems, and how it's handled client-side.
* Load the about page in another language. "About Scratch" should be translated
* Load the about page in another language. The title should be translated.

Fix GH-419: Some localization cleanup

---

bin/configure-fastly.js

This fixes staging being broken currently.
Previously we relied on the static directory to construct the pass condition, but this doesn't include many things added to the build other than static files. So instead of adding these explicitly through `extraAppRoutes`, base the Pass condition on the final build, but exclude the view .html files. This way the version.txt, routes.json, and all directories added by webpack will be resolved to S3 rather than scratchr2.

Fix Pass condition for "static" routes

---

bin/configure-fastly.js

If the map function doesn't return anything, the added item is undefined. Avoid this by filtering the array before mapping.
I actually tested this :|

Filter before mapping to avoid returning undefined

---

src/components/footer/www/footer.jsx
src/l10n.json

So that it matches the rest, and is localized. Not sure, but I think this was fallout from de-localizing the Privacy Policy page.

Prefix privacyPolicy message string

---

bin/build-locales
bin/lib/locale-compare.js
test/localization/spot_check_about_has_strings.js
test/localization/spot_check_cards_has_strings.js
test/localization/spot_check_general_has_strings.js
test/localization/spot_check_nav.js
test/localization/spot_check_splash_has_strings.js
test/localization/spot_check_wedo2_has_strings.js

Before we were using glob, which was about to start failing on subdirectories in views (which we started using in `conference`). Instead of searching for `l10n.json`, it seemed more appropriate to instead look for localization by using the configured pages that need to be localized.
* run `make translations && npm start`. Check the website in pt_BR – it should be localised.

Use `routes.json` to get localization paths

---

Makefile

Unfortunately there's no way to map extensions to MIME type. The s3cmd tool guesses wrong and uploads svgs with text/html.  Upload everything but svgs first, then upload only svgs using the correct MIME type.
Fixes an issue where svg `<img>` tags were appearing as not found.
FYI @mewtaylor

Upload svgs with MIME type image/svg+xml

---

src/views/conference/schedule/schedule.scss

Changes the background color on the schedule page to $background-color instead of $ui-white, fixes #505.
**Test Cases**
Ensure that the background color of the time headers is consistent with the rest of the page.

Fix gh-505: Incorrect time header background

---

src/views/cards/cards.jsx

It was adding the `(English)` suffix no matter what before, when it should do so only if the cards are only available in english, and the language is not english. This fixes it by getting the locale from props, and also by making the conditional check a bit more safe by using `indexOf` instead of a complete equal check.
* Visit `/info/cards` in English. No links should have the `(English)` suffix anymore
* Visit `/info/cards` in Spanish. The first link should not have the suffix, but the others should.

Fix pdf localization check

---

src/routes.json
src/views/terms/terms.jsx
src/views/termsofuse/termsofuse.jsx

Migrate [Terms of Use](https://scratch.mit.edu/terms_of_use) as per #29.
HTML tested locally on Chrome 50.0 on ChromeOS.
A couple things to note:
-  3.2 is nonexistent. 3.1 and 3.3 exist, but not 3.2.
- 7.2 should be updated as users can now delete their own users without emailing the ST.
- 16 says that the terms of use were last revised March 4, 2015, but at the bottom of the page it says that the last update was April 2016
A little side note, this will probably be my last PR for quite a while. I've got an internship this summer, so I'll be less active both on Scratch and here. I'll probably make a PR once and a while, but definitely not a frequently as I have been recently.

Fix gh-29: Migrate Terms of Use

---

src/views/conference/schedule/schedule.jsx

Fixes #507 by adding a location hash after clicking on a different schedule day (conforms with the behavior of the 'back to full schedule' links on detail pages). 
I used window.history.replaceState to change the hash, so that moving back and forward in history drops the user into the place in the schedule where they left off, but that behavior is certainly up for discussion.
**Test Cases**
Clicking on days in the schedule should change the location hash in the address bar, and moving back and forward in browser history should load the schedule for the most recently accessed day.

Fix gh-507: Consistently change URI

---

bin/configure-fastly.js

The response from the request condition includes fields we don't want to send up with the cache condition

[Release] Fix cache condition request

---

bin/configure-fastly.js

The response from the request condition includes fields we don't want to send up with the cache condition

[Develop] Fix cache condition request

---

bin/configure-fastly.js

The response from the request condition includes fields we don't want to send up with the cache condition

[Master] Fix cache condition request

---

src/components/adminpanel/adminpanel.jsx
src/components/navigation/www/navigation.jsx
src/redux/session.js
src/views/splash/splash.jsx

This PR adds a {'loaded':true} item to the session object when a session is successfully loaded. This allows the navbar and splash header to have different states for 1) logged in users, 2) logged out users, and 3) not fully loaded pages. 
Fixes #395 and #396.
For the design, I've replicated the scratchr2 navbar design (search field is farthest element on the right side), and omitted the welcome element or news elements from the splash page.
Labeled as needs-discussion in case the way I'm modifying the session object isn't Kosher.

Fix GH-395 and GH-396: Add initial state to splash header and navbar

---

webpack.config.js

The source-map devtool adds a lot of time to startup, and eval works just as well for debugging.

Use eval for webpack devtool

---

src/redux/conference-schedule.js

1. Sort schedule using 24-hour clock to handle redundant times in am and pm
2. Sort time slots by type AND time, since some time slots have the same type.

[Develop] Hotfix: conference schedule bug fixes

---

src/redux/session.js

This PR resolves #548 by using lodash.defaults instead of lodash.defaultsDeep.
The reason for this is that using defaultsDeep doesn't replace a non-empty object with an empty object, which is necessary for the logged-in -> logged-out state change.

Fix GH-548: Sign out should take effect before reload

---

src/components/navigation/conference/navigation.scss
src/views/conference/expect/expect.jsx

Also fix the spelling for Nichole Pinkard's name (apologies!). 
It appears that flexbox has an easier time formatting wrapped rows on mobile than columns. Fixes #529.
/cc @sleggss

[Master] hotfix: mobile nav conference

---

src/views/developers/developers.jsx

Fixes issue in `/developers` page where we reference the Apache 2.0 license which *only* applies to the [scratch-blocks](https://github.com/llk/scratch-blocks) codebase.

Fix issues in FAQ of /developers page.

---

src/routes.json

for `/explore`, `/explore/projects` and `/explore/studios` to `/explore/<projects|studios>/all`.This fixes #574.
* Go to `/explore`. It should redirect to `/explore/projects/all`.
* Go to `/explore/projects`. It should redirect to `/explore/projects/all`.
* Go to `/explore/studios`. It should redirect to `/explore/studios/all`.

Fix GH-574: Add explore redirects

---

src/views/splash/splash.scss

Should fix #555 
@Choco31415 came up with the fix and tested it in Safari, I have tested it locally on Chrome 51.

Fix gh-555: Squished News Icons

---

src/views/faq/faq.jsx
src/views/faq/l10n.json

This PR localizes the FAQ title to replicate the current behavior on the Scratch site, resolving #554.
**Test cases**

Fix GH-554: Localize FAQ title

---

src/views/hoc/hoc.scss

This PR fixes #572 using @Choco31415's suggestion.
Tested on Chrome 51, Firefox 46.0.1, and Safari 9.1.1.
**Testing Steps**
Making the width of the window small enough to cause the center box to resize should *not* cause the headers in "Activity Cards and Guides" section to collapse on themselves. 
I did have some issues in Safari with the headers extending past the box, but this behavior is the same on the existing Scratch website.

Fix GH-572: HOC page formatting

---

src/template.html

Moves GA tracking code into the page head as per Google's recommendations. This should help resolve an issue where our Google Analytics performance metrics and bounce rate analytics appear to be skewed.

Move GA tracking code into page head

---

src/components/navigation/container/navigation.scss

On the Scratch Website, when hovering over any of the links on the navbar, the dark blue caused by the `:hover` code does not extend to the bottom of the navbar, causing there to be a faint line of the normal blue at the bottom. See here:
However, adding a height of 34px to the dark blue `:hover` code (`height: 34px;`) fixes this, ensuring that the dark blue color extends to the very bottom of the navbar. See here:
This is my first PR on github, so if I did anything wrong I am so sorry :)

Navbar issues; :hover

---

src/components/languagechooser/languagechooser.jsx

This PR fixes #605 by using the `value` prop rather than `defaultValue`. This makes the dropdown behave as expected (dropdown should default to the current locale).

Fix GH-605: Make languagechooser keep locale state

---

src/components/languagechooser/languagechooser.jsx
src/components/languagechooser/languagechooser.scss

This PR fixes #607 by adding a stylesheet for the languagechooser component that sets the `select` element's width to 13.75 rem (3 columns).

Fix GH-607: Language chooser should not be 100% width

---

src/components/navigation/www/navigation.jsx
src/lib/render.jsx
src/redux/session.js
src/views/splash/splash.jsx

We still need `componentWillMount` to handle the initial render for a logged in teacher first visting the page. Fixes issue in which a teacher would not see the banner immediately after dynamic login.

[Bugfix] Add permissions dispatch for `WillReceiveProps`

---

src/components/navigation/www/navigation.scss

This PR fixes #537 by setting the dropdown's position to be directly underneath the navigation bar. It also sets the dropdown's `box-sizing` attribute to `border-box` so that the dropdown aligns with the button in the navbar as per Carl's sketch in the issue. 
Before:
After:
I did notice that in the sketch on the issue, the dropdown remained darkened while the menu was open, but I figured a fix for that should go in another PR if that behavior is wanted.

Fix GH-537: Logged-in user dropdown gap

---

src/components/deck/deck.jsx

Fixes #623 
* Try to navigate to the homepage from the registration page for teachers. It should lead you to the homepage.

Fix GH-623: Add link to splash page around registration icon

---

src/components/teacher-banner/teacher-banner.jsx

`info` is not in there anymore. Fixes #625.
See #625 for test case.

Fix GH-625: fix educator faq link

---

src/components/navigation/www/navigation.jsx
src/components/navigation/www/navigation.scss

This PR adds an `open` class to the account nav link whenever the profile menu is open and darkens the link, as per Carl's sketch in #537.

Darken Account Nav Link when Menu Open

---

src/components/navigation/www/navigation.scss

so that it looks like it used to, and not to tall. Fixes #618.

Fix GH-618: Override devault input style for login

---

src/components/forms/validations.jsx

This was assigning `props` to defaults, rather than the other way around. Fixes #617.
* in `/eduators/register`, type a password that is too short. The error message should not refer to the "username" in any way (as it does currently according to #617.

Fix GH-617: switch ordering in defaults

---

src/views/teachers/landing/landing.jsx
src/views/teachers/landing/landing.scss

This PR fixes #633, #634, and #635 by adding a container div for the YouTube iframe to force it to maintain a border radius, as well as setting the height correctly and changing the "allowfullscreen" prop to "allowFullScreen".

Fix GH-633, GH-634, and GH-635: Embedded player fixes

---

src/redux/permissions.js
src/redux/token.js

redux doesn't like getting null values for actions, so give empty ones
/cc @rschamp

Fix GH-643: use empty string if no cookie value found

---

src/components/forms/validations.jsx

Looks as if the having one of these objects as the default causes overwriting in some way, as opposed to augmentation. Have the source object be an empty one, so that it gets the attributes of both defaults and props. Fixes #642.
* Register for a teacher account. On the "phone number" step, if your number is not real, it should show an error message

Fix GH-642: Use empty default object for validation factory

---

src/components/dropdown/dropdown.scss
src/components/navigation/container/navigation.scss
src/components/navigation/www/navigation.jsx
src/components/navigation/www/navigation.scss
src/components/page/www/page.jsx
webpack.config.js

This PR fixes #651 by adding a `staging` class to the navbar and the dropdown if an environment variable named `SCRATCH_ENV` is set to "staging".

Fix GH-651: Orangeify navbar on Staging

---

src/views/teachers/landing/landing.scss

Fixes #649 by removing the z-index attributes from the video containers, as it doesn't appear that they were needed after all.

Fix GH-649: Dropdown hidden by TED Talk

---

src/components/forms/form.jsx

I don't like that the state is being set to a calculation of existing props. When I did that calculation in `render`, it didn't update when fields were changed.
Fixes #645

Revalidate address step after invalid submissions

---

bin/lib/locale-compare.js

There is some stacking that happens in object keys that had been using the `-` to track language/view hierarchies, which was thrown off by view names that used a `-` in them. Switch to using `:`, and also make it customizable. Fixes #655.
/cc @rschamp

Fix GH-655: use custom-defined internal separator in locale compare

---

src/lib/api.js

Fixes #654
IE does not honor responseType: 'json', and will not parse responses as JSON unless json data is present in the request. For some reason this issue can also be solved by including a `json` attribute on the xhr request, but if that's present, url encoded form data is overwritten with the contents of the json.  So just try to parse the response ourselves if it looks like it wasn't parsed.
See https://github.com/Raynos/xhr/issues/123

Fix JSON response parsing in IE

---

src/views/explore/explore.jsx

so that we can store the query string with the tab name, since it's not the same in every instance. fixes #666, and makes a couple other style tweaks.

Fix GH-666: Make category options into key/value

---

src/components/forms/checkbox.scss

Fixes #628 by applying the same outline for focus as is currently applied to checked boxes.
/cc @carljbowman

Fix GH-628: Add box shadow for focus state on checkboxes

---

src/components/forms/form.jsx
src/components/forms/general-error.jsx
src/components/forms/general-error.scss
src/components/registration/steps.jsx

Resolves #647 
Also moves the message to right before the submit button so it's more likely that the user sees the message (e.g., if they're on a long form and it is scrolled out of view). That change requires a bit of magic, where the Form component manually adds the "all" value. But without a major overhaul of the validation system, I don't see how else to put the general error among the other fields.

Add style to general error messages

---

src/components/forms/select.scss

Disable default style for select elements in IE

---

src/components/forms/form.jsx

Was throwing a `TypeError` when child was null/undefined.
/cc @mewtaylor

Don't error on null children

---

src/components/registration/steps.jsx
src/views/teacherregistration/l10n.json
src/views/teacherregistration/teacherregistration.scss

It appears that the `required` field is not applied in the way we'd like it to be for the custom checkbox group and custom phone input fields, so do a `required` check on form submission. Additionally, this adds in a few style fixes. Fixes #695, #694, #693, #691.
/cc @rschamp @carljbowman

Fix GH-[695, 694, 693, 691] – Add custom validation for organization and phone

---

src/views/teacherregistration/l10n.json

I edited the error message to specifically say `letters, numbers,` instead of the possible misleading `characters` as per #684

Fix gh-684 - Changing error message

---

src/components/forms/select.scss

Fixes #701 by adding an ::-ms-value pseudoclass to the select element to set the background color and color attributes to the original values. 
It also fixes #700 by setting left padding to 1rem, as text-indent does not appear to work on select elements in IE.

Fix GH-701, GH-700: IE11 select form background, indent issues

---

src/views/teacherregistration/teacherregistration.scss

This PR fixes #674 by setting the horizontal margin of the waiting room card elements to auto instead of 0.

Fix GH-674: Waiting room cards should be centered in IE

---

package.json
webpack.config.js

This is to remove the deprecation warning about React.__spread. It will give us other nice things too, though.

Use babel-loader for jsx transpilation

---

src/components/registration/steps.jsx
src/l10n.json
src/redux/session.js
src/routes.json
src/views/studentcompleteregistration/studentcompleteregistration.jsx
src/views/studentcompleteregistration/studentcompleteregistration.scss
src/views/studentregistration/studentregistration.jsx
src/views/studentregistration/studentregistration.scss
src/views/teacherregistration/teacherregistration.jsx

When students created by the teacher log in, they are redirected to a page so that they can complete their registration details.
Updates how banned users are redirected, since the middleware for this behavior and banned users share the list of paths, and `/session/` needed to be whitelisted.
Requires https://github.com/LLK/scratchr2/pull/3860
* As an educator, create a single student and sign in as that student
* They should be redirected to `/classes/complete_registration` from both the home page and scratchr2-based pages
* View `/session/`: both `force_password_reset` and `must_complete_registration` should be `true`
* Complete the registration at `/classes/complete_registration`
* It should match what is laid out in #3679
* It should contain a "Create a Password" step
* As an educator, …

Add Student registration update view

---

src/views/studentcompleteregistration/studentcompleteregistration.jsx
src/views/studentregistration/studentregistration.jsx

While doing so, fix an issue where logged out users just saw a spinner when visiting `/classes/complete_registration` — now it shows an error.

Make the student registration views more consistent with each other

---

src/components/card/card.scss
src/components/forms/checkbox.jsx
src/components/forms/input.jsx
src/components/forms/input.scss
src/components/forms/phone-input.jsx
src/components/forms/phone-input.scss
src/components/forms/row.scss
src/components/forms/select.scss
src/components/forms/textarea.jsx
src/components/forms/textarea.scss
src/components/navigation/www/navigation.jsx
src/components/navigation/www/navigation.scss
src/components/registration/steps.jsx
src/components/registration/steps.scss

and make use of the FRC `elementWrapperClassName`, since they way we did it before – custom `className` strings on the element – was not working. Fixes #749 .
* Phone number input
* "Why use scratch" textarea
* Checkbox group

Fix GH-749: Fix formatting for a few form elements

---

src/components/registration/steps.jsx
src/views/teacherwaitingroom/teacherwaitingroom.jsx

Fixes #757. Note: Because we are getting this info from the session, the redirect may not happen until the page is rendered first in cases where the connection is slow, or the db is slow.
* With a confirmed teacher account, try to go directly to the `waiting` page. It should redirect you to "My Classes"

Fix GH-757: Redirect to `/educators/classes` if a confirmed teacher

---

src/components/card/card.scss
src/components/registration/steps.scss

I believe this will keep the misalignment from happening across browsers. Sets the top left corner to the top left corner of the input block.
Tested in Chrome 52 and confirmed this fixes the issue there, but Sauce was having network issues so I wasn't able to check this in other browsers yet. I think the absence of the `top` declaration was the source of the pain for this though.
Resolves #770

Set common y-origin for validation bubbles

---

src/components/registration/steps.jsx
src/l10n.json
src/views/teacherregistration/l10n.json

It's reused in the other registration views so doesn't belong in teacherregistration/l10n.json
Fixes #783 
/cc @mewtaylor

Move "select country" to general strings

---

src/views/jobs/jobs.scss

This PR fixes #781 by setting the width of the `img` element to 100% (like the rest of the paragraph elements on the page). 
This page will probably need some more work when #217 is merged, but that's outside the scope of this PR.

Fix GH-781: Jobs page image is too wide

---

src/views/teachers/faq/l10n.json

so that it doesn’t 403 for people without educator accounts. Fixes #658.

Fix GH-658: remove link to “My Classes” from faq

---

src/views/terms/terms.jsx

Fixes #822 
Turns out the link tag was there, it just didn't have any text.
@thisandagain @mewtaylor @rschamp @technoboy10

Fix gh-822: Missing Email Address

---

src/views/splash/splash.jsx

otherwise, `this` is undefined. Fixes #673.

[Master] Hotfix: Bind the banner api method to the splash page

---

src/components/registration/steps.jsx

It appears that some valid phone numbers in some countries differ in length from what is specified in the util’s phone number format. Fixes #816.

[Master] Hotfix: Remove `phoneLength` validation

---

src/views/teachers/faq/faq.jsx
src/views/teachers/faq/l10n.json

This PR fixes #806 by embedding the youtube video using `iframe` and amending the text to what was suggested by @kaschm :)
This is what the page looks like for me after the PR on my local host:
Hope this helps!
@thisandagain @mewtaylor @rschamp @technoboy10

Fix GH-806: Teacher Account Video Embded

---

src/lib/api.js
src/lib/smarty-streets.js

This makes use of a custom header used by Smarty Streets (https://smartystreets.com/docs/us-street-api#x-standardize-only) which uses street number ranges, rather than exact addresses, to return results. This can help if, for some reason, we have someone sign up whose post office listing has not been updated, for instance. 
Fixes #828.

[Master] Fix GH-828: check street number range for address

---

src/components/footer/conference/footer.scss
src/components/forms/validations.jsx
src/components/login/login.scss
src/components/registration/steps.jsx
src/main.scss
src/views/studentcompleteregistration/studentcompleteregistration.jsx

for Student Complete Registration. This fixes #760.
* Sign in as a student, and be redirected to the registration page. You should not be able to use your own username as a password
* Regression tests: 
* Should not be able to use "password" as your password
* Password should be longer than 6 characters

Fix GH-760: Add username `not equals` to password validation

---

src/components/card/card.scss

now that it’s not centered but rather top/down, we don’t need this anymore. This was breaking with the new max character copy.

For GH-835: eliminate max height of validation messsage

---

src/components/card/card.scss
src/components/registration/steps.jsx
src/l10n.json

This fixes #835 by adding maxlength validations for: first name, last name, organization name, organization role, organization url, gender input, address line 1, address line 2, zip code, city.
This also changes `getCountryOptions` to take in a required argument of `intl`, which is meant to be the currently injected `react-intl` object, so that it can localize the `select country` string on its own. This eliminates hundreds of console warnings, since the previously used `<FormattedMessage />` component would wrap each option in a `span`, which threw a warning for react. 
* These fields should say they're too long after *more than 50* characters are typed:
* first name, last name, organization name, organization role, city
* These fields should say they're too long after *more than 100* …

[Master] Hotfix GH-835: Add maxLength validations when needed

---

src/components/thumbnail/thumbnail.jsx
src/l10n.json
src/views/explore/explore.jsx
src/views/splash/l10n.json
src/views/splash/splash.jsx
src/views/teachers/landing/l10n.json
src/views/teachers/landing/landing.jsx

This is part of https://github.com/LLK/scratchr2/pull/3955, adding strings that have been ported over:
* "by" in thumbnails
* "Explore" header on the Explore page
It also does a bit of cleanup on the splash page to format the intl handling as we do on other pages  (i.e. remove `defaultMessage` from being inline, just use the `id`)
[UPDATE] Also fixes #840.

Add missing locale strings for localization

---

src/routes.json

Resolves LLK/scratchr2#3895
* Go to /educators/registration — you should see the teacher registration page
* Go to /educators/registration/ — you should see the teacher registration page (not a 403)

Allow an optional / in teacher registration URL

---

src/components/card/card.scss
src/components/registration/steps.scss

Because the `input` field is already to the right, they were being transformed too far over. This overrides the transform to be correct, and also scopes some css in more detail.

Bugfix: align gender/organization type input msg with other messages

---

src/components/registration/steps.jsx

Since we only check for the US, only require for that country. Other countries have zip codes, but it seems better to do it this way than codify which countries do/do not have zip codes (in case local practices are not the same as international information). Fixes #825

Fix GH-825: Only require zip code for US addresses

---

webpack.config.js

`caniuse` updated their api recently, and it appears that support for safari 8 is no longer in the last 3 versions (and it appears that safari 8 is not listed as supported there in general). explicitly add the version back in to make sure the proper `-webkit` prefixes are included for that browser.

Bugfix: Add webkit prefixes for safari 8

---

src/components/registration/steps.jsx

the `//` for an empty username that gets sent to the backend causes a 500 error. This is an edge case in formsy, as it has not detected a change value yet, so handle it in the username validation method. Fixes #872

Fix GH-872: Check for username before sending

---

languages.json

My bad on the misunderstanding! This correctly names Albanian in the language menu. Towards https://github.com/LLK/scratchr2/pull/4013.

Rename Albanian correctly

---

Makefile

A possible fix for #787. I haven't been able to reproduce the error locally, and can't seem to cause the error to happen when deploying locally anymore :(
This header should be there in any case, and is recommended when using the other cache headers we have, `ETag` and `Last-Modified`.
I've made the cache length 1 day, just thinking that would be a good balance between giving the benefit of a browser cache and hedging the risk that it lasts too long (given we're having issues with it anyway).  I am open to suggestions for a different length.

Add Cache-Control header to all S3 uploads

---

src/views/splash/splash.jsx

This resolves the "Cannot read property 'x' of undefined" errors that occur when the API returns non-JSON responses. For instance if the proxy endpoints return 500 error responses from scratchr2.
We need a way to let the user know when things aren't working in general, but we don't have that.  In the meantime just log the error.

Don't set state to undefined API response bodies

---

package.json
test/integration/check_navbar_links.js

This is what I have for the initial automated test per https://github.com/LLK/scratch-www/issues/590#issuecomment-243812155. The initial test is to check that the URL in the Create link in the navbar is correct when the user is signed out (without navigating to the editor, and using selenium and tap, as discussed).
There are some questions I have about it:
- A better solution than brittle XPath (I can continue looking into this; first I wanted to get something working)
- I set it up with a driver for Chrome; should I enumerate through the other available drivers here? How does this work with saucelabs?
- I created an integration folder in the test folder for these kinds of automated tests, but I am open to changing the structure
- Integration with travis? (I think it should be simple?)
- …

Fix GH-590: initial automated test

---

src/components/forms/row.scss
src/components/registration/steps.jsx

Fixes #933 by giving the "Not Required" styling used in organization url (i.e. separated out label elements)
/cc @rschamp

Fix GH-933: Put label for “Not Required” above input

---

src/views/privacypolicy/privacypolicy.jsx

Should fix #938 
Test cases:
- Link to the Scratch Foundation should now be http://www.scratchfoundation.org/ instead of http://codetolearn.org
- There should now be a line at the bottom of the page that reads: "The Scratch Privacy Policy was last updated: October 2016" (Text should also be **unbolded**)

Fix gh-938: Update Privacy Policy

---

src/lib/smarty-streets.js

re-fixes #828 by loosening restrictions on the check once again (see https://smartystreets.com/docs/us-street-api#match-strategy)

[Master] Hotfix: loosen restrictions on smartystreets check

---

bin/build-locales
bin/lib/locale-compare.js
package.json
src/components/activity/activity.jsx
src/views/splash/splash.jsx
src/views/wedo2/l10n.json
test/fixtures/test_es_md5map.json
test/functional/build_locales_icuMap.js
test/functional/build_locales_mergeDupStrings.js
test/functional/build_locales_mergeTranslations.js

Updated the build-locales script to handle duplicate strings. 
You can spot check the output by looking in the intl directory. 
about.intl.js: the key 'about.whoUsesScratch' should be translated in many languages. 
hoc.intl.js: the key 'hoc.tipsAnimateYourNameTitle' should be in languages other than English

Fix gh-940: missing translations

---

Makefile

See #968 
From https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
> "no-cache" indicates that the returned response can't be used to satisfy a subsequent request to the same URL without first checking with the server if the response has changed. As a result, if a proper validation token (ETag) is present, no-cache incurs a roundtrip to validate the cached response, but can eliminate the download if the resource has not changed.
This is what we want to happen.

[Master] Use no-cache so ETags are used

---

languages.json

This language needs some updates on the editor/block translations before we can add it back in – see https://github.com/LLK/scratch-flash/issues/1165

Remove Khmer from language list

---

src/views/developers/developers.jsx

Fix #928. Following style of the rest of the developers page, assuming it's like this because of #924.
I took and slightly tweaked copy from the standard ScratchJr materials.
cc: @kaschm @thisandagain @chrisgarrity

Add ScratchJr to developers page

---

src/views/search/search.jsx

This PR resolves #899 by adding a check for an undefined formData.q value (the search page populates the search bar's defaultValue, but not actual value), and searches for `this.props.searchTerm` if the check fails. 
Another option would be to prevent the user from searching the same term repeatedly, but I'm not sure what UX is preferable (having the page react like it normally done when searching, vs saving bandwidth/time by assuming the user doesn't want to search for the same thing again).

Fix GH-899: Re-searching should not search for 'undefined'

---

src/components/registration/steps.jsx

Should fix #706 
Separated the null check from the area code check so that when the field is null the 'required' popup will be displayed.

Fix gh-706: "This field is required" when phone number is null

---

src/routes.json

@kaschm needs `/hoc?somequerystring=1` to work, but it currently doesn't because of the regex we use for Fastly.  This should allow the hoc url with a querystring to resolve to the page currently visible at `/hoc`.
Eventually we should fix this for every URL, but that is too large of a change for a hotfix.

[Master] Allow querystring in /hoc URL

---

src/views/privacypolicy/privacypolicy.jsx

Should fix #996 
Test cases:
- 
- The following text should now be added at the bottom of the "How does the Scratch Team use my Information?" list.
> Scratch reserves the right to share user information with the appropriate authorities (including schools, school districts, and law enforcement, when necessary) for the purposes of protecting the safety of users, other individuals, or the security of the site.
- This typo should be fixed: `(such as a school or internet service provided)` should now be `(such as a school or internet service provider)`.
- The month the Privacy Policy was last updated at the bottom of the page should now read `November 2016`

Fix gh-996: Update Privacy Policy

---

src/components/masonrygrid/masonrygrid.scss

Set column-count for all widths since it’s needed for Firefox, IE and Edge browsers

fix column count for IE and Edge

---

bin/build-locales
src/views/cards/l10n-static.json

otherwise, they will get the id for the url, rather than the english version. Fixes #1059.
/cc @rschamp 
* Links on `/cards/` page for the `Getting Started` pdf should be localized in Spanish and Brasilian Portuguese
* Links for other cards on the `/cards/` page should be in English
* Links for the pdfs in `ttt` should all be in English, for Spanish, Brasilian Portuguese, Persian and Furlan.

[Master] Fix GH-1059: Still build url localization for languages with none

---

src/routes.json

[Staging] Hotfix: allow querystrings for `/go`

---

src/routes.json

again, the same as #1004, but needed too soon for a full fix of this issue.

[Master] Hotfix: allow querystrings for `/go`

---

src/views/search/search.jsx

Should fix #1066, brought up by @chrisgarrity here: https://github.com/LLK/scratch-www/issues/1023#issuecomment-262292730
Test cases:
-
- `h1` header at the top of the search page should now be localized.

Fix gh-1066: Localize Search Header

---

src/views/explore/explore.jsx
src/views/explore/l10n.json

Should fix #1023 
Test cases:
-
- `h1` element at the title of the page should now be localized
- dropdown on the right side of the page should now be localized

Fix gh-1023: Localize Explore Title and Dropdown

---

src/views/splash/hoc-banner/hoc-banner.scss

since that’s whats in the specs, and it handles centering with `align-items`. Fixes #1083

Fix GH-1083: switch to column in tablet

---

src/views/splash/hoc-banner/hoc-banner.scss

so that the header elements are evently aligned vertically. fixes #1089

Fix GH-1089: Move margin to flex-row element

---

src/views/splash/hoc-event-row/hoc-event-row.jsx
src/views/splash/hoc-event-row/hoc-event-row.scss

See https://github.com/LLK/scratch-www/pull/1081#issuecomment-263746724. This also adjusts tracking that Youtube might do on the video to only apply to people who watch it, which can be adjusted if desired @kaschm. Also adjusts padding to accommodate https://github.com/LLK/scratch-www/pull/1081#issuecomment-263747658.

Turn off related videos in event row embed

---

.eslintrc
src/views/wedo2/l10n.json
src/views/wedo2/wedo2.jsx

Fixes #930 by updating the text – this is still in progress, as a Windows device manager link is still needed.

Fix GH-930: Update wedo2 text for new Windows deploy

---

src/components/registration/steps.jsx
src/components/registration/steps.scss

This fixes #962 – the margin was causing flex to overflow the radio buttons when the text was long, causing the male and other options to render on top of each other. This fixes that by giving the radio buttons a fixed with relative to the parent container, and by ensuring that languages with long localizations will still be visible in overflow text.
* In any language (specifically pt_BR, en, and es to test), all three options should show up for this question
* If the input field is selected, it should require text be added in the input before the selection is valid
* If the input field is given a gender, that should be the gender recorded for the user in the db

Fix GH-962: use width for radio buttons, not margin

---

src/components/forms/validations.jsx
src/l10n.json
src/views/teacherregistration/l10n.json

Fixes #966. I was trying, if possible, to not introduce localization at the component level in order to keep it in the views – but that seemed a bit too involved given that the fix in this way is only a few lines long.

Fix GH-966: Localize default “required” message

---

src/routes.json

This fixes https://github.com/LLK/scratchr2/issues/4195 by updating the regex to catch two slashes. I decided to intentionally not catch more than 2 – it’ll 404 on 3 or more, which seems appropriate.
We could also redirect on 2 slashes to the homepage, but this seemed just as well.

Fix r2-4195: Handle double slash in splash pattern

---

src/components/registration/steps.scss

fixes #1101. I wanted to apply a custom class to the input, however that is unfortunately obscured and unreachable with our current implementation of `formsy-react-components`

Fix GH-1101: only apply right margin to radio input

---

src/l10n.json
src/views/studentcompleteregistration/studentcompleteregistration.jsx
src/views/studentregistration/studentregistration.jsx
src/views/teacherregistration/teacherregistration.jsx

Fixes #1107.  Right now I'm adding this into the frozen branch since it could be hotfix-worthy, but if @jwzimmer would like this to respect the freeze I'll update the base accordingly.
In case the response does not supply `msg` or `errors`, provide a default. If `registrationError(s)` is empty, we do not show the error card, which causes "silent" failures.
* The following should still work as expected:
* Registering as a new teacher
* Registering as a new student through a student sign-up link
* Completing registration as a student when logging in for the first time after a teacher creates the student account
* You should see an error page rather than getting stuck on the second step after exceeding the registration rate limit (we can artificially limit this for testing) in the following …

Provide fallback error messages

---

src/routes.json

It’s not necessary, and I believe is causing confusion for the faslty config.

Remove `routeAlias` from splash redirect

---

src/views/studentregistration/studentregistration.jsx
src/views/teacherregistration/teacherregistration.jsx

Missed in #1128, this fixes the rest of the handler to not expect a body from the request. Fixes #1124 again.

Allow empty response, again

---

src/components/registration/steps.jsx
src/l10n.json
src/views/teacherregistration/teacherregistration.jsx

Part of https://github.com/LLK/scratchr2/pull/4448, adds an opt-in subscribe button to be added to a new teacher-specific email list.

For R2-4092: Add checkbox to opt-in to teacher emails

---

src/components/registration/steps.jsx

Fixes #1097 by not making the server-side username validation call if the client side validations have failed. It runs the [isValidValue()](https://github.com/christianalfoni/formsy-react/blob/master/API.md#isvalidvalue) check on the input `onBlur` to make sure it is a valid value before trying, preventing a possible 404 from a username with disallowed characters.
This is not the ideal way to do this, since it’s getting the input from an array, and an array buried multiple levels of `refs` deep. However, to make this different would require significant refactor, given our current use of `formsy-react-components`. I'd like to not do that refactor unless we also have a conversation about our registration UX regarding when we want validation to occur generally – i.e., do we want to move to …

Fix GH-1097: Don’t validate username server side unless it passes client-side checks

---

src/components/registration/steps.jsx

Should fix #1159 
- 2017 should now be an option
- 1916 should no longer be an option

Fix gh-1159: Add 2017 to Teacher Registration

---

src/l10n.json
src/views/explore/explore.jsx

Should (start to) fix #1009 
Not entirely sure about the xhr thing, but I think it might be covered already.
Test cases:
-
- There is a new button with the text 'tutorials' to the right of the 'stories' button on the explore page
- When clicking it, it should take you to [the explore tutorials page](https://scratch.mit.edu/explore/projects/tutorials/)

Fix gh-1009: Add Tutorials Button

---

src/routes.json

Should fix #1157 
Test cases:
- `/search/` should now redirect to `/search/projects/`

Fix gh-1157: Search Redirect

---

src/components/navigation/www/navigation.jsx
src/views/search/search.jsx

This prevents the search form from setting an invalid URL.
Also, clean up usage of Redux for the searchTerm on /search.  Now that the search term is encoded, we need to be sure both the search fields get a decoded string. Parse, decode and set this string via Redux in componentDidMount, and use it in both places.
Resolves #1153.

URI-encode search string on form submit

---

src/l10n.json
src/views/teachers/faq/l10n.json

Fixes #1178 
**On teacher FAQ:**
Question should now read `Why do I have to wait one day for my account?` instead of `Why do I have to wait 24 hours for my account?`
**On teacher account registration:**
Sentence should now read `The approval process may take up to one day.` instead of `The approval process may take up to 24 hours.`

Fix gh-1178: 24 hours => one day

---

src/views/thingstotry/l10n.json
src/views/thingstotry/ttt.json

Added Fashion and Story activities between Hide and Pong.
Updated description text.
Note that Cards and Guide locations were already included in l10n-static.json
Guides and tutorials still need to be added in the designated places (specified in #1170 )

Added Fashion and Story activities to Things to Try

---

src/components/grid/grid.jsx
src/components/thumbnail/thumbnail.jsx
src/views/search/search.jsx

* Fixes #1189: Wait for the search term prop before performing the search. Also encode the term sent to the API, so the API request uses a valid URL.
* Also fixes an unlogged error, the same as #1153, but from the search form on the search page (not in the nav bar).
* Finally, clean up keys to resolve warnings from React. There were so many on the search page that my browser was locking up (only affects development).

Search view fixes

---

src/views/conference/2017/index/index.scss

needed by ie11 to render correctly. fixes #1208

Fix GH-1208: add height to svg

---

src/components/registration/steps.jsx
src/views/teacherregistration/l10n.json

Fixes #1196 by removing the other empty string from the localization file, and just adding it to the options list separately.

Fix GH-1196: Don’t localize an empty string

---

src/routes.json
src/views/jobs/jobs.jsx
src/views/jobs/moderator/moderator.jsx

Should resolve #1218 
- Back-End Engineer position removed from jobs page
- Community Moderator position added to jobs page
- Community Moderator page added at `/jobs/moderator`
- All links should be functional on the Community Moderators page (Twitter links, create link, mailto link)

Fix gh-1218: Community Moderator Page

---

src/routes.json

this `routeAlias` is being added as it’s own path pattern since it’s not matching the other one, causing us to hit our 512 char limit.
/cc @thisandagain @chrisgarrity – now we know where we're at when we want to add new pages :).

Match `routeAlias` with that of `/jobs` route

---

src/views/conference/2017/index/index.jsx

Should resolve #1234 
Another thing to note would be that we can now remove the l10n string for `Contact Organizer` if that is desirable.
- Date for China conference should now read `May 20, 2017 - May 21, 2017`
- China button should now read `Visit Website`
- China button should now go to http://scratchconference2017.sxl.cn/

Fix gh-1234: Update China Conference

---

bin/build-locales

Fixes #1199 by continuing the iteration over languages even if a view doesn’t have an l10n file. The issue was that only the `en` language object was getting added when the view didn’t have an l10n file, because of the `hasOwnProperty` check. This adjusts it to iterate over languages anyways, and only ouput the `No translations for…` message if it’s for a language of a view that does have an l10n file.
* Change language on the homepage. Go to `/terms_of_use` – the header and footer should be translated, and the langue in the dropdown should match what you changed it to

Fix GH-1199: iterate over languages for views without l10n files

---

src/views/conference/2017/index/index.jsx

Costa Rica dates were updated, plus fixed a gotcha with the China dates. (Wasn't counting on the month number being 0-based)
Oh yeah, I forgot to reference this one to #1239 
- Costa Rica's conference dates should now be November 10, 2017 - November 12, 2017
- China dates should be May, not June. (Whoops!)

Fix gh-1239: Update Conference Dates

---

src/components/footer/www/footer.jsx
src/l10n.json

Fixes #1194 
- Footer text for the day.scratch.mit.edu should still read `Scratch Day`

Fix gh-1194: Remove Scratch Day from Localization

---

src/views/developers/developers.jsx

Just noticed that the type on this page was `About` instead of `Developers`. No logged issues about this, it's just me being nit-picky.
I might be wrong about this, please correct me if I am.

Nit-picky Developer Class Type

---

src/components/dropdown/dropdown.scss

Fixes #728 
- Click the dropdown in the nav-bar (where your username is). The dropdown should now be aligned with the nav-bar component, like so:

Fix gh-728: Align Misaligned Nav-bar Dropdown

---

src/components/registration/steps.jsx

This fixes #1278 by ensuring that the `birthOffset`, not a hardcoded value, is used for validation – meaning that students will not be checked if they're younger than 13. It also changes to show the error on the year field for UX purposes.

Fix GH-1278: Use birthOffset for age check

---

src/routes.json

Fixes #1265 by updating the logic for checking the route to include an optional moderator endpoint check.

[Master] Hotfix GH-1265: Update jobs route to include moderator

---

src/views/credits/credits.jsx

Resolves #1296 
- DD Liu should now be added to the "Scratch is designed and developed by the Lifelong Kindergarten Group at MIT Media Lab:" section
- Icon for DD Liu should be https://cdn.scratch.mit.edu/get_image/user/527836_170x170.png
@mewtaylor @rschamp @thisandagain

Fix gh-1296: Add DD Liu to Credits Page

---

src/components/dropdown/dropdown.scss

Fixes #1292 
Test cases:
- `min-width: 160px` should not be applied on desktop sized screens
- `min-width: 160px` should be applied to mobile sized screens
@mewtaylor @rschamp @thisandagain

Fix gh-1292: Dropdown Mobile Un-Friendly

---

bin/build-locales

since we’ll need them for nav/footer strings
/cc @chrisgarrity

Fix 1303 Fallout: Apply defaults for untranslated pages too

---

bin/lib/fastly-config-methods.js
src/routes.json

This fixes https://github.com/LLK/scratchr2/issues/3798 by using regex in expressjs patterns, and then also parsing those regex patterns for fastly, such that we can limit the scope of the regex created for a specific view.

Fix r2-3978: Use regex in express patterns to limit scope

---

src/components/footer/www/footer.jsx
src/routes.json
src/views/download/download.jsx
src/views/download/download.scss
src/views/download/l10n.json
src/views/privacypolicy/privacypolicy.jsx

Fixes #1351 by including a call to `version.xml` to get the most up-to-date offline build version, defaulting to the current version, `456.0.3`. This also fixes #1352 by switching the route to `/download`, with a redirect from `/scratch2download/`
* Go to download page. All downloads for the offline editor should download
* Go to `/scratch2download` – you should be redirected to `/download`
* click on `offline editor` in the footer – you should be directed to `/download`

Fix GH-1351: Make version dependent on xml call

---

README.md

From the issues and from my own experience it seems that the standalone client doesn't work well on windows. I added a section "Windows" to the readme, to point windows users to two possible solutions. 
(1) Cygwin has not worked for me personally, but for @cwillisf it did. 
I tried (2) Wubi(uefi) which worked perfectly well. It is a simple .exe wich installs Ubuntu from within Windows and you can decide for Windows or Ubuntu when booting. No partitioning is needed. In Ubuntu you can still access your files from Windows. You have to install things like npm, node and git again for Ubuntu though. I hope my wording is okay, feel free to change it though. I also wasn't sure about how much information I should provide about the two solutions.

Readme update for running standalone client on Windows

---

package.json

FIxes problem where webpack wasn’t copying static or intl to the build directory.
Gory details:
node-dir is a dependency of copy-webpack-plugin. If you don’t already have it installed, the latest version (0.1.17) gets installed and that one breaks copy-webpack (https://github.com/fshost/node-dir/issues/50). Webpack build will complete. but there will be an error `ERROR in this is not a typed array.` We didn’t see it earlier because node-modules are cached.

Add dependency for node-dir 0.1.16

---

.travis.yml

The ubuntu image that we’re using doesn’t include a C++11 compliant compiler. Followed Travis instructions to install a compiler:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

Install c++ compiler to build native extensions

---

src/views/download/download.jsx
src/views/download/download.scss

Adds the numbers back in above the download steps, and also moves the “note for mac users” down into a callout.
/cc @carljbowman @TheGrits

Tweak some styling for the download page

---

src/routes.json

Simplify help redirect so it doesn't match anything other than `/help/` (with the last slash optional).

Redirect help

---

src/components/footer/www/footer.jsx

Fixes #1364.
/cc @SpeakkVisually (just fyi)

Fix GH-1364: Change `help` to `tips` in footer

---

src/views/tips/l10n.json

Getting started tutorial link started with `//` instead of just `/`.

Fix typo in tutorial URL

---

src/views/tips/tips.scss

Note for future reference - set the size for SVGs with height not width if using rem.
IE on Windows 7 doesn’t resize correctly if the width is set with rem. Height works with rem, and exact pixel width works, but that should be avoided.

Fix blocks icon for windows

---

src/views/tips/l10n.json

The l10n string for tips.subtitle was missing a closing </a> - Browsers were handling it, but figured it would be better to fix it.

Add missing closing tag for PDF Guide

---

src/views/jobs/jobs.jsx

Resolves #1404 
- 'Junior Developer' should be the position title
- the link should lead to https://www.media.mit.edu/about/job-opportunities/junior-web-designer-scratch/

Fix gh-1404: Add Junior Designer Position

---

src/views/credits/credits.jsx

Resolves #1397 
- "pootle" should now be removed
- "transifex" should now be added under the organizations that donate their services

Fix gh-1397: Update Supporting Organizations

---

src/views/download/l10n.json

Resolves #1399 
- `This issue is due to a bug introduced in Adobe Air version 14. (released April 2014).` 
Should now read: 
`This issue is due to a bug introduced in Adobe Air version 14 (released April 2014).`
- `If your offline editor is crashing directly after Scratch is opened, install the Scratch 2 offline editor again (see step 2 above.)` 
Should now read: 
`If your offline editor is crashing directly after Scratch is opened, install the Scratch 2 offline editor again (see step 2 above).`

Fix gh-1399: Misplaced Periods Fix

---

src/views/download/download.scss

Resolves #1382 
- the "Note for Mac users" box should have its text centre-aligned now

Fix gh-1382: Centre Align Note

---

src/l10n.json

‘Help’ and ‘Discuss’ are not needed now that they’ve been replaced with the Tips page.
Fixes #1362

remove obsolete strings

---

test/integration/README.md
test/integration/smoke-testing/test_signing_in_and_my_stuff.js
test/integration/smoke-testing/test_signing_in_homepage.js

It works! Fixes https://github.com/LLK/scratch-www/issues/1385. But.
Things I'm not sure about:
1. passing in the credentials from another file
2. assuming existence of projects, studios, and shared projects
a. To address this we could make a test user solely for this on Staging & Production, but then where to put the credentials? Last pass and everyone makes their own un-checked-in credentials file?
3. using eval & window
4. we should refactor the helper functions rather than including them in multiple files; I could do that as a separate pr since it involves changing other tests as well as these? or I could do that here?
5. organizing it into two files, (a) my stuff + signing in on scratchr2 and (b) signing in on scratch-www. I did it that way b/c I have to sign in to get to My Stuff …

Fix Gh-1385 - Issue/smoke test signing in

---

src/views/splash/l10n.json
src/views/splash/presentation.jsx
src/views/splash/splash.jsx

This goes along with https://github.com/LLK/scratch-api/pull/292. This can be updated if we choose to migrate the `lovedByFollowing` endpoint off of proxy as well.
* `Projects Shared by Scratchers I'm Following` should load projects when you are signed in on the splash page
* `Projects Loved by Scratchers I'm Following` should load projects when you are signed in on the splash page
* `Projects in Studios I'm Following` should load projects when you are signed in on the splash page
* None of the above rows should load if you are logged out on the splash page

Move custom homepage row to new api endpoints

---

src/components/carousel/legacy-carousel.jsx
src/components/microworld/microworld.jsx
src/views/splash/presentation.jsx

1. Moves carousel to `LegacyCarousel` since it currently is designed to handle JSON from proxy endpoints
2. Add separate `Carousel` endpoint to handle data from project models in scratch’s new api, the standard moving forward.
Fixes an issue with rendering custom homepage rows.

Add new carousel component

---

src/views/splash/splash.jsx

`this.props.user` will now return `true` because there is a default user object that’s empty. So, instead, wait for an actual user object. This is fallout from #1416

key api calls on `username` check

---

src/views/jobs/jobs.jsx

Fixes #1442 by removing the Moderator Position from the Jobs page.
/cc @chrisgarrity @mewtaylor @rschamp @thisandagain

Fix gh-1442: Remove Moderator Position

---

src/views/guidelines/l10n.json

Resolves #1438 
The text at the bottom of the page should now read `Scratch welcomes people of all ages, races, ethnicities, religions, abilities, sexual orientations, and gender identities.` instead of `Scratch welcomes people of all ages, races, ethnicities, religions, sexual orientations, and gender identities.`

Fix gh-1438: Update Community Guidelines

---

src/views/credits/credits.jsx

This fixes #1465 by adding Ellen Daoust to the Moderator section of the Credits page.

Fix gh-1465: Add Ellen Daoust to Credits

---

src/views/credits/credits.jsx

Resolves #1488 
- 'Tracy Tang' should now be added under the list of current ST members
- the avatar for Tracy should be https://cdn.scratch.mit.edu/get_image/user/18417774_170x170.png

Fix gh-1488: Add Tracy Tang to Credits Page

---

src/redux/messages.js
src/views/messages/container.jsx
src/views/messages/message-rows/admin-message.jsx
src/views/messages/message-rows/scratcher-invite.jsx
src/views/messages/messages.scss
src/views/messages/presentation.jsx

This also fixes a bug in which the unread message count remains the same after dismissing an admin message successfully (by reducing the count, not by making another request, in order to reduce back-and-forth with the servers)

Fix GH-1494: fix formatting for dismiss icon, unread message count

---

src/routes.json

Currenlty, some legacy endpoints are failing because they’re being directed to www. A similar thing happened with `/explore`, and this is the same fix

Pass to legacy on message routes with `ajax`

---

src/l10n.json

fixes #1454.
Changes ‘has invited you to join the class:’ sentence fragment to a complete sentence ‘Your teacher has invited you to join a class:’ to account for languages that reverse the  order of subject/object.

Revise student invitation string

---

src/components/navigation/www/navigation.jsx
src/views/messages/container.jsx

Go back to redirecting to splash on logout, and empty messages page too.

Fix GH-1501: handle logout on messages page

---

src/redux/messages.js
src/views/messages/presentation.jsx

This hides the messages counter if there are no unread messages. It also checks for `body` to exist on a clear messages api request before looking for `success` to prevent an extraneous console error.
Fixes #1507 and #1505

Fix GH-[1505, 1507]: hide message counter on 0

---

src/views/tips/l10n-static.json

Resolved GH-1509
- Updated the 'Animate a Name' educator guide link as per instructions in #1509

Changed 'Animate a Name' educator guide link

---

src/components/social-message/social-message.scss

This addresses issues with seeing unread notifications by highlighting them as light blue, along with more opaque icons. 
Here's an example of what it looks like:

[Master] Hotfix: highlight unread message row in light blue

---

src/views/messages/message-rows/forum-topic-post.jsx

Fixes #1526.
Changes the CSS class `.mod-studio-activity` to `.mod-forum-activity` in the forum post message row. (I picked the class name because it's consistent with the `.mod-studio-activity` class; the SVG icon is also named `forum-activity.svg`.)

Fix CSS class of forum post message row

---

src/components/activity/activity.jsx

Fixes an issue where the thumbnail mismatches the username presented.

[Master] Hotfix: use recipient thumbnail, not actor for manager activity

---

src/views/messages/message-rows/studio-activity.jsx

Fixes #1540 by ensuring that the anchor link for studio activity is directed to the activity tab of the studio. Thanks @towerofnix for bringing this over to github from the suggestions forum!

Fix GH-1540: Direct studio activity link to the activity tab

---

src/views/download/download.jsx

Assumptions per discussion with @cwillisf:
- there will be a `pt-br` subdirectory on `/scratchr2/static/sa` for the pt-br specific downloads 
- there will be a `version.xml` file in the pt-br that contains the current version info for the pt-br editor
see #1548

Link to pt-br downloads if locale is pt-br

---

src/lib/jar.js

This should fix #1455 by preventing the path from being changes via opts passed in, even though we don’t pass in a `path` anywhere.

GH-1455: apply path explicitly rather than in `defaults`

---

src/views/messages/container.jsx
src/views/messages/presentation.jsx

This fixes #1545 by adding unread as a key/value on each message during the filtering process. This means the unread count is always applied to the list of full messages, and never to a subset (as was happening before to cause #1545).
(See #1545 for repros)
* Visit your messages page with unread messages. Highlighting should only apply to the top `n` rows on the messages page when the `all activity` filter is chosen
* Choose another filter. If a row is highlighted in `all activity` and is present in that filter too, it should appear highlighted. If a row is not highlighted in `all activity` and is present in that filter too, is should **not** appear highlighted

Fix GH-1545: add `unread` as a key/value on each message

---

CONTRIBUTING.md
README.md

After examining the "CONTRIBUTING" & "README" files, I found several grammar mistakes in them. 
- Fixed "road map" (It should all be one word)
- Adding necessary comma
- Capitalizing "url"
- Fixing "webclient" (Separate words) 
- Capitalizing another word
- Makes the files simpler to read 
- Some sentences make more sense

Fixing some grammar mistakes in markdown files.

---

src/views/messages/l10n.json
src/views/terms/terms.jsx

Typos fixed:
Resolves #1595 - "many not" -> "may not" in Terms of Service
Resolves #1593 - "oops!... this page" -> "Oops!... this page." in `/src/messages/l10n.json`

Fix typos in Terms of Service and Messages l10n

---

src/components/comment/comment.scss

fixes #1568 by imposing a hidden state on overflow text.
* Post a comment that uses "zalgo text" to someone's profile. Then, log in as that user, and look at their messages. The "zalgo text" should not overflow beyond the comment bubble

Fix GH-1568: hide overflow on comment component

---

src/redux/messages.js
src/views/messages/container.jsx
src/views/messages/presentation.jsx

This fixes #1546 by using the new optional `filter` keyword argument that will be added to the messages api endpoint.
* If you change filters, the notifications that show up should only apply to that type of filter
* If you change filters and there are no notifications available for that filter, the load more button shouldn't show up
* If you change filters and there were no notifications of that type in the original list of 40 notifications, you should still see the most recent of that notification type

Fix GH-1546: Use new filters on api endpoint

---

src/views/credits/credits.jsx

I noticed while doing qa for #1616 that @TheGrits avatar was pointing at the default avatar – I changed it to point at `GulpTea`'s avatar instead.

Point at GulpTea’s avatar in credits page

---

src/views/developers/l10n.json

Fixes #1668 by Updating the llk link to:
``https://www.media.mit.edu/groups/lifelong-kindergarten/overview/``

Fix #1668 (Update llk link)

---

src/components/footer/conference/2018/footer.jsx
src/components/navigation/conference/2018/navigation.jsx
src/components/navigation/conference/2018/navigation.scss
src/components/page/conference/2018/page.jsx
src/routes.json
src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/index.scss
src/views/conference/2018/index/l10n.json

Fixes #1633 
Adds the following:
New Copy (italics = instructions not copy):
Title: Scratch Conference 2018: The Next Generation (replaces Scratch Conferences 2017)
Sub-title: July 26-28, 2018 | Cambridge, MA, USA (replaces 'This year, in celebration...')
[Drop the lighter blue banner 'Learn more about conference dates and locations below.']
Join us for the Scratch@MIT conference, a playful gathering of educators, researchers, developers, and other members of the worldwide Scratch community.
We're planning a very participatory conference, with an entire day of hands-on workshops and lots of opportunities for peer-to-peer discussion and collaboration.
[use date and location styling from current site:]
When: July 26-28, 2018 (with opening reception the evening of July 25)
Where: MIT Media …

Fixes #1633 - Scratch Conference 2018 Website Phase 1

---

src/views/jobs/jobs.jsx

Adds:
"Learning Resource Designer, MIT Media Lab, Cambridge, MA" to list of jobs
Link: https://www.media.mit.edu/about/job-opportunities/learning-resources/

Fixes #1674 - Add Learning Resource designer

---

.tx/config
src/components/footer/conference/2018/footer.jsx
src/components/navigation/conference/2018/navigation.jsx
src/components/navigation/conference/2018/navigation.scss
src/components/page/conference/2018/page.jsx
src/routes.json
src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/index.scss
src/views/conference/2018/index/l10n.json
src/views/jobs/jobs.jsx

Includes #1673 (thanks @GreenBayRules) and #1674. A couple of small changes from for the conference page PR include:
* changing back the `routeAlias` for the 2017 and 2018 pages – they need to be consistent with the other conference routes to ensure all routes >=2016 use this repo
* changing the localization to use only `FormattedMessage` – this is meant to be part of the standard which we'll eventually have in #1677 
/cc @chrisgarrity @thisandagain @ChampikaF

[Master] December 1st Hotfix

---

src/components/grid/grid.jsx
src/components/thumbnail/thumbnail.jsx

It also changes some formatting of the jsx, but nothing major. This is mostly for CSEdWeek, to reduce load to our legacy system when we expect increased traffic.
* images on search and explore should still be the same size
* analyze the size of images coming through, if there's any noticeable influence on load time/performance/bandwidth
/cc @thisandagain @colbygk @chrisgarrity

[Master] Hotfix: Change avatar to use `uploads` endpoint

---

.travis.yml
bin/get-localized-urls
package.json

This fixes an issue in compilation by upgrading node-sass to v4.6, and also upgrades express in the process.
Callback added to `writeFile` in `get-localized-urls` in order to avoid a deprecation warning during `make translations`.

Upgrade compatibility to node 8

---

.travis.yml
src/routes.json

Currently deployed for testing.
There was an issue building with the new Travis image, so that is what the `group:` in `.travis.yml` is for.

[Master] Ignore querystring when routing conference page 

---

src/views/splash/presentation.jsx

There appears to have been a merge issue between the hotfixes around CSEdWeek and the implementation of the splash refactor, so this rectifies that error.

[Master] Add back in FPC and recently shared rows

---

src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/l10n.json

Fixes The Changes Requsted In issue #1746 
*/ Add  extra desc   to desc2 `The conference is intended primarily for adults who support young people learning Scratch.` in #L13 <br>
*/ Adding a new section in jsx, a new corresponding section to the l10n file with the Registration opens March 1, 2018. text.
I used NPM start and test, i can't show a screenshot, because my screenshot is not working. I used it today 
(december 23th 2017) and used my freind coumpter, who lives far away from me! )
I used NPM because @thisandagain Told me! :D
[![Build Status](https://travis-ci.org/LLK/scratch-www.svg?branch=develop)](https://travis-ci.org/LLK/scratch-www)

Add Changes to scratch conf website (#1746)

---

src/views/about/l10n.json

Translators can’t translate a string with unbalanced paren’s.

Add a closing paren

---

src/components/forms/select.scss

Fixes the old issue #711.
I don't know why commit 007bb54bf17d62577e85317778db48af4b023656 is in this PR, but it doesn't make any changes.
Quoting the two commit messages:
> Only transition border property since it's the only property which actually animates. (The background image also changes on hover/focus, but that isn't visually effected by transition, so we [don't transition] it.) This is for the next commit. Without this, the focus ring slowly disappears, and the text slowly becomes the color it's meant to be; neither of those are good.
> Hide Firefox focus ring, per [this StackOverflow answer](https://stackoverflow.com/a/18853002/4633828). This isn't a perfect fix - we have to set `color` explicitly, rather than use `inherit`, because we want the text color to be the same when the …

Hide Firefox focus ring on <select> elements (language selector)

---

webpack.config.js

#1684 
This will save *[an alot](http://4.bp.blogspot.com/_D_Z-D2tzi14/S8TRIo4br3I/AAAAAAAACv4/Zh7_GcMlRKo/s1600/ALOT.png)* of bandwidth and parsing time. Also Uglify works much better on code that isn't in strings.
Before:
After:
This should be tagged "performance," but I don't have the permissions to do so.

Don't use eval devtool in production

---

src/components/footer/www/footer.jsx

Issue #1808 
This updates the link to:
https://www.scratchfoundation.org/media-kit/
Instead of:
https://wiki.scratch.mit.edu/wiki/Scratch_Press
I don't think such a tiny change needs to be tested, but I can if necessary.

Fixes #1808 | Updates scratch press link to point to Scratch Foundation Media Kit.

---

src/views/jobs/jobs.jsx

#1825 - Remove filled listings from `/jobs/`
Removed: Designer, Learning Resource Designer, QA Engineer, Senior Backend Engineer

Fix gh-1825: Remove filled jobs

---

src/views/faq/l10n.json

#1842 
At the src/views/faq/l10n.json line 85, Giga is missing.
Giga is trademarked/copyrighted by Scratch Team.
I added Giga to the FAQ.
View FAQ Page

Added Giga

---

.tx/config

the `view/research/l10n.json` configuration was missing from the transifex config, so translations are missing.
An oversight when we moved the research page from scratchr2.

Add research view to transifex config

---

Makefile
package.json
src/routes.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/preview.scss
webpack.config.js

Fixes #1773, and most of #1799 
- `/preview/editor` will load GUI with an empty project
- `/preview/:id/editor` will load GUI with a project from the projects server (not local data)
- `/preview/:id` loads a Scratch 2 project with just the player from GUI
- can switch in/out of full screen mode for both player and editor
- passes intl object to GUI

Initial GUI embed

---

bin/configure-fastly.js
src/routes.json
src/views/preview/preview.jsx

Fastly deploy failure
- use more explicit route
- handle fastly error in the callback correctly
- more succinct parsing of the URL path
Current tests pass

Correct preview route for fastly

---

.tx/config
Makefile
bin/configure-fastly.js
package.json
src/routes.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/preview.scss
webpack.config.js

Make sure develop gets everything that was merged to release.

[Develop] April 2018 Release

---

src/components/news/news.json
src/views/download/download.jsx
src/views/download/l10n.json

Resolves GH-1880
- Removes references to Linux on the `/download` view
- Removes reference to Linux on the default metadata for the `news` component (used for testing)
Removes references to Linux for the Scratch 2.0 Offline Editor. Unfortunately [Adobe stopped supporting Adobe AIR on Linux platforms in 2011](https://helpx.adobe.com/air/kb/install-air-2-64-bit.html). We have continued to provide a version of the Scratch 2.0 Offline Editor since then, but unfortunately more recent versions of Ubuntu and other major distributions of Linux have completely broken AIR compatibility to the point where we need to drop support. Our hope is that the Scratch 3.0 Offline Editor will be able to more sustainably support Linux (via [Electron](https://electronjs.org/)) in the future.

Remove references to Linux for the Scratch 2.0 offline editor

---

test/integration/selenium-helpers.js
test/integration/smoke-testing/test-login-failures.js

All login-failure Selenium tests now pass.  
Make sure that the error messages are visible before getting their text and asserting on that text.
Update the tests to use css selectors to find elements, rather than text of the element.
Relies on https://github.com/LLK/scratch-www/pull/1887

Selenium login failure tests

---

.travis.yml
test/integration/package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test_project_rows.js

Sets up Travis to run Selenium smoke tests on the branch Travis.  This includes modifying the selenium helpers to be able to run headless and adding a stage to Travis to run the tests after it builds.
The tests will currently only run on the Travis build as they fail intermittently and shouldn't run on everything until they pass more consistently.

Run smoke tests with Travis after deployment

---

src/views/search/search.jsx

Resolves #1224 
`decodeURI` will **only** decode escape sequences that could've been added with `encodeURI`.
`decodeURIComponent` will decode everything it can, even if it's just ASCII punctuation encodings.
That means that when you now search for `cats?`, you will then see the feedback saying `cats?` -- and not `cats%3f`, which can be a little confusing.
The below should test everything
All of these manual tests worked.

Fix search bar's handling of special characters

---

src/views/about/about.jsx

#1898 
Changes the link to old Scratch Wiki domain to new one
See the /about/ page

Updated link to Scratch Wiki - to new domain

---

src/views/about/about.jsx

Fixes #1895
Changes the research page link in the /about view from /info/research to /research

Fix the /about research page link

---

src/views/about/about.jsx

#1909
Changed links from /help to /tips (It's moved in July 2017)
See /about page

Changed link from /help to /tips

---

src/routes.json

#1920
Adds the following redirects
* https://scratch.mit.edu/donate → https://secure.donationpay.org/scratchfoundation/
* https://scratch.mit.edu/connect → https://eepurl.com/cws7_f

[Master] Add donate and connect (email list) redirects

---

src/views/splash/splash.jsx

It uses "30000000 projects" by default now!
#1916 
Changed the default value.
It's difficult to test it, because it has to be without api access.

Change splash to use 30000000

---

package.json

Now that GUI deploys "stable" builds to the `latest` tag, we can pin to latest, so rebuilds pull in the latest stable GUI.

Pin scratch-gui to `latest`

---

src/views/teacherregistration/l10n.json

Resolves GH-1929
Fix copy in Teacher Registration error message to match new GDPR policies.

Fix issue with error copy to match new teacher age limit.

---

src/views/preview/preview.scss

This PR resolves #1935.
Firefox implements flexboxes in a way that prevents them from shrinking smaller than their content unless `min-height` is set to 0. This PR adds `min-height: 0` to the `description-block` class to allow the notes and instruction containers to scroll. This change does not affect the behavior on Chrome or Safari.

Fix notes/instructions layout on Firefox 

---

src/init.js

Added `console.log()` calls to be executed on the `window.onload` event, in `init.js`.
Tested on MacOS 10.13.5
Chrome 67.0.3396.87:
Firefox 59.0.2:
Safari 11.1.1:

Fix gh-1899: Add Console Warning

---

package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test_footer_links.js
test/integration/smoke-testing/test_navbar_links.js
test/integration/smoke-testing/test_project_rows.js

Allows Smoke Tests to be run  with SauceLabs.  
Adds a second function for creating a driver so that it uses Sauce Labs and then checks the environment variable SMOKE_REMOTE to determine which type of driver to make.
Also sets up an package.json to have a smoke-sauce script that sets the timeout to be larger.

Setup Selenium tests to be run with Sauce Labs

---

src/views/faq/l10n.json

Changed the age from 13 to 16, as per the issue description.

Fix gh-1950: Update parent email age on FAQ page

---

package.json
test/integration/README.md

Recently the integration tests have been updated to support testing with Sauce Labs.  This updates the README file in the Integration folder to reflect that. 
* New information has been added to the README in the integration folder.  
* Some minor changes to the smoke testing scripts in package.json: 
* None of the smoke tests use Make.  
* Smoke-sauce script now automatically sets the environment variable SMOKE_REMOTE to true.

Update integration readme with Sauce Labs information

---

docker-compose.yml

docker-compose no longer strips `-` from the project name, which makes `scratchapi` now `scratch-api` when referencing the network.
A change introduced by updates to `docker-compose`
Updates the named network when performing local development
N/A

Update to track changes in docker-compose behavior

---

src/_colors.scss
src/components/forms/button.scss
src/components/grid/grid.scss
src/components/informationpage/informationpage.scss
src/components/intro/intro.scss
src/components/spinner/spinner.scss
src/components/thumbnailcolumn/thumbnailcolumn.scss
src/components/welcome/welcome.scss
src/main.scss
src/views/components/components.jsx
src/views/components/components.scss
src/views/conference/2018/schedule/schedule.scss
src/views/download/download.scss
src/views/explore/explore.jsx
src/views/explore/explore.scss
src/views/messages/messages.scss
src/views/messages/presentation.jsx
src/views/preview/preview.scss
src/views/search/search.jsx
src/views/search/search.scss
src/views/studentcompleteregistration/studentcompleteregistration.scss
src/views/studentregistration/studentregistration.scss
src/views/teacherregistration/teacherregistration.scss
src/views/teachers/landing/landing.scss
src/views/teacherwaitingroom/teacherwaitingroom.scss
src/views/wedo2/wedo2.scss

As we launch the Beta version of Scratch 3.0, we would like to update the rest of the Scratch to use more consistent colors and typography. 
- Colors - Uses new 3.0 color palette
- Typography - Removes use of numeric font weights (e.g. font-weight: 400) this caused many rendering issues across browsers
- Buttons - Not more drop shadows (GET OUT OF HERE)
**Navigation**
**Footer**
**Conference**
**Addtional Pages**

Update WWW to unify color and typography with scratch-gui

---

src/routes.json

This PR fixes an issue with the /preview-faq -> /3faq redirect by removing `/?$` from the end of the routeAlias for the preview faq redirect route.

Remove extra characters from preview faq routeAlias

---

src/views/jobs/jobs.jsx

Resolves #1972 
Adds the "Community Moderator" job listing. The location is listed as "Remote".
I tested it *in my miiiiiind*

Added Community Moderator job listing

---

.tx/config

We forgot to remove the conference 2018 l10n file from the tx config when the file was removed. It causes transifex to quit with an error, so research and preview weren’t getting sent to transifex/updated.

remove obsolete tx/config for conference

---

src/components/social-message/social-message.scss

New messages should now have a blue backgroud (like they did previously).
/cc @thisandagain

Fix new message highlight

---

.eslintignore
Makefile
dev-server/index.js
docker-compose.yml

By default, webpack-dev-middleware is supposed to be watching for changes in the local source files, but in practice this seems to not be the case in docker containers, as fsevents are not passed through the NFS mount into a container and it requires explicit polling to enable watching for changes.
This will work in both docker and outside of docker, and tunes the load on a docker container running webpack to not overly burden a local host’s cpu watching for changes. 
#1974 - Docker does not re-compile on changes
This updates `dev-server/index.js` to specify `watchOptions`. These options include a polling interval of 2500ms and aggregate changes in a 500ms window.  See also: https://webpack.js.org/configuration/watch/
N/A

watchOptions required for use in docker environment

---

src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/index.scss

#1812
Updated landing page header to include link to conference livestream (to be deployed on the 25th in prep for the beginning of the conference on the morning of the 26th)

[Master] Conference 2018 Livestream

---

src/views/credits/credits.jsx

Closes #1978 
This adds an entry for Bryce Taylor, just before M. Taylor (since Taylor == Taylor; but B < M)
`npm test` was weird because Windows is weird.
Manually tested by navigating to /info/credits and observing Bryce Taylor's avatar, their name, in the non-moderator category in their correct position.

Add brycedtea to Credits page

---

src/components/footer/www/footer.jsx

Changed link in footer component from https://wiki.scratch.mit.edu to https://en.scratch-wiki.info/

Fix gh-1962: Update footer wiki link

---

src/views/splash/beta/top-banner.scss

This PR fixes an issue on Android Chrome 50 where the text in the top banner was not centered. This was done by adding `left: 0;` and `right: 0;` on the container for the text in the top banner.
**Before:**
**After:**
Tested on Android Chrome 50, macOS Firefox 63, Chrome 68, and Safari 11.1.

[DEVELOP] Fix top banner centering on android chrome

---

src/components/forms/validations.jsx
src/components/modal/addtostudio/modal.scss
src/components/modal/base/modal.scss
src/components/modal/report/modal.jsx
src/components/modal/report/modal.scss
src/l10n.json
src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Resolves #1957.
When tested using Docker, depends on https://github.com/LLK/scratchr2/pull/5133 .
Looks like:
Note that this does NOT use a scratch-api endpoint at all; it just uses the existing scratchr2 endpoint.
We ran into difficulties getting scratch-api to read the cookie from scratch-www, in the process of sending a proxy request from scratch-api to scratchr2. We decided to come back to this at a a later time.
Why setting headers in www doesn’t work:
* Currently can get csrf token from cookie fine; but can’t get sessionid token that way, because it’s set as http only by scratchr2. So it’s unreadable!
Why sending whole cookie from www to api doesn’t work:
* So, it CAN, it’s just tricky.
* To send cookie, you have xhr options include withCredentials: true. That will send cookie.
* …

report project POSTs to scratchr2, displays modal reactively

---

src/views/preview/preview.jsx

This PR is a continuation of llk/scratch-gui#2814.
This PR changes the project page view so it uses the `hideIntro` prop introduced in llk/scratch-gui#2831 to hide the intro modal in the editor.
Tested manually by making sure the intro modal does not show up when clicking "See Inside" on project pages. Tested on macOS Firefox 63, Chrome 70, Safari 11.1.1

Hide intro modal in editor on new project page

---

src/redux/navigation.js
src/views/search/l10n.json
src/views/search/search.jsx
src/views/search/search.scss

Resolves #1252 
> On the explore page, there is a dropdown for the sorting scheme ("Trending", "Popular", "Recent"). This component should be added to the search results page, defaulting to "Popular". Changing the choice should change the sort order of the results.
> The same design on the Explore page should be used for the dropdown, except that the tags should not appear in the row.
This PR adds this dropdown and its functionality, including a new `m` query parameter for filter mode. A new search URL could look like: `/search/projects/?q=cats&m=recent`

Add sort scheme dropdown to search results page

---

src/components/navigation/www/accountnav.jsx
src/components/navigation/www/accountnav.scss
src/components/navigation/www/navigation.jsx
src/components/navigation/www/navigation.scss
src/views/preview/preview.jsx

This is a first step in identifying the account nav menu info and styles that will be needed for replicating the menu for GUI, per  https://github.com/LLK/scratch-gui/issues/2816 .
Note that the component can almost handle its own open/closed state, but the navigation component currently overrides this state when there are updates to she session, and that seemed beyond the scope of this component.

split account nav into its own component, pass logout callback to GUI

---

src/components/navigation/www/navigation.jsx

My commit https://github.com/LLK/scratch-www/commit/3c6530fe859753a3b7b2389659c576e1eaeacfc5 introduced a bug where after the user logs in, the view is not refreshed to reflect the logged in session.
The culprit was the dummy mapDispatchToProps that I introduced (to quiet a js console warning). navigation.jsx was using this.props.dispatch(...) in several places, but the dummy mapDispatchToProps meant that these dispatch calls never went through.
I solved this by making a proper mapDispatchToProps function and putting the dispatched function calls there.
Tested that login and message count fetching work in Mac Chrome.

moved dispatched navigation function calls to mapDispatchToProps

---

src/lib/render.jsx
src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Big help from pairing with @LiFaytheGoblin!
https://github.com/LLK/scratch-gui/issues/2815
(together with PR in GUI)
Passes projectTitle and onUpdateProjectTitle props to GUI component; also disables enter key when editing project title in www.
https://github.com/LLK/scratch-gui/pull/3016 in GUI should be used together with this.

pass project title to GUI, and disable submit when editing title

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss

Part of #1986 
* added a title attribute to project title so you can see the whole title even when it is not completely displayed on the website
* made it so long titles don't get displayed completely, see comments in scss file
Tested in MacOS Chrome & Safari, looks good for screen with min-width 640px

Keep title on preview project page from overflowing or otherwise messing up the layout

---

test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_project_rows.js
test/integration/smoke-testing/test_signing_in_and_out_discuss.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js

resolves broken smoke test from merging https://github.com/LLK/scratch-www/pull/2078
The issue was that the tests were targeting DOM elements by assuming they would *only* have one particular class, rather than allowing them to include that class among several.
Unfortunately, it's not easy to test all of these smoke tests before deploying them to staging, because they depend on seed data and server access that are not easy to replicate locally.

fixed smoke tests to use non-exclusive class locators

---

src/views/search/search.jsx

Resolves #1934 
The text was encoded once already by the search bar. That means we need to decode it twice in order to decode special characters.
?q=cat%3Fcat (should now appear as cat?cat)
?q=cat%20cat (should still appear as cat cat)

Fix gh-1934: Search bar special chars

---

src/views/preview/preview.jsx

Having the `onShare` prop defined to a function enables the button in the GUI

Add placeholder share handler

---

src/components/registration/steps.jsx

Previously, the validation made it so the year Input was invalid. Even though changing the month puts the birth date over 16 years, the form still thinks that the year input is invalid. By changing it to an inline validation we resolve this problem because the check gets called everytime an input is changed.

Fix gh-1930: Teacher registration dates 

---

src/_colors.scss
src/views/preview/comment/comment.scss

#2067 
transparent in safari gets a greyish look. fix is to use a white base and set to 0 opacity.
MacOS, Chrome, Firefox, Safari

Made comments fade out look nice in Safari too

---

src/components/thumbnailcolumn/thumbnailcolumn.scss
src/views/preview/preview.scss

Part of #2086. On mobile the thumbnailcolumns like remixes and studios should appear below comments and also be in a row or so (design not finalized, looking for a meantime-solution here)
MacOS, Chrome

Thumbnailcolumns appear at bottom on mobile

---

src/views/preview/preview.scss

##2132
On mobile, remix credit is still a row so it looks nice and for single line remix credit it looks good because the text is vertically aligned.
MacOS, Chrome, npm test passed

Positioning remix credit text correctly

---

src/views/preview/preview.scss

Part of #2086: According to the design, left and right of page content should be some space on mobile. This is what this pull request does. It will not take full effect unless some of the page content is actually adapted to fit in the page container.
MacOS, Chrome

Make container smaller for mobile to allow for space left and right

---

src/lib/storage.js

Instead of hardcoding the projects server host here, let's use the relevant env.variable if available.

storage.js can use PROJECT_HOST env setting

---

src/components/forms/inplace-input.scss
src/redux/preview.js
src/views/preview/comment/comment.jsx
src/views/preview/comment/comment.scss
src/views/preview/comment/compose-comment.jsx
src/views/preview/comment/top-level-comment.jsx
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

This is a bit of a work-in-progress, but it includes all the major parts of posting comments and replying to comments on the preview page, including
- commenting/replying only visible to logged in users
- comment posting with submitting/rejected states
- seeing newly created comments/replies get added to the thread in the right place
A few things are more WIPy:
- only a few of the more common error responses are ported over, did not look up the messages for all of the possible responses
- needs localization (/cc @chrisgarrity), it already contained a fair number of hard-coded strings, so i'm going to defer this until i talk to chris about how to do it.
I've still got some various cleanup things, but I wanted @rschamp to get a chance to take a look early
Here is a brief demo (although …

Add comments to projects and replies to comments

---

src/_frameless.scss
src/components/modal/addtostudio/modal.scss
src/components/modal/base/modal.scss
src/components/modal/report/modal.scss
src/views/preview/preview.scss
src/views/preview/stats.scss
src/views/preview/subactions.scss

Part of #2133 
The media query variables in various scss files used in the responsive project page have been moved to frameless to keep them consistent accross all files, easier to update, less double code.
Media queries like this are used all over the website tho. Would it make sense to replace them all by the variables from frameless? If so we should make an issue for that.
MacOS, Chrome, npm test passed

Move media queries used in responsive project page to frameless

---

src/components/modal/base/modal.jsx

An issue with react-modal (https://github.com/reactjs/react-modal/issues/697) was causing errors when we passed the prop `bodyOpenClassName` a value of `null`. It works when the value is `undefined` or the prop is omitted.
Now, when we are not setting `bodyOpenClassName` to a custom value, we simply omit the prop entirely.

fix modal prop

---

src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/preview.scss

This uses the project update route using `comments_allowed` as a boolean property. This requires https://github.com/LLK/scratch-api/pull/590
For testing:
- As the project owner, you should see the comment toggling checkbox. When it is toggled, it should show the "sorry comments disabled" and should remain that way when the project is refreshed.
- If you are not the project owner, you should not see the toggle, but should see the "sorry comments disabled" message

Add comment toggling for the preview page

---

src/components/modal/comments/delete-comment.jsx
src/components/modal/comments/modal.scss
src/components/modal/comments/report-comment.jsx
src/l10n.json
src/redux/preview.js
src/views/preview/comment/comment.jsx
src/views/preview/comment/comment.scss
src/views/preview/comment/compose-comment.jsx
src/views/preview/comment/top-level-comment.jsx
src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

This PR implements the following:
- Fix the "delete" action for nested comments (first commit)
- Include a confirmation modal for deleting comments, that allows you to report instead
- Add action for reporting comments, including a confirmation modal
- Fix proptype warnings from previous PR
Some of the finer details about the report/delete flow are not yet implemented, e.g. whether the comments are removed instantly, having different text in the report modal depending on project ownership... I will come back to these in a later design pass.
Also /cc @chrisgarrity, introduced some new strings for these modals, tried to follow the other modal string conventions

Comment report action and modal flow for deleting

---

src/components/forms/select.scss

Resolves #1643
Fixes the text slicing in the select menu of the Messages section. Potential reason can be due to different indentation spacing/styles across different browsers. This PR changes the text-indent property to left-padding potentially fixing it for all the browsers (Chrome, IE and Mozilla tested)
Chrome (Desktop):
Chrome (Mobile):
Firefox(Desktop):
Firefox(Mobile):
IE (Desktop):
IE (Responsive):

Fix Select Menu in Messages Section

---

src/views/search/search.jsx

Because query terms only sometimes need to be decoded, we attempt URI decoding and silence the error if it fails. This lets us still search with queries like `cat%25cat` when we want to, but now falls back to no-decoding when an invalid string is presented (e.g. `100%pen`).

Fix gh-2160: Search with %

---

src/components/dropdown/dropdown.scss

Resolves https://github.com/LLK/scratch-www/issues/1318
Maintains status of closed issue https://github.com/LLK/scratch-www/issues/1292
Note: hard to test on mobile widths because of https://github.com/LLK/scratch-www/issues/2180
Before: 
After:
Before: 
After:
(Note: this is slightly wider, and uglier, than a username this width would previously have)
Before and after, unchanged:

made account menu have min-width, changed max-width to rem from px

---

src/redux/preview.js
src/views/preview/preview.jsx

/cc @benjiwheeler @colbygk this PR moves the last request from preview that was hitting `/site-api` directly to hitting the correct proxy route. I also added the token so that the API accepts the request, and I think because of fixes colby made to `/proxy` it now goes through correctly. This worked on my local setup, but once it is deployed we should just double check that it works on staging (i don't see why it wouldn't, but these proxy routes are finnicky. 
/cc @rschamp This closes the card we discussed today about "API used for all proxy routes"

Use the proper API route for reporting projects

---

src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/share-banner.jsx
src/views/preview/share-banner.scss

Sorry to steal this one from you @benjiwheeler!
Three things:
- Use `projectInfo.is_published` to tell if a project is published. Using the share time does not work if the project was subsequently unshared...
- Wire up the share button to update the published status through the API
- Move strings over to preview l10n file
One thing that is funky is that the API changes the `isPublished` attribute in the db to `is_published` when responding. But you still need to use `isPublished` to update through the API... /cc @colbygk not so happy about this...

Make share banner work on preview

---

src/views/preview/comment/comment.jsx
src/views/preview/comment/top-level-comment.jsx

Prefix comment content with `@username` that links to that users profile
The only thing I'm uncertain about is whether the API should take care of naming the parent username, but I figured since the TopLevelComment component has all the necessary information to do it, it might as well. I think moving this to the API would make it more resilient to loading non-sequential sub-slices of replies, or other situations where you might not have the entire thread.
The second commit also makes the comment use the EmojiText component for showing the content, which is unrelated, but it should have been doing it from the beginning so that the API can emojify the comment content (the way it already is doing for comment notifications).

Show the username of the parent comment in replies

---

src/views/preview/presentation.jsx

This fixes an issue where a project with one top-level comment and one reply would should the "Load more" button at the bottom, even though there were no more to load
On develop
With this fix

Use top level + replies count to control "Load More" comments button

---

src/views/preview/comment/comment.jsx
src/views/preview/comment/top-level-comment.jsx

This PR will show the staff * next to staff usernames on comments, once that information starts coming from the API on comments.

Add * to comments from staff on preview

---

src/components/thumbnail/thumbnail.scss

Resolves #1191
Japanese characters in the title were increasing the height of the line by 4 pixels. As mentioned the line-height has been changed from 'normal' to 1.2em. This has fixed the alignment issues.
Before Fix:
After Fix:
Tested in browsers : Chrome, Mozilla and IE
Mozilla:
IE:

Japanese Character Fix

---

src/components/modal/addtostudio/container.jsx
src/views/preview/add-to-studio.jsx
src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/subactions.jsx

Fixes https://github.com/LLK/scratch-www/issues/2209
There was a performance problem because of returning a new array for consolidatedStudios, which was causing the page to rerender constantly. Instead, move the logic into a connected container for `AddToStudioModal`, and only render the modal if it is visible, ensuring these updates only happen when the modal is open. 
An alternative solution would be to memoize the result of `consolidateStudios`, but it felt better to extract that logic into its own place and fix the issues with rendering invisible modals. 
/cc @rschamp @benjiwheeler 
ps a good way to see that this fixes the issue, beside FPS, is to use the `Highlight Updates` option in the React dev tools (under the gear at the top right). It is like the highlight paint in the chrome …

Connect the consolidated studio data directly

---

src/redux/preview.js
src/views/preview/preview.jsx

Wait to merge until https://github.com/LLK/scratch-gui/issues/3391 is merged
* Sets and provides props to gui:
* canSave: now also true when user is logged in and project page is showing default project
* enableCommunity: instead of always enabling, only enable when the project actually has a project/community page
* Can reset project page state to reflect change in which project is showing]
* updates url when gui calls back with new project id

Pass to and receive from GUI info about project creation lifecycle; handle url changes

---

src/views/preview/comment/comment.jsx
src/views/preview/comment/compose-comment.jsx
src/views/preview/comment/top-level-comment.jsx

This resolves an issue on the preview page where the parent_id was being set to the comment being replied to, instead of what it should be, the top-level parent comment. The commentee_id was being left out, it needs to be the id of the user the comment is directed at, possibly different from the top-level parent comment author.
This PR also changes the auto `@` tagging to use the commentee_id instead of the parent_id for finding the username to show. The logic of that function remains very similar though, it just builds the cache from the author.id instead of comment.id.

Use parent_id and commentee_id correctly when posting comments.

---

src/views/preview/preview.jsx

Fixes #2172 (along with https://github.com/LLK/scratch-gui/pull/3431)
* Initialize `locales` in redux using methods exported by GUI.
* pass GUI method to set the `scratchlanguage` cookie
NOTE: The  does not reload the page, so switching back to the project page will not reflect language changes made in gui until the next page reload. Reloading the page will lose project state so we don’t want to do that.

Integrate www-gui localization

---

src/redux/preview.js

/cc @colbygk this updates the existing comment routes to match the updates we made yesterday.
I haven't introduced the single comment view, so there is no single comment endpoint to update, just the top level comments and replies routes.

Update the comment routes

---

src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Show the load more comments button any time the last comment page was filled to the requested limit. As noted in the comment, this heuristic will be wrong at most 5% of the time but the failure mode (showing load more which, when clicked doesn't load any more, just goes away) is very mild, and for the overwhelming majority of project views that happen on projects with many, many comments, this is very unlikely to ever be noticed. It obviously isn't a perfect solution, but I cannot think of another that does not need the server to do another query to find out the total number of visible comments, or to find out if there are more comments after the requested offset+limit.
After talking it over with @colbygk, I think this is the best way to avoid adding extra pagination logic to the comments …

Do not rely on total comment number for load more functionality

---

src/redux/preview.js
src/views/preview/comment/comment.jsx
src/views/preview/comment/comment.scss
src/views/preview/comment/top-level-comment.jsx
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

This PR enables loading a single comment into view by the existing URL hash scheme (#comment-<id>). The functionality is different from 2.0 project page because it does not load up all comments page-by-page until it finds the right one. Instead, it loads the requested comment specifically. If the comment is a top-level comment, it is shown and replies are loaded. If the requested comment is a reply, the associated top-level comment is loaded and shown, then the replies are loaded. In either case, the requested comment is highlighted and then scrolled into view.
/cc @chrisgarrity because you were mentioning URL schemes, this is one that has to be maintained because other parts of the app are generating links (comment reports, notifications).
We discussed adding a button to "go back" to …

Showing specific comment by url hash on preview

---

src/views/preview/comment/comment.scss
src/views/preview/comment/compose-comment.jsx
src/views/preview/presentation.jsx

Having Formsy around the entire page was causing re-renders to happen when you typed into an input, when really just that component needed to re-render.
You can compare the rerenders by turning on "Highlight Updates" in the react dev tools:
Fixed

Keep each input in its own formsy wrapper to improve performance

---

src/lib/decorate-text.jsx
src/views/preview/comment/comment.jsx
src/views/preview/presentation.jsx

Implements the feature for converting scratch domain links and @usernames to /users/username links in the comments.
I did this by enhancing the `decorateText` helper to optionally convert scratch domain link text to react links. There was an issue in the documentation for decorateText, which was actually returning an array, not a string. For comments, each element of the resulting array is either rendered directly if it is a component (i.e. link) or put inside `<EmojiText ...>` since it may already contain an imageified emoji (handled by the server). 
This code also makes more explicit what kind of conversions we expect in each part of the app, since you have to pass an object of flags indicating what you want.

Decorate comment text to add @username links and scratch-domain links

---

src/views/preview/preview.jsx

Resolves https://github.com/LLK/scratch-www/issues/2216
* moves getExtensions call out of Preview constructor, where it causes a warning because it attempt to setState before Preview is constructed
* moves the other getExtensions call out of a place in the code where it doesn't fit -- it was waiting for projectInfo to be fetched, when it doesn't need projectInfo, just projectId

moved getExtensions out of constructor, and out of projectInfo response

---

src/views/preview/preview.jsx

Helps resolve https://github.com/LLK/scratch-gui/issues/3466
passes isShared prop to gui, so gui can decide how to reflect the project's being shared or not
https://github.com/LLK/scratch-gui/pull/3508 depends on this, but this does not depend on it, and can be merged before it

pass isShared to gui

---

src/views/preview/comment/comment.jsx
src/views/preview/preview.jsx

Fix a typo with the url anchor for comments

Use #comments-id instead of #comment-id for fetching single comments

---

package.json

Previously, we chose to track scratch-gui@develop instead of @latest: https://github.com/LLK/scratch-www/pull/2119
The reason then was "The lag between releases for scratch-gui@latest hinders testing scratch-gui/www integration changes"... which is true!
But right now, we want to specifically test the latest release build of gui in staging.
We should revisit this question soon.

Track scratch-gui@latest 

---

src/views/preview/preview.scss

Preview doesn’t need to set a z-index (the first version was trying to overlay gui on top of the project view).
resolves #2030

remove obsolete code

---

src/views/preview/share-banner.scss

https://github.com/LLK/scratch-www/issues/2248
Comments out css that put a placeholder icon in the Share button.
I'm keeping the code there because we will probably put an icon in there soon.
Before: 
After:

removed erroneous share button icon

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Resolves https://github.com/LLK/scratch-www/issues/2273
passes `canShare` boolean prop to preview presentation, which uses it to show or hide the share banner accordingly.

make share banner appear only if user has the power to share this project

---

src/views/splash/l10n.json

Adding the text that will be used in the Hour of Code banner so translators can get started translating before the code changes are ready.
For reference see #2280

Add new strings in preparation for Hour of Code

---

src/l10n.json
src/views/preview/comment/compose-comment.jsx

Enhances the error message for preview page comments in the case of IP Mute to include showing an appeal case ID. This PR expects that info to be included with the `{rejected: 'IPMuted'}` response from API in a key called `appealId`. This PR is safe to merge before the API is in place, just will show a blank case number.

Add IP Mute message to project comment errors

---

test/integration/package.json
test/integration/selenium-helpers.js

test_footer_links tests were failing due to a problem in the version of chromedriver. 
Updates the package.json in test/integration to include the latest and working version of chromedriver.
`SMOKE_USERNAME=[username] SMOKE_PASSWORD_[password] npm run smoke` passing in a valid staging username and password.  The tests should now pass.

Update chromedriver so tests pass more reliably

---

src/views/splash/splash.jsx

This situation probably occurs most frequently when running dev servers while offline, but could also happen if the API is having issues. 500 responses from the API should not take down the homepage so drastically, and are also sometimes unavoidable while working offline.

Avoid displaying an error when /news returns a 500

---

package.json

See: https://github.com/LLK/scratch-www/pull/2241 , https://github.com/LLK/scratch-www/pull/2276
We want to specifically test the `latest` release build of gui in staging. Not the `develop` release build, which changes out of step with this branch.
We don't intend this change to be merged back into the www `develop` branch; or if it is, we would have to revert or otherwise reverse it.

point to scratch-gui latest npm release, not develop

---

src/components/footer/conference/2016/footer.jsx
src/components/footer/conference/2017/footer.jsx
src/components/footer/conference/2018/footer.jsx
src/components/footer/www/footer.jsx
test/integration-cypress/cypress/smoke-tests/test-footer-links.js
test/integration/smoke-testing/test_footer_links.js

Resolves #2297 
This changes all the links to Scratch Jr from http to https.
I don't understand much about testing yet (I use testing for my other node modules of course), but I ran `npm test` and everything passed. 
I also checked the pages and made sure that the links went to https://scratchjr.org.

Use https for ScratchJR links

---

src/views/microbit/microbit.jsx

Update the download link for the microbit hex file to version 1.1.0. This version provides support for an incremental update to the microbit hardware.

Update microbit hex file version

---

src/routes.json

The translation generation script uses the view name from the routes file when generating the translations files. So the route `name:` and `view:` must match.
Symptom: when generating translations there were warnings that there were no translations for `wedo-legacy`.
Changes the wedo2-legacy route name to match the view. (not the route pattern which is still `wedo-legacy`)
On fastly this should change the name of the `rewrites/wedo-legacy` header to `rewrites/wedo2-legacy`, and it will change the filename from `wedo-legacy.html` to `wedo2-legacy.html`. However the URL `/wedo-legacy` should not change.
@rschamp do we have a way to 'test' what gets generated on fastly other than looking on staging?
/cc FYI @benjiwheeler

Fix wedo-legacy translations

---

test/unit/redux/preview-test.js

There is some non-trivial logic in the preview reducer, and I was getting a bit anxious about it being uncovered by tests. This just adds a unit test covering some of the trickier reducer stuff. 
Covers stuff like:
- replies get added to the end, but top level comments get added to the beginning
- `projectNotAvailable` gets toggled by setting null project info
- addNewComment, setCommentDeleted/Reported can act on both top level comments and replies, but use different code paths to accomplish that.

Add a unit test covering the trickier parts of the preview reducer

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/preview.scss
src/views/preview/subactions.scss

Should be checked in *after* gui counterpart: https://github.com/LLK/scratch-gui/pull/3826
- Resolves https://github.com/LLK/scratch-www/issues/2283
* improves css of see inside button; introduces remix button on project page
* enables remix button and connects it to gui player
none yet

enable remix button; format remix, see inside button css

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Fixes https://github.com/LLK/scratch-www/issues/1873 by promoting the NotAvailable component above the editor/project page switch. 
This fixes the issue where going to /editor would still load the editor, even if the project was unshared.

Show projectNotAvailable view in editor mode also

---

src/l10n.json
src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

This visually appears like a "load more comments" button for now, but has the impact of unsetting the #comments-<id> hash in the url and resetting the comment state, showing all the comments (in paginated view)
To test locally: 
- load a project with a comment id in the url, locally with the seed data you could use `/preview/12#comments-10`
- click the "see all comments button"
- see that the comments are now loaded chronologically, and you get the top level comment form back
*Note: I changed comments-16 to comments-10 above; my local data didn't have 16* - @benjiwheeler

Allow user to exit "single comment mode" and see all comments.

---

src/routes.json
src/views/preview/preview.jsx
src/views/preview/remix-credit.jsx

Redefines the `/preview...` route to `/projects...` in preparation for January.
Note: this does not rename the preview view, resources etc. as there are too many people working on them. I will open a new tech dept issue to track that.
Manual tests:

Rename /preview to /projects

---

src/views/preview/preview.jsx

- Resolves https://github.com/LLK/scratch-www/issues/2095
Before www preview page renders or components mount, check if the page's url hash matches `#editor` or `#fullscreen`. If so, replace that hash tag with the equivalent path. Maintain querystring, protocol, etc.
Note: not IE-safe because we use `window.location.origin`. Is that bad? Will we show IE is unsupported earlier?
NEED TO WRITE TESTS

redirect hash urls to url pathnames

---

src/routes.json

Duplicate tutorial shortcuts previously handled by scratchr2.
Left out routeAlias as that is no longer needed.
#2270 
Tested locally, but that only tests the local routes.
Tutorial shortcuts and aliases should redirect as documented in the [Tutorial Redirect spreadsheet](https://docs.google.com/spreadsheets/d/1HjMSBWMLR_rH0-z4ZqWpmos2FSEtmSjNQzScerxNhx8/edit?usp=sharing).

Tutorial shortcut redirects

---

src/views/preview/comment/comment.jsx
src/views/preview/comment/comment.scss

Resolves two minor issues with comments
1. The actions (delete/report/restore) should only show on hover, that just had gone unimplemented. /cc @kathymakes the hover target is the entire comment
2. There was an incorrect translation string for reporting comments, causing this

Show comment actions on hover and fix report translation

---

test/integration/selenium-helpers.js
test/integration/smoke-testing/test-my-stuff.js

The www tests failing on scratch.ly
explicitly requires chromedriver in the helper file, without which sometimes the tests wouldn't run.
Changes an expected url in the See Inside test under "test-my-stuff" so that that test passes.
There was another test in the "test_navbar_links" tests that was failing.  I changed some things but then put them back the way they were and now they pass.  I'm not sure what caused the failure yet and we should keep an eye out for it in the future.

Get integration tests to pass after preview to project change

---

src/l10n.json
src/views/preview/unsupported-browser.jsx

Fixes #2352 
- Header reads ‘This browser is not supported’
- FAQ link goes to general Scratch FAQ.
Current tests run.

Revised unsupported browser info

---

src/views/splash/presentation.jsx

Switch `&&` to `||`. Current date before AND after HoC is never true.

[Master] show intro for logged out users

---

src/redux/preview.js
src/views/preview/project-view.jsx

Add an action that uses the existing infrastructure for storing project thumbnails. As discussed with @rschamp, we don't want to move this to the API and proxy it because it probably will not live permanently in the API. 
This is a bit tough to test locally without the project thumbnail upload infrastructure, but I checked the request against the request made when saving project thumbnails in scratch2 and they seem to match (bare PNG in the body, content-type image/png, x-csrftoken and cookies sent). 
Also we discussed putting this entirely in GUI and having storage manage it, but there are a few reasons that were convincing to me not to do that: 
- The stuff needed to make the request work with existing infrastructure (cookies, csrf, internalapi route) is already being handled in www.
- …

Add project thumbnail update action to pass into GUI

---

src/views/microworld/fashion/fashion.json
src/views/microworld/hiphop/hiphop.json

Resolves #998.
Firefox and IE are not able to load the WebP image on the hip-hop page. Changing the extension of the image from .webp to .png fixes the problem. Not sure if this the desired solution, Firefox is currently incorporating WebP support.
Firefox before fix:
Firefox after fix:
Edge after fix:

Thumbnail Fix

---

package.json

This was accidentally changed to "latest" when the merge from @rschamp's latest hotfix to master was made.

Point scratch-gui dependency back to develop tag

---

src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Track isScratcher status and pass info to gui about whether the user has permission to use cloud variables.
LLK/scratch-gui#3931
Manually tested along with LLK/scratch-gui#3931

Track isScratcher status and pass hasCloudPermission flag to gui.

---

src/routes.json

fixes #2364
Add `/bird` and `/makeitfly` as redirects to the tips page. `makeitfly` is an alias for `fly`
Manual testing:

Add missing tutorial shortcuts

---

src/views/preview/project-view.jsx

Fixes an issue where the information related to the project JSON (i.e. moderation data and extension data) would be out of date if you went "see inside" -> add extension -> "see community". The data needs to be re-fetched when switching back from editor mode.
Originally mentioned by @ericrosenbaum

Refresh the data related to the project json on switch back from editor

---

src/redux/preview.js

One of the weird behaviors identified in the issue https://github.com/LLK/scratch-api/issues/638 is that currently, if you edit project metadata on a censored project, the project disappears:
That's because we're only checking for status code == 500, and so we are acting in the code like status code === 404 is valid, and setting the project metadata to the response body (which is empty)

project page will no longer vanish when project metadata update fails on the backend

---

src/views/preview/project-view.jsx

`/projects` without an id or `editor` should just show a 404.
Fixes #2306 
Checks URL, and just shows NotAvailable if nothing other than `/projects` is given.
Manual Testing:

Show NotAvailable for invalid URL

---

src/views/preview/project-view.jsx

Admins should see the "this project is not shared" message if the project is not shared. Right now, they cannot.
Fixes https://github.com/LLK/scratch-www/issues/2400

Allow admins to see share banner

---

src/components/adminpanel/adminpanel.jsx
src/components/adminpanel/adminpanel.scss
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx
src/views/splash/presentation.jsx
src/views/splash/splash.scss

~~Just in case we don't do anything else,~~ _As was the plan_, this "proxies" a standalone admin panel onto the new project page in an iframe.
~~Requires https://github.com/LLK/scratchr2/pull/5219 to work.~~ (merged!)
Requires https://github.com/LLK/scratchr2/pull/5220 to work.
This re-arranges some styles in the existing admin panel on the homepage so it can be re-used on the project page.
Then, listen for events (added in the PR above) that tell us when a modal is opened or closed in the iframe'd page and expand the panel and iframe accordingly so we can see/hide the rest of the page to interact with the modal.

Admin panel for the project page

---

src/components/extension-landing/extension-landing.scss
src/components/extension-landing/extension-video.jsx
src/views/ev3/ev3.jsx
src/views/wedo2/wedo2.jsx

Resolves https://github.com/LLK/scratch-www/issues/2402
Add a video player component to the extension landing pages for WeDo and EV3 that displays a wistia video.
Thanks to the resources team for the awesome videos!

Add videos to WeDo and EV3 landing pages

---

bin/configure-fastly.js
src/routes.json
src/views/preview/project-view.jsx

Fixes #2388 
* detect `embed` in the URL
* initialize GUI in embed mode if detected
* match `embed` in the project page route
* add fastly config rules to redirect `/projects/embed/:id` to `/projects/:id/embed`
Manual Testing:
Post Deploy testing:

show embed view

---

src/views/preview/presentation.jsx

Because it doesn't work until the project has changed, it is a little misleading and shouldn't be so big. The functionality needs reconsidering.

Remove share button on censored project banner.

---

src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Part of resolving https://github.com/LLK/scratch-www/issues/1858
relies on https://github.com/LLK/scratch-gui/pull/3981 and https://github.com/LLK/scratch-api/pull/650
Passes a function callback to GUI, for it to call when green flag clicked. When handling this callback, post to the API endpoint responsible for registering project views.

pass onGreenFlag to GUI; when called, call API to register project view

---

src/views/preview/subactions.jsx

It is set to empty string elsewhere when the value does not exist, not null.

Use falsey check for shareDate instead of checking for null.

---

src/views/preview/project-view.jsx

Resolves #2072, an alternative to https://github.com/LLK/scratch-www/pull/2428
Only try to call the fave/heart handler functions if the network is not in the process of making a fave/heart request. This should make it so that you cannot submit a fave if a fave submission is in progress.

Only try to update fave counts if there are no requests in progress.

---

src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

smoketest issue
Handle moderator information for sb2 projects
Manual testing:
- sb3 projects show correct number of sprites and # of top blocks
- sb2 projects show correct number of sprites and hat blocks
- sb1 projects show zero for both.

Add moderator info for sb2 projects

---

src/lib/project-info.js

Fixes an issue where 3.0 projects arent showing their extensions.
@kchadha this was just a typo in our PR.

Actually return the mapping of extension info

---

package.json
src/views/preview/meta.jsx
src/views/preview/project-view.jsx

Note this _will not_ work until the page uses a template that does not include these meta tags. That is because react-helmet does not override any existing info in the head.
Thus, this was tested by removing that info from the template and seeing it work, then putting the template back.
This will be part of https://github.com/LLK/scratch-www/issues/2354, but again, it depends on being rendered into a template that does not already use those metatags /cc @rschamp

Use custom meta tag info for project page.

---

src/redux/preview.js
src/views/preview/remix-credit.jsx

Resolves https://github.com/LLK/scratch-www/issues/2201
Checks for return values from API indicating that the parent project (of a remix) or original project (in the remix tree) was not found, which is usually because it was unshared.
Checks in `remix-credit.jsx` to make sure parent or original info object has needed fields before assuming that they are there.
None

if remix parent or original is unshared, don't crash project page

---

src/views/preview/presentation.jsx

Resolves https://github.com/LLK/scratch-www/issues/2458
Changes the `<FlexRow>` element that wraps the instructions and credits sections on the project page into a <div> instead, so it won't use the `flex-row` class, so it won't use the `flex-wrap: wrap` property, which can make the "instructions" and "notes and credits" wrap

don't use flex-row class to wrap instructions and credits

---

src/routes.json
src/template.ejs
webpack.config.js

Resolves https://github.com/LLK/scratch-www/issues/2354 by allowing routes to declare `dynamicMetaTags: true`, in which case we do not render the default meta information, allowing the dynamic ones to take over.
@rschamp I know we mentioned using a separate template, but I didn't want to duplicate some of the things that are shared, like favicon, google site verification, etc, so I did it as a flag.

Add flag for dynamic meta tags in the template

---

src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Resolves https://github.com/LLK/scratch-www/issues/2484 
(together with https://github.com/LLK/scratch-gui/pull/4111 , but the two do not depend on each other)
Passes onUpdateProjectThumbnail function prop to `PreviewPresentation` and from there to `GUI`, so that the project page player has access to it (not just in editor view).
none

pass onUpdateProjectThumbnail to gui when on project page

---

src/views/preview/project-view.jsx

Second try at resolving https://github.com/LLK/scratch-gui/issues/3995
Instead of changing gui, we just pass a different capability property to gui if it is in editor mode. This makes it so that in editor mode, the user can edit the title iff:
* they can edit and save the project in general; AND
* they own the project, OR
* they are NOT an admin.
Thus, regular users can edit the project title iff:
* they can edit and save the project in general
Admins can edit the project title iff:
* they own the project
None

admins should not see editable project title in editor

---

src/views/preview/project-view.jsx

Resolves https://github.com/LLK/scratch-www/issues/2339
As soon as remix is done on project page, calls the same code that clicking the See inside button calls.
Note that the UX is kind of fiddly because so much react state changes so many times before it all settles
None.

switch to editor after remixing from project page

---

src/views/preview/project-view.jsx

This makes it feel snappier to start the remixing project because it does not wait for the GUI to notify

Set isRemixing to true and then start remixing process

---

test/integration/smoke-testing/test_footer_links.js

Smoke tests have been failing as the credits link in the footer now lands on `/credits` instead of `/info/credits`
Smoke tests should pass

Credits link has changed

---

src/views/preview/studio-list.jsx

Resolves an issue that @BryceLTaylor found this morning where the project page was linking to `/studio/:id` instead of `/studios/:id`
Fixes the "itemType" property which is used to create the URL for the links.

Fix the studio links to use the correct URL

---

src/views/preview/preview.scss

/cc @rschamp @thisandagain 
Bring in the min sizes from the [GUI playground](https://github.com/LLK/scratch-gui/blob/develop/src/playground/index.css#L9-L11) to allow for scrollable UI. I double checked that this is the correct class used in the editor view and not used in the regular project page view.

Bring in the min sizes for GUI to allow scrollable UI

---

package.json

This will enable us to have more confidence/control over updates to scratch-gui, be able to test updates individually and allow us to rollback if needed.

Pin to a specific version of scratch-gui

---

src/views/preview/stats.jsx

Removes the `CappedNumber` component from the view count on the project page as per feedback from the community.

[Develop] Remove "CappedNumber" from view count on project page.

---

src/routes.json

Resolves:
Third party websites include extra query parameters to, `/faq`, `/download`. Will need to land this and/or make updates to CDN configuration if not landed before release.
Changes:
Fixes issue with correctly routing in CDN.
Test Coverage:
N/A

[Develop] fix downloads 3faq routes

---

src/routes.json

Third party websites include extra query parameters to `/faq`, `/download`. Will need to land this and/or make updates to CDN configuration if not landed before release.
Fixes issue with correctly routing in CDN.
N/A

[RELEASE] fix downloads 3faq routes

---

src/routes.json

Fixes the change introduced https://github.com/LLK/scratch-www/pull/2552 to make sure that we are matching query params instead of sub routes.
/cc @rschamp @thisandagain

Fix the regexp that allows for query params on faq and download

---

src/views/preview/project-view.jsx

Fixes an issue where every time you click the green flag a POST is made against the API. only do that once per session.
/cc @rschamp, tested locally.

Only track green flag once per session

---

src/views/splash/presentation.jsx
src/views/splash/splash.jsx

Fixes an issue where we were making an API request from the homepage that was not needed.
/cc @thisandagain

Remove the project count request since it is no longer being used

---

src/views/preview/presentation.jsx

Resolves https://github.com/LLK/scratch-www/issues/1938
On the project page, conditionally shows project instructions, and project notes&credits. If both have text, both will show, taking up half the height. If either one is empty, it will hide, allowing the other to occupy all of the vertical space, UNLESS both are blank, in which case they both display normally.
This behavior was cleared with the mods.
(Note that admins will always see both fields, as in 2.0.)
Examples of new behavior:
Both empty:
Empty instructions, non-empty notes&credits:
Empty notes&credits, non-empty instructions:
Both non-empty:

collapse empty project instructions or notes and credits

---

src/l10n.json

Fixes #2572 
Changes the word from "url" to "URL." (aka capitalization)

Capitalize URL

---

src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/remix-list.jsx
src/views/preview/studio-list.jsx

Resolves https://github.com/LLK/scratch-www/issues/2584
Adds a "View all" link at the top of the list of remixes on the project page
On Safari:
On Chrome:
/cc: @carljbowman @kathymakes

[Master] Show link to view all remixes on project page

---

src/views/preview/presentation.jsx

check whether project is shared before showing comment form
manual testing:

Disallow comments on unshared projects

---

src/l10n.json
src/lib/api.js
src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

Resolves https://github.com/LLK/scratch-www/issues/2614 (together with API proxy addition to address https://github.com/LLK/scratch-api/issues/696 )
* introduce new `setLovedStatusViaProxy` and `setFavedStatusViaProxy` functions to use the new API proxy endpoints
* use `X-Requested-With` header with value `XMLHttpRequest` in these api queries, so that scratchr2 receives the correct headers in the proxy request from -api

[MASTER] love and favorite proxy, and use x-requested-with header

---

src/views/preview/project-view.jsx

Following the advice at the bottom of https://github.com/getsentry/sentry-javascript/pull/1050
/cc @rschamp it isn't as easy as I was hoping...

Disable global error handling for sentry

---

src/lib/supported-browser.js

Only reject IE, other gui errors should get handled by error boundary in gui.

Revise unsupported browser

---

src/views/preview/project-view.jsx

For real this time. Just needed to figure out the right plugins to filter. TryCatch plugin is the one that reports errors from setTimeouts, which the VM executes code in.
Remove the previous window.onerror kludge, it was not working and prevented errors from reaching the console.
Tested locally by providing the staging DSN for Sentry
/cc @rschamp

Prevent uncaught errors from going to sentry

---

package.json
src/views/preview/project-view.jsx

Override window.onerror to prevent sending so many errors. I will test this when it builds on staging, but I wanted to have the PR ready!

[MASTER] Deploy sentry fix to stop noisy errors

---

src/views/faq/l10n.json

Resolves #2643 
Changes the supported version from 62+ to 63+

Change Mobile Chrome supported ver to 63+

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

Fixes #2628 
The project page gets into a bad state if you try to remix a project before it is fully loaded. This PR disables the remix button until the project is loaded.
Depends on https://github.com/LLK/scratch-gui/pull/4312
Adds new `isProjectLoaded` state to the project view, and disables the remix button until the project is loaded. Passes new callback to gui to be notified when the project is loaded.
A side benefit is that the remix button is also disabled while a project is remixing

Don’t allow remixing if the project is not loaded

---

package.json

bump gui version so that scratch-gui #4319 can land (resolve name conflict in project-fetcher-hoc)

bump gui version so that scratch-gui #4319

---

src/components/navigation/base/navigation.scss
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

Resolves LLK/scratch-gui#4230
Changes the z-index to 99.
According to my research, 99 is the best value for this - navbar should be under modal overlay (like reporting), which has `z-index:100;`.
Confirmed working with Firefox 64's inspector
NOTE: It might not work for Account Settings in editor.

Raise z-index of navbar

---

test/integration/smoke-testing/test_footer_links.js

Wiki link test was failing/flaky. The wiki page is not maintained by the Scratch Team, so this test is likely to fail periodically due to circumstances out of our control.  We are also testing this with Pingdom.
Removes the test.

Remove Scratch Wiki test from integration tests

---

src/components/modal/addtostudio/modal.scss
src/components/modal/addtostudio/presentation.jsx
src/components/modal/addtostudio/studio-button.jsx
src/views/preview/add-to-studio.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
src/views/preview/subactions.jsx

Relies on https://github.com/LLK/scratch-api/pull/712 
With https://github.com/LLK/scratch-api/pull/712 , resolves https://github.com/LLK/scratch-www/issues/2539 .
uses user status (as owner of a studio, as owner of a project) and studio type (open to all, or privately curated) to enable or disable the various buttons in the add to studio pane.
* studios will only be shown in the add to studio list if the user has the ability to *remove* the project from the given studio.
* if the project belongs to the user, all studios the project is in should appear, as well as all studios that they curate.
* if the project does not belong to the user, they should only see studios that they curate.
* each studio has a `canAdd` and a `canRemove` property that controls whether or not the user has the …

Add to studio modal should only show studios user can actually change

---

package.json
src/views/credits/credits.jsx

Fixes a bug where reordering a sound could cause a crash.
Also brings in the change to the credits page where logos without links don't link to nowhere.

Deploy sound reordering fix

---

src/lib/extensions.js
src/routes.json
src/views/wedo2/l10n.json
src/views/wedo2/wedo2.jsx

Update the wording for the WeDo 2.0 extension landing page, so that it is always referred to as either "LEGO Education WeDo 2.0" or "WeDo 2.0" (and _not_ "LEGO WeDo 2.0").
- Page title (shown on the tab) is "Scratch - WeDo 2.0"
- Header title is "LEGO Education WeDo 2.0"
- Wording in the header text includes "your WeDo 2.0 creations"
- Link in the troubleshooting area to the WeDo legacy page says "using WeDo with Scratch 2.0." (this is a special case, because a) the page includes info about both WeDo 2.0 and WeDo 1.0 and b) repeating "2.0" twice in the sentence looks even more confusing).
Also update the extension chip to read "WeDo 2.0"

LEGO branding updates

---

src/views/preview/formsy-project-updater.jsx
src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

Note: use the "whitespace" option in view options, since a lot of this is indentation change
This introduces a `FormsyProjectUpdater` file that uses the technique of [render props](https://levelup.gitconnected.com/understanding-react-render-props-by-example-71f2162fd0f2) in order to put save/error functionality in a separate, recyclable file while keeping the markup inline.
The `FormsyProjectUpdater` takes care of sending project data updates to the server, and when it gets an error state back it triggers the formsy error states, which have to be managed in this strange imperative way.
Test this by having the API send back 400s (for inappropriate content) and anything other than 200s to see the general "something went wrong" message (in case the servers go down, 500s, etc.)
Thanks for …

[Develop] Wrap project update inputs to show server validation

---

src/views/jobs/jobs.jsx

Resolves #2625 
Adds the Community Moderator job listing, and removes the message about there being no jobs available.
I know it's no longer help-wanted, but I'm sure you wouldn't mind an outside pull anyway, right?

Add Community Moderator listing

---

.tx/config
src/routes.json

The `download/scratch2` l10n file was missing from the config file, along with the new ideas page.
Also, the `name` field in the routes json needs to match the resource name. So changed the `download-scratch2` route name to match the l10n name.
This is why you would get lots of things missing when making translations. The resources still need to be included in scratchr2_translations for the 'make' step to work properly.

Add missing resource to .tx/config

---

src/routes.json

Fixes #2271 
Adds a route for `/tutorials` or `/tutorials/` that redirects to `/projects/editor/?tutorial=all`

Add route for `/tutorials` shortcut

---

src/components/modal/base/modal.scss

Fixes https://github.com/LLK/scratch-gui/issues/4046 
I think this also fixes the modal part of https://github.com/LLK/scratch-www/issues/2157 (It appears the loading screen and monitors were fixed previously)
The gui uses z-indices up to 500 for things that should be covered by a modal and sets the modal to 510. www should match gui.
Modals were already above everything with a z-index on www except for the gui-player in fullscreen mode. I created a spreadsheet that documents [gui and www z-indices](https://docs.google.com/spreadsheets/d/169cRxUOGXCfi716BDOLQLrhmP9ei-A-iUQWEK6rSw1A/edit?usp=sharing)
Since this is change to the base modal, we should check that modals are still fine overall.
- registration modal (on any page including project page)
- report modal
- delete comment modal
- …

Make www modal z-index consitent with gui

---

src/views/preview/comment/comment.scss

https://github.com/LLK/scratch-www/pull/2512 had the effect of disabled commenting on mobile, per a decision from december that was not implemented then in the interests of keeping the build stable for launch.
On further discussion with designers, we're not going to remove comment creation on mobile at this time.

reenable commenting on mobile, which was disabled in #2512

---

src/views/about/about.jsx

We decided that the version of the Scratch Video on the About page should not autoplay.

Change video id to one without autoplay

---

src/components/login/login.jsx
src/components/login/login.scss

Fixes #2309 
The `need help` link for resetting a password was awkwardly positioned when the translation was too bit to fit beside the `submit` button. 
Refactored the submit row of the login component to use Flex Row instead of `float: right` for the `need help` link.  The bulk of the changes are white space, so remember to ignore whitespace for review. The link wraps so that it is under the button if it doesn't fit next to it.
A selection of languages:

Wrap ‘need help?’ link when translation is too long

---

src/views/preview/project-view.jsx

Resolves https://github.com/LLK/scratch-gui/issues/4212
This fixes the issue where you could go from `/projects/editor` => `/projects/0/fullscreen` by entering fullscreen mode on a new unsaved project.
Since there is no such route as `/projects/fullscreen`, just abandon the history management for projects that have ID=0 (i.e. not saved on the server)
_Please show how you have added tests to cover your changes or describe how you have …

Prevent seeing /projects/0/fullscreen URL

---

src/views/preview/censored-message.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Resolves https://github.com/LLK/scratch-api/issues/724 , by implementing client side handling of the API changes in https://github.com/LLK/scratch-api/pull/722 .
* Changes the `PropTypes` spec of `visibilityInfo` to include two new fields: `censoredByAdmin` (currently unused) and `censoredByCommunity`.
* `preview/presentation.jsx` passes `censoredByCommunity` to the `CensoredMessage` component
* `CensoredMessage` component shows distinct, autocensored-specific message if no manual message has been included, and `censoredByCommunity` is true
None

show autocensored message if API indicates project was autocensored

---

src/redux/preview.js
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

@rschamp this is the WWW side of projects not be reported with their snapshot.
Depends on https://github.com/LLK/scratch-gui/pull/4567
This PR allows WWW to include a thumbnail snapshot of the stage when reporting a project.

Get thumbnails from the project for reporting
