scratchfoundation/scratch-www

src/views/credits/credits.jsx

Travis was complaining that link 188 had over 120 characters, this should fix it.
Here's where I saw it: https://github.com/LLK/scratch-www/issues/358#issuecomment-181396113

Fix travis build fail

---

src/views/splash/splash.jsx

Updated the number with a more recent number, I wasn't sure if using a string like "Loading..." would damage anything.
Temporary fix for #357
Also added a comment about the project count, but that doesn't change much. :stuck_out_tongue_winking_eye:

Fix gh-357: Splash - Initial value of project count is arbitrary

---

custom-locales.json

[Develop] Fix GH-381: add custom langauges

---

languages.json

The language has a sufficient level of translation to be added now.

Add nynorsk to dropdown

---

src/components/navigation/navigation.scss

Fix incorrect nesting in search styles

---

src/components/navigation/navigation.jsx

Caused by merging an old branch which didn't have conflicts, but did have a different understanding of session.
FYI @mewtaylor

Fix reference to session

---

src/views/wedo2/wedo2.jsx

Need to add the new `Page` component so that this page renders correctly. Currently shows up as a blue box.

[Master] Hotfix: Wrap wedo2 view in page component

---

src/components/footer/conference/footer.jsx
src/components/footer/conference/footer.scss
src/views/conference/expect/expect.jsx

1. s/collaborators/sponsors
2. open footer links in new window
3. remove superfluous require statement
4. increase spacing for scratch family links

Cleanup for scratch conference

---

src/components/footer/www/footer.jsx

Revert "Fix gh-427: Footer Wiki Link not working"

---

bin/deploy-to-s3.js

This will give us cleaner builds — I meant to include it from the beginning. It may help with the version.txt issue we're seeing on master.  When I ran it locally, it updated staging, although staging didn't show the issue anyway.

[Master] Remove deleted files from S3 on build

---

src/components/intro/intro.jsx
src/views/conference/expect/expect.jsx
src/views/splash/l10n.json
src/views/splash/splash.jsx

Update project count to (temporarily) fix #426  
I took the liberty to update _all_ references of 13 million projects to 14 million projects.
@mewtaylor @thisandagain @rschamp

Fix gh-426: Update Project Count

---

src/_typography.scss
src/routes.json
src/views/guidelines/guidelines.jsx
src/views/guidelines/guidelines.scss
src/views/guidelines/l10n.json

Rebased #421 and added all of the changes as per @mewtaylor's comments.
(#19 - so that #19 has a reference to this PR)
I already know that Travis will hate the image url, it would be great if a shorter url could be created.

Fix gh-19: Migrate Community Guidelines

---

src/views/conference/plan/plan.jsx

[Master] Hotfix: Add registration to FAQ

---

.travis.yml
package.json
src/routes.json
src/views/privacypolicy/privacypolicy.jsx

Rebased and updated version of #471, to resolve #309.
HTML tested locally on Chrome 50 (ChromeOS)
@rschamp @thisandagain @mewtaylor

Fix gh-309: Migrate Privacy Policy

---

.eslintignore
.eslintrc
Makefile
package.json
src/redux/actions.js
src/redux/reducer.js

This adds a JSON linter to catch JSON errors before trying to build or run.
It also adds directory rules to eslint and sass-lint, so that when we add new directories or new depths of directories, we don't need to add them to the lint step.
When I added those rules, the linter found errors in un-linted files (including a bug!), which I fixed.
Fixes #472

Lint JSON and all of our .js and .scss

---

src/views/privacypolicy/privacypolicy.jsx

I can't believe I missed this one earlier. \*facepalm\* Sorry about that.
Also, I'm thinking about solutions for the non-bolding problem. Perhaps we should increase the font-weight for the `<h3>`s?
(And yes, I double-checked to make sure there were no more this time)

[Privacy Policy] One space more

---

Makefile

Missed this when we moved that task to webpack.

Remove tag target

---

bin/configure-fastly.js

When talking to Fastly, don't ever use an express-style url pattern for consistency, and so we don't use : characters in condition names.
FYI @mewtaylor

Always use regex form of route patterns

---

src/l10n.json

As per https://github.com/LLK/scratch-www/pull/503#issuecomment-220647078

Fix gh-500: Footer press link

---

src/views/conference/index/index.scss

There were some problems with a previous commit of mine that caused other PRs to fail in Travis due to whitespace issues. This PR adds the correct amount of whitespace.

Fix whitespace issues in index.scss

---

src/views/privacypolicy/privacypolicy.jsx

Fix Password Reset Link

---

src/components/footer/conference/footer.jsx
src/components/footer/conference/footer.scss
src/components/navigation/conference/navigation.scss
src/components/thumbnail/thumbnail.scss
src/views/conference/details/details.jsx
src/views/conference/details/details.scss
src/views/conference/index/index.jsx
src/views/conference/index/index.scss
src/views/conference/plan/plan.jsx
src/views/conference/schedule/schedule.scss

Thanks @carljbowman and @jwzimmer ! Here are some updates for typography/mobile fixes

For GH-497: conference tweaks for fallout from schedule/typography

---

src/components/navigation/conference/navigation.scss
src/components/page/conference/page.scss
src/views/conference/expect/expect.scss

Some additional mobile tweaks for conference

---

bin/configure-fastly.js

Otherwise anything with html in the path matches. Fixes #527
/cc @mewtaylor @thisandagain

Terminate view.html rewrite rule

---

Makefile
bin/configure-fastly.js
bin/lib/fastly-extended.js
src/components/activity/activity.scss
src/components/footer/conference/footer.jsx
src/components/footer/conference/footer.scss
src/components/footer/www/footer.scss
src/components/navigation/conference/navigation.scss
src/components/navigation/container/navigation.scss
src/components/news/news.jsx
src/components/news/news.scss
src/components/page/conference/page.scss
src/components/thumbnail/thumbnail.scss
src/l10n.json
src/views/conference/details/details.jsx
src/views/conference/details/details.scss
src/views/conference/expect/expect.scss
src/views/conference/index/index.jsx
src/views/conference/index/index.scss
src/views/conference/plan/plan.jsx
src/views/conference/schedule/schedule.jsx
src/views/conference/schedule/schedule.scss
src/views/privacypolicy/privacypolicy.jsx

[Develop] Release 2.2.9

---

src/views/dmca/dmca.jsx

This PR corrects an error in #542 that caused the DMCA page's text to be wider than it should have been.

Fix DMCA page

---

src/redux/conference-schedule.js

1. Sort schedule by 24-hour time to handle 12-o-clock
2. Sort chunks by type AND time, since multiple chunks have the same name

[Master] Hotfix: conference schedule formatting bugfixes

---

src/components/navigation/conference/navigation.scss
src/views/conference/expect/expect.jsx

[Develop] hotfix: mobile nav conference

---

src/lib/shuffle.js
src/views/splash/splash.jsx

This PR resolves #123 by using a Fisher-Yates shuffle<sup>1</sup> on the array of projects in the top loved and top remixed section.
[1] Source: https://www.frankmitchell.org/2015/01/fisher-yates/

Fix GH-123: Shuffle top loved and top remixed

---

src/components/grid/grid.jsx
src/components/grid/grid.scss

Fixes #573
* Click "Load More" on `/explore/projects/art` until you get a row with only 3 projects in it. Those 3 projects should be left-aligned.
* The grid of projects should be centered in the box

Fix GH-573: center align grid while left aligning projects

---

src/components/footer/www/footer.jsx
src/l10n.json

Fix GH-556: Add "For Developers" to the footer

---

.eslintignore
src/_colors.scss
src/views/jobs/jobs.jsx
src/views/jobs/jobs.scss

- Add 'Web Designer' job description
- Adjusted typography to match new Type Standards
- Add Hex Value to `_colors` for consistency
In addition to updating the jobs page, @rschamp asked to update `.eslintignore` to ignore `locales/*`

Jobs update

---

src/views/jobs/jobs.jsx

Fix gh-602: Remove Community Counselor

---

src/components/deck/deck.scss
src/components/forms/charcount.scss
src/components/forms/checkbox-group.scss
src/components/forms/checkbox.scss
src/components/forms/radio-group.scss
src/components/forms/select.scss
src/components/registration/steps.jsx

some scoping, as well as class labeling

styling cleanup for teacher registration

---

src/components/teacher-banner/teacher-banner.jsx

whoops! Thanks @rschamp. Fixes #611

Fix GH-611: Connect `TeacherBanner` to redux

---

src/views/teachers/landing/l10n.json
src/views/teachers/landing/landing.jsx
src/views/teachers/landing/landing.scss

This PR fixes #620 by changing the button string to "Coming Soon", removing the link to teacher registration, and restyling the button to match the mockup in the issue.

Fix GH-620: Replace "Request account" with "Coming Soon"

---

src/views/teacherregistration/teacherregistration.scss

They're both mostly info cards, so give them the same styling Fixes #627 .

Fix GH-627: style error-step like last-step

---

src/views/teachers/landing/l10n.json

Fix GH-636: point landing page to teacher faq page

---

src/components/registration/steps.jsx
src/views/teacherregistration/l10n.json

Fix localization of address validation message

---

src/components/carousel/carousel.jsx
src/components/navigation/www/navigation.jsx
src/components/teacher-banner/teacher-banner.jsx
src/views/splash/splash.jsx

A couple of changes in the release caused some pretty spammy warnings in development.
/cc @mewtaylor

Get rid of most splash warnings in development

---

src/views/teachers/landing/landing.jsx
src/views/teachers/landing/landing.scss

This PR fixes #680 and #681 by changing the story divs to `a` elements and setting `cursor: default` on the Coming Soon button.

Fix GH-680 and GH-681: Educator landing style tweaks

---

src/views/explore/explore.jsx
src/views/search/search.jsx

Fixes #686, thanks @thisandagain !

Fix GH-686: Add language to search / explore api requests

---

src/routes.json

Towards Hotfix: Allow urls with `ajax` to pass through

---

src/routes.json

Trying #716 again due to CI failure.

[Master] Hotfix: Allow urls with `ajax` to pass through

---

src/views/teachers/landing/landing.jsx

Fixes the typo mentioned in #732.

Fix GH-732: Plug-In Studios -> Plug-In Studio

---

src/views/teacherregistration/teacherregistration.jsx

This is needed to ensure that the approval step displays the correct “Wait for Approval” message. Fixes #698

Fix GH-698: refresh session on successful registration

---

bin/configure-fastly.js

Don't require end slashes when replacing arguments

---

src/views/studentcompleteregistration/studentcompleteregistration.jsx

Fixes #747.
Also explicitly show a spinner when the component is waiting on the class API, and hide it when it returns.

Show an error if the API doesn't return class data

---

src/redux/session.js

Redirect students that must reset their password

---

src/redux/session.js

Don't redirect to password reset on complete_registration

---

src/components/deck/deck.scss

Tested in Edge and Chrome.
Fixes #769 
/cc @mewtaylor

Don't use a static width for inputs

---

src/components/registration/steps.jsx
src/components/registration/steps.scss
src/views/teacherregistration/l10n.json

Fix GH-[772,773]: Fix “afterschool” typo, default country and margin for username

---

src/views/teacherwaitingroom/teacherwaitingroom.jsx

[Develop] Only redirect approved educators to My Classes

---

src/views/teacherwaitingroom/teacherwaitingroom.jsx

[Master] Only redirect approved educators to My Classes

---

src/components/subnavigation/subnavigation.jsx
src/components/subnavigation/subnavigation.scss
src/views/teachers/landing/l10n.json
src/views/teachers/landing/landing.jsx
src/views/teachers/landing/landing.scss

[Master] Add "Request Account" button to Educators landing page

---

src/views/conference/schedule/schedule.scss

[Master] Hotfix: Create space between paragraph elements

---

src/views/teachers/faq/l10n.json

[Develop] Add link to teacher account walkthrough video

---

Makefile

hopefully just using file extensions works

[Develop] Hotfix: Don’t use mime magic to guess

---

src/components/forms/phone-input.jsx
src/components/forms/validations.jsx
src/components/registration/steps.jsx
src/l10n.json

1. Phone too long validation occurs before submit now.
2. Organization “other” type is now being required
3. Organization type required now shows up at the same time as other organization validation errors
4. Username check now occurs earlier, on blur rather than on submit
Fixes #683, #705, #712, #797.
* Try to register with a pre-existing username. It should show you an error after you focus out from the username field
* Try to type a phone number that's too long – it should show an error and prevent moving to the next step
* Try to submit without choosing an organization type or an organization name. The organization type error should appear
* Try to choose "Other" for organization without putting anything in the black input. An error should appear, and prevent you from moving to the …

Fix GH-[683,705,712,797]: Updates to registration UX for teachers

---

src/components/forms/checkbox.scss

Fixes #812 
I can enhance it more if needed. I'm not sure if this is the preferred method of border display code, so super sorry if it isn't!
Before: 
After: 
hurrah for finally understanding scss variables :P

Fix GH-812 / Enhance Checkbox Display

---

src/views/splash/splash.jsx

[Develop] Hotfix: Bind the banner api method to the splash page

---

src/components/forms/phone-input.jsx
src/components/forms/validations.jsx
src/components/registration/steps.jsx

[Develop] Hotfix: Remove `phoneLength` validation

---

src/lib/api.js
src/lib/smarty-streets.js

[Develop] Fix GH-828: check street number range for address

---

src/components/registration/steps.jsx
src/l10n.json

[Develop] Hotfix GH-835: Add maxLength validations when needed

---

src/l10n.json

This is an update for #842 to add new copy based on feedback given on PR #841. Thanks @kaschm and @jwzimmer!

For GH-835: Update max length copy

---

src/views/teachers/landing/landing.jsx

This PR fixes #850 by changing the images to be clickable. 
@mewtaylor

Fix GH-850 // Add image links

---

src/routes.json
src/template-config.js

Now that we have mobile nav/footer.
/cc @rschamp @technoboy10

Bugfix: Add `device-width` by default

---

src/components/grid/grid.scss

This also does a bit of restructuring of the grid file – reduces declarations where possible, and rewords some of the variables declared.

Bugfix: Align projects in grid to the left

---

src/views/guidelines/l10n.json

As per @Paddle2See on #853
@mewtaylor

Fix gh-853: Update Community Guidelines

---

src/views/conference/index/index.jsx

Updates as per #864 :)
Sorry if I've been hogging issues recently :(

Fix gh-864 // Update Conference Text

---

README.md

Updates the Readme to include Node requirements as per https://github.com/LLK/scratch-www/issues/838#issuecomment-239803847 fixing #844 :)

Fix gh-844 // Update Readme

---

src/views/credits/credits.jsx

#900 As per @christanbalch 
"For the Scratch Team section:
Add Sarah Otts (scmb1 on Scratch)
Add Connor Hudson (technoboy10 on Scratch)
Add Hanako Tjia (hanakoala on Scratch)
Remove Ben Berg
Remove Hannah Cole
For the Moderator Section:
Add Tauntaun Kim (thetaun on Scratch)
Remove Sarah Otts (she is being moved up to ST section)
Remove Andrea Saxman
For the "Previous MIT Scratch Team Members" section:
Add Ben Berg
Add Hannah Cole
Add Andrea Saxman"
Additionally, I added the profile picture link for Morant and Shruti. Also, I didn't see any specific order request or any real order currently, but if anything needs to be changed :)
@mewtaylor

Fix gh-900 // Update Credits

---

src/views/conference/index/index.jsx

As per @sleggss on #918
(@mewtaylor I see that the issue was assigned to you, but I assumed that it would be OK for me to fix it because of the `help wanted` tag)

Fix gh-918: Update Video Link

---

Makefile

In @jwzimmer's repro of https://github.com/LLK/scratchr2/issues/4075, her Javascript was not up to date with the hotfix. The cache settings that causes blank pages may be to blame for this. I should have included this in the original hotfix.
/cc @mewtaylor @thisandagain

[Master] Add Cache-Control header to all S3 uploads

---

src/views/wedo2/l10n.json

Fix gh-930: Update requirement string

---

src/views/credits/credits.jsx

Fixes #950 by adding Travis-CI organization to the credits page. :)

Add Travis-CI

---

src/views/splash/l10n.json
src/views/splash/splash.jsx

Fixes #965 by adding a space in the projects curated by text. :)

Fix gh-965 - Projects Curated by space

---

Makefile

[Develop] Use no-cache so ETags are used

---

bin/build-locales
bin/lib/locale-compare.js
package.json
src/components/activity/activity.jsx
src/views/splash/splash.jsx
src/views/wedo2/l10n.json
test/fixtures/test_es_md5map.json
test/functional/build_locales_icuMap.js
test/functional/build_locales_mergeDupStrings.js
test/functional/build_locales_mergeTranslations.js

Fixes the problem where the same literal string is associated with different message keys on multiple pages. Fixes #940

[Master] Hotfix - update build-locales script

---

src/redux/session.js

Goes along with https://github.com/LLK/scratchr2/pull/4127.
* As a banned user, try to go to any page on the www repo that's not community guidelines – you should get redirected to the banned user page
* As a banned user, try to go to the community guidelines page – you should be able to go to it

Don’t redirect banned user on community guidelines

---

.gitignore
Makefile
package.json

Hello Scratch team and Happy Hacktober. :)
I love Scratch and would like to help out by contributing code to your projects.
I'm also a big fan of TDD, so I thought I'd get started by measuring coverage.
I've enabled travis and coveralls on my fork.
Here's the coveralls report from this commit: https://coveralls.io/builds/8488587
Please let me know if there's anything else I need to do to begin contributing, and of course anything I should do for this PR.

Measure test coverage

---

src/views/jobs/jobs.jsx

Removes Senior Front-End Engineer and Web Developer, as per #988 :)

Fix gh-988: Update jobs page

---

README.md

Add coverage and dependency badges to README

---

languages.json

Scratch share user, See LLK/scratch-flash/issues/1230

Add Zulu to Language Menu

---

src/views/jobs/jobs.jsx

Should fix #1026 
I have a feeling Travis won't like how long the URL is though...

Fix gh-1026: Trust and Safety Manager URL update

---

src/views/cards/l10n-static.json

Bug found by @jwzimmer, thanks!

remove uri from path

---

src/routes.json

Remove extra $

---

src/views/splash/hoc-banner/hoc-banner.jsx
src/views/splash/hoc-banner/hoc-banner.scss
src/views/splash/l10n.json

Fixes #1078. This also fixes #1076 and https://github.com/LLK/scratch-www/issues/981#issuecomment-263301322 by updating the styling accordingly.
/cc @carljbowman @rschamp

Fix GH-1078: Add “open” string to l10n.json

---

languages.json

Fixes #1047 
Add belarusian with the correct language name.

Add Belarusian to the menu

---

src/components/registration/steps.jsx

Fixes #1112, which was created by moving the error message into `general`. Fallout from #1099.

Fix GH-1112: Update id string for general error message strings

---

src/components/registration/steps.jsx

Fixes #1125. I had fixed this last iteration, not sure how it got re-introduced.
/cc @rschamp

Fix GH-1125: get `formatMessage` from props

---

src/views/studentregistration/studentregistration.jsx
src/views/teacherregistration/teacherregistration.jsx

Fixes #1124 by not assuming there is any body associated with the response.  That we don't send one is news to me, but we should cover this possibility in any case.
/cc @mewtaylor

Allow empty responses

---

src/views/microworld/fashion/fashion.json

Fix #1118 - broken link to fashion microworld video

Fix #1118 - broken link to fashion microworld video

---

src/components/login/login.jsx
src/l10n.json

This is part of https://github.com/LLK/scratchr2/pull/4451

For r2-4451: Change password reset anchor text

---

src/components/footer/conference/2016/footer.jsx
src/components/footer/conference/2017/footer.jsx
src/components/navigation/conference/2017/navigation.jsx
src/components/page/conference/2016/page.jsx
src/components/page/conference/2017/page.jsx
src/views/conference/2017/index/index.jsx
src/views/conference/2017/index/index.scss
src/views/conference/2017/index/l10n.json

Thanks @kaschm for tracking these!

Bugfix: Some copy fixes for new conference page

---

src/components/footer/conference/2017/footer.jsx
src/components/footer/conference/footer.scss

thanks @jwzimmer! /cc @chrisgarrity

Add language chooser to conf footer

---

src/views/developers/developers.jsx

Should fix #1202 
@mewtaylor @thisandagain @rschamp

Fix gh-1202: ProjectsTitle localization

---

src/views/credits/l10n.json

Should fix #1201
@mewtaylor @rschamp @thisandagain

Fix gh-1201: credits localization typo

---

src/components/registration/steps.jsx

Fall out from #1217. We should likely change the way this is set up, it seems not ideal. But not sure the best way atm.

GH-1196 Follow Up: Update `otherDisabled` check

---

src/l10n.json

Fix gh-1222: One 24 Hours More

---

src/views/conference/2017/index/l10n.json

Fixes #1214
(Also, I'm not sure what's going on with the new line at the end of the file. 🤔)

Fix gh-1214: Lowercase F in Family

---

src/components/footer/www/footer.jsx

Fix gh-1183: Remove slashes

---

custom-locales.json

Added sc to custom-locales with parent Italian (it).

Make Sardinian translations appear on www pages.

---

src/components/footer/www/footer.scss

Fix gh-1232: Footer Links space-between

---

src/views/splash/splash.jsx

redis emptied when mc1 restarted, so this is all going to mysql at the moment

[Master] Temp Hotfix: remove custom rows

---

src/views/splash/splash.jsx

Revert "[Master] Temp Hotfix: remove custom rows"

---

src/views/search/search.jsx

Resolves #875 
- Search bar in actual search page should be removed
- Search bar in nav-bar should still be there
Cc @carljbowman

Fix gh-875: Double Search Bar

---

src/views/conference/2017/index/index.jsx

Change conference date

---

src/views/explore/explore.jsx

Corresponds to a new endpoint that is being developed for our REST API.

For api-250: Change explore endpoint

---

src/views/explore/explore.jsx

Temporary fix for https://github.com/LLK/scratch-search/issues/45

[Master] Revert PR #1324

---

src/views/explore/explore.jsx

Revert "[Develop] Revert PR #1324"

---

src/views/explore/explore.jsx

Revert "[Master] Revert PR #1324"

---

src/views/credits/credits.jsx

Fixes https://github.com/LLK/scratch-www/issues/1331
I added Mark Ferrell to the credits page. 
Tested in Firefox

Fix issue/gh-1331: added mark ferrell to credits page

---

src/components/footer/www/footer.jsx
src/l10n.json

Goes with https://github.com/LLK/scratchr2/pull/4701

Add `/store` to footer

---

src/views/tips/l10n.json
src/views/tips/tips.jsx
src/views/tips/tips.scss

* removed white-space: no wrap to let buttons flow in Cards section
* Fix download link (download should be part of the link)
* Set the size of the icons to fix alignment

FIx layout problems

---

src/routes.json

basing new patterns for /help and /info on /go.
/cc @mewtaylor

update /help and /info routes

---

src/views/camp/l10n.json

Fixes Down Deep Camp Counselors Link

---

src/views/tips/tips.jsx

Updates the link provided by @ntlrsk :)
https://scratch-foundation.myshopify.com/collections/all-products/products/scratch-coding-cards-creative-coding-activities-for-kids
Fixes #1410

Fix gh-1410: Correct "Tips" Page Link

---

src/views/camp/l10n.json

Fixes #1425 by changing "How to Particpate" to "How to Participate" :)

Fix gh-1425 // Camp Page Typo

---

src/routes.json

Rebase and revamp of #1272 
@mewtaylor

Alphabetize Routes List v2

---

src/views/jobs/jobs.jsx

Also hotfix removal of moderator position
/cc @thisandagain

[Master] 	Add Senior Backend Engineer job posting

---

test/helpers/selenium-helpers.js
test/integration/smoke-testing/test_signing_in_and_my_stuff.js
test/integration/smoke-testing/test_signing_in_homepage.js
test/integration/smoke-testing/test_statistics_page.js

Fixes https://github.com/LLK/scratch-www/issues/1420 by moving the selenium helper functions into their own file, following the style @paulkaplan used in https://github.com/LLK/scratch-gui/pull/584.

Fix GH-1420 Issue/refactor helper functions

---

bin/build-locales
test/localization/check_valid_json.js

* make build-locales fail if there are errors in the translations
* add test to parse translation files
Also make build-locales quieter if there are no problems.

Add error checking and testing for translations

---

src/views/credits/credits.scss

#1470 
Add specific style on credits page to allow for word wrap.

Fix gh-1470 Firefox Overflow on Credits Page

---

src/components/navigation/www/navigation.jsx

the interval to check for message count is not working on www due to a parentheses mismatch

[Master] fix parentheses around interval

---

src/components/registration/steps.scss

Resolves #1195
Add focus highlight scss for radio buttons on demographic registration step.

Fix issue 1195 registration gender tabbing

---

src/views/credits/credits.jsx

Add Tina Quach to Credits

---

src/views/messages/message-rows/comment-message.jsx

Add Link to profile pic

---

src/views/jobs/jobs.jsx
src/views/jobs/moderator/moderator.jsx

- #1442 (re-opened by @dietbacon)
- #1596
Removes community moderator job listing & adds a hyphen to the moderator job page.

Removes the community moderator & adds hyphen to the moderator page.

---

src/components/intro/intro.jsx
src/views/splash/l10n.json
src/views/splash/presentation.jsx

Resolves #1588 
- component string should still read "it's free!" while using English
- component string should now be in Transifex

Fix gh-1588: Localize "it's free!" String

---

src/views/download/download.jsx
src/views/download/l10n.json

I changed all Adobe Air, to Adobe AIR

Fixes #1645 and #1644

---

src/views/conference/2017/index/index.jsx
src/views/conference/2017/index/l10n.json

Hotfix #1649: Correct Info for Costa Rica Conference

---

.tx/config
src/components/footer/conference/2018/footer.jsx
src/components/navigation/conference/2018/navigation.jsx
src/components/navigation/conference/2018/navigation.scss
src/components/page/conference/2018/page.jsx
src/routes.json
src/views/conference/2017/index/index.jsx
src/views/conference/2017/index/l10n.json
src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/index.scss
src/views/conference/2018/index/l10n.json
src/views/jobs/jobs.jsx

[Develop] December 1st Hotfix

---

src/components/navigation/conference/2018/navigation.jsx

Make Conference logo button link to homepage.

---

src/components/grid/grid.jsx

[Develop] Hotfix: Change avatar to use `uploads` endpoint

---

src/views/jobs/jobs.jsx

Changes "Junior Designer" to "Designer" on the jobs page and fixes the link.
#1703

Fixes #1703 | Update role on jobs page

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

Allow caching of specific `^/projects/` pages while maintaining language selection for non-logged in users. Reduce complexity of recv backend selection.

[Develop] Project page caching

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

Allow caching of specific ^/projects/ pages while maintaining language selection for non-logged in users. Reduce complexity of recv backend selection
See #1707

[Master] Project page caching

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

Revert "[Master] Project page caching"

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
src/views/conference/2017/index/index.jsx
src/views/conference/2017/index/l10n.json
test/unit/test_fastly_config_methods.js

Provides caching for /projects for non-logged in users only

[Develop] Hotfix/project caching

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

Caches /projects pages only for users who are logged out

[Master] Hotfix/project caching

---

src/views/splash/hoc/middle-banner.jsx
src/views/splash/hoc/top-banner.jsx
src/views/splash/hoc/top-banner.scss
src/views/splash/l10n.json
src/views/splash/presentation.jsx

Invite logged-out users to ‘Get Started with Coding!’, and make the whole Scratch animation clickable (goes to the Animate a Name tutorial).
See #1664

Switch CTA button based on logged in state

---

bin/configure-fastly.js

We can configure this within Travis

[Master] Conditionally purge on deploys

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

This adds ^/fragment/account-nav.json and ^/session to being cached for logged out users

[Develop] Hotfix/cache nav session endpoints

---

bin/configure-fastly.js
bin/lib/fastly-config-methods.js
test/unit/test_fastly_config_methods.js

Cache ^/fragment/account-nav.json and ^/session for logged out users

[Master] Hotfix/cache nav session endpoints

---

src/routes.json

[Master] Redirect /hoc2014 -> /tips

---

src/views/splash/presentation.jsx

Just temporarily for the start of CSEdWeek next week.

[Master] temporarily take out curator row and recently shared row

---

src/views/credits/credits.jsx

Adds kchadha to the credits as requested in #1728.

Fixes #1728 | Add new member to credits

---

src/views/splash/presentation.jsx

[Master] Add back curator and recently shared rows

---

.github/ISSUE_TEMPLATE.md

#1733 
Changes "eplicit" to "explicit".
- After testing, the changes don't break any of the file

Fix #1733 | Spelling issue

---

.github/PULL_REQUEST_TEMPLATE.md

#1736
Adds the enhancements provided in #1736 
I looked at the file. (since it is a .md)

Fixes #1736 Pull Request Template Enhancements

---

package.json
src/routes.json
src/views/preview-faq/l10n.json
src/views/preview-faq/preview-faq.jsx
src/views/preview-faq/preview-faq.scss

Implements #1711
Adds a new page for the 3.0 faq, with a the published faq doc embedded in a `Box` component. Sets a fixed height to `450px` while being responsive in width. Current endpoint: `/preview-faq`

Implement GH-1711: Add 3.0 preview faq page

---

src/views/jobs/jobs.jsx

Also reorder existing posts to be alphabetical.

Add Full Stack Engineer job post

---

webpack.config.js

#1684 
This should be tagged "ergonomics."

Don't run UglifyJS unless it's a production build

---

README.md

Resolves #1823 
Update testing guide url
Add explanations to sections of README

Clarify README and fix link on README to testing guide

---

src/views/splash/l10n.json
src/views/splash/presentation.jsx
src/views/splash/splash.jsx

[Master] remove recent projects row

---

src/components/navigation/conference/2018/navigation.jsx
src/views/conference/2018/index/index.jsx
src/views/conference/2018/index/index.scss
src/views/conference/2018/index/l10n.json

Hotfix ready to deploy when conference registration has filled up. We're expecting to sell out in the next few days.
fixes #1810 
Removes conference registration link. Adds Conference sold out FAQ.

[DEVELOP] Close registration when full

---

.gitignore
Makefile
package.json
test/integration/package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test-login-failures.js
test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_footer_links.js
test/integration/smoke-testing/test_navbar_links.js
test/integration/smoke-testing/test_signing_in_and_out_discuss.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js
test/integration/smoke-testing/test_statistics_page.js

Makes it so you can run the integration tests so they show each test individually and whether it passes or fails.  It should make it easier to find which test is failing.
Add a method of running the integration tests remotely using make and npm: npm run smoke-verbose and make smoke-verbose.
Dependent on these PRs: https://github.com/LLK/scratch-www/pull/1877 and https://github.com/LLK/scratch-www/pull/1878

Verbose testing

---

.gitignore
test/integration/package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test_footer_links.js
test/integration/smoke-testing/test_navbar_links.js
test/integration/smoke-testing/test_signing_in_and_out_discuss.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js
test/integration/smoke-testing/test_statistics_page.js

This makes sure that www is using the same version of selenium-webdriver as gui, which should make it easier to make them more similar.
This updates the version of Selenium Webdriver and Chromedriver used in the integration tests.  It also moves selenium helper file and makes sure that the existing tests use it properly.  
There are some other mild changes to the existing smoke tests to get most of them to pass.
Run the smoke tests following the instructions [in the readme](https://github.com/LLK/scratch-www/blob/develop/test/integration/README.md)

Update selenium webdriver

---

.gitignore
test/integration/package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test-login-failures.js
test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_footer_links.js
test/integration/smoke-testing/test_navbar_links.js
test/integration/smoke-testing/test_signing_in_and_out_discuss.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js
test/integration/smoke-testing/test_statistics_page.js

Sign_In_And_My_Stuff had two unrelated set of tests in it, which I split into two separate files.  This is dependent on this PR: https://github.com/LLK/scratch-www/pull/1877
Splits the Sign_In_And_My_Stuff integration test into test-my-stuff.js and test-login-failures.js.

Split my stuff test

---

src/components/registration/steps.jsx
src/views/privacypolicy/privacypolicy.jsx

- Updates privacy policy to reflect necessary modifications for GDPR
- Updates the default "opt-in" state during teacher registration
/cc @dietbacon

[Develop] Hotfix - Update Privacy Policy

---

src/components/registration/steps.jsx
src/views/privacypolicy/privacypolicy.jsx

See #1891 — This is that onto master, plus post-merge fixes.

[Master] Hotfix Privacy Policy updates

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Found a couple of typos now that API can process favorites.
Resolves #1852 
* calls setFavedStatus (not loved)
* sets the correct style for `favorited` status

Fix up favorites

---

Dockerfile
README.md
docker-compose.yml
docker_entrypoint.sh

This allows for using a localized docker development environment that works in concert with scratch-api and scratchr2
Adds Dockerfile, docker-compose.yml and docker_entrypoint.sh
Requires no tests. This is an environment that allows running tests within it.

Dockerization 

---

README.md

Adds a sentence of description to How to Deploy section of README. 
Also makes whitespace compliant with markdown linting, hope this isn't annoying :)

added sentence of detail on deployment

---

package.json
test/integration/selenium-helpers.js
test/integration/smoke-testing/test-login-failures.js
test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_footer_links.js
test/integration/smoke-testing/test_navbar_links.js
test/integration/smoke-testing/test_project_rows.js
test/integration/smoke-testing/test_signing_in_and_out_discuss.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js
test/integration/smoke-testing/test_statistics_page.js

Updates the Selenium Helper file to make it more in line with the GUI Selenium Helper File.  It also allows the test files to build the driver by calling a function in the helper file, rather than the Helper file building the driver and then the test file pulling in a built driver.  This lets us name the tests being sent into Saucelabs.
It also updates the test files to make use of the new selenium helper and makes the test files more uniform.
Relies on this pr: https://github.com/LLK/scratch-www/pull/1936
https://github.com/BryceLTaylor/scratch-www/compare/sauce-test...BryceLTaylor:Selenium-Helper-Update

Selenium helper update

---

.travis.yml
test/integration/selenium-helpers.js

Make Travis run smoke tests with Saucelabs

---

src/views/credits/credits.jsx

Fixes: https://github.com/LLK/scratch-www/issues/1977
Adds Kathy Wu (pondermake) to credits.
Shouldn't be neccessary as I just used the template from the other members, and this is a small commit.

Add Kathy Wu to Credits

---

src/views/splash/beta/top-banner.scss

This is the same PR as #2010, but to master instead of develop.

[MASTER] Fix top banner centering on android chrome 

---

.travis.yml

This will bring in the latest version of anything not explicitly pinned, notably scratch-gui

Update packages after installing

---

src/views/terms/terms.jsx

Resolves #1999 
Change the "last updated" date on ToU

Update the last updated date

---

src/views/search/search.jsx

Add 'popular' as default setting for search.

[Master] Hotfix: Use popular for the default sort mode

---

src/views/credits/credits.jsx

#2062 
adds Katelyn to credits page
tested for MacOS+Chrome
npm tests passed

Added Katelyn to credits page

---

src/components/login/login.jsx
src/components/login/login.scss
src/components/modal/addtostudio/animate-hoc.jsx
src/components/modal/addtostudio/modal.scss
src/components/modal/addtostudio/presentation.jsx
src/components/modal/addtostudio/studio-button.jsx
src/components/modal/report/modal.jsx
src/components/spinner/spinner.jsx
src/components/spinner/spinner.scss
src/views/components/components.jsx
src/views/preview/preview.jsx
src/views/studentcompleteregistration/studentcompleteregistration.jsx
static/svgs/modal/spinner-blue.svg
static/svgs/modal/spinner-transparent-gray.svg
static/svgs/modal/spinner-white.svg
static/svgs/modal/spinner.svg

#2005 
So, I added some css for an animation but for the animation to work NICELY I had to put the whole StudioButtons in a Wrapped Component using an HOC! Big thanks to @rschamp for helping me getting started with HOCs and also helping me when I was stuck with the onClick vs onStudioToggle functions.
Tested on MacOS, Chrome, for slow and fast network connection.

Animate add-to-studio-buttons on preview project page

---

src/views/preview/preview.scss
src/views/preview/remix-credit.jsx

#2082 
MacOS, Chrome,
npm test passes

Fix notfications box, player box, buttons and icons alignments

---

src/redux/splash.js
src/views/splash/presentation.jsx

See https://github.com/LLK/scratch-www/issues/2076 . 
These seem to be straightforward bugs where failure cases and prop types aren't being handled right.
Here's a fix!

fixed errors in splash page that appear in develop

---

src/views/jobs/jobs.jsx

#2104 
MacOS, Chrome
npm tests passed

Removed moderator position from jobs page

---

package.json

The lag between releases for scratch-gui@latest hinders testing scratch-gui/www integration changes

Track scratch-gui@develop

---

src/views/preview/preview.scss

Part of #2086 . Looks ok as is but would look better after pull request #2107 .
MacOS, Chrome,

Made comments look better on mobile

---

src/views/preview/preview.scss

Part of #2086 . (This already looks ok but kind of depends on Pull request #2107. Edit, actually I changed my mind because I changed 2107 again!)
MacOs, Chrome,

Made project notes look better on mobile

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx

Part of #2086: The design envisioned the full screen player to appear for mobile devices in landscape mode.
Adds js to react to the orientation of a device to presentation.jsx
Tested as far as possible with MacOS + Chrome dev tools,

If in landscape format on mobile, switch to fullscreen mode

---

src/components/modal/report/modal.scss
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/stats.jsx
src/views/preview/stats.scss
src/views/preview/subactions.jsx
src/views/preview/subactions.scss

PR depends on #2108
Part of #2086: The stats and subactions now position nicely depending on media queries. They are also put in separate components.
MacOS, Chrome
npm test passes

Stats and subactions are responsive and separate components

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss

On mobile phones (not tablets!) the see inside and remix buttons now disappear.
MacOS, Chrome, npm test passes

New project page: See inside and remix buttons disappear on mobile

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss

#2134 
Tested on MacOs, Chrome
npm test passes

Make header of new project page look good on mobile

---

src/views/preview/presentation.jsx
src/views/preview/subactions.jsx

Part of #2133 
share date is now passed as a prop.
MacOS, Chrome, npm test passed

[new project page] share date is passed as a prop to subactions component

---

src/views/preview/presentation.jsx

Make sure not to show the "reply" option when comments are turned off!

Prevent replying when comments are turned off

---

src/redux/preview.js

Update the API route for comment deleting.
/cc @colbygk

Fix comment delete endpoint

---

src/l10n.json
src/views/preview/comment/compose-comment.jsx
src/views/preview/comment/top-level-comment.jsx
src/views/preview/l10n.json
src/views/preview/presentation.jsx

Including the error messages and the various other labels

Localize all the comment related strings

---

src/views/preview/presentation.jsx
src/views/preview/preview.jsx
src/views/preview/subactions.jsx

Partially resolves https://github.com/LLK/scratch-www/issues/2168 ; 
sets several variables:
```
canCreateNew
canRemix
canReport
canSave
canSaveAsCopy
canShare
```
Question: are there any booleans we should add? Do all of these make sense?
No functions added; no tests added
Tried using Mac Chrome

set explicit capabilities like “can____” for GUI and project page

---

src/l10n.json
src/views/preview/comment/comment.jsx
src/views/preview/comment/top-level-comment.jsx
src/views/preview/presentation.jsx
src/views/preview/preview.jsx

A few minor fixups after seeing the comments on staging
1. Add a missing comment status message
2. Show comment delete for admins as well as project owners
3. Only show report for logged in users

Comment minor fixes

---

.tx/config

Add views that weren't in the tx config. Without this, new strings in those files will never get translated.

Add missing l10n files to tx config

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss

Woops, PR https://github.com/LLK/scratch-www/pull/2237 did not consider the style impact of putting forms around those fields. Fixed!

Fix form styling for project edit fields

---

src/views/about/about.scss

Closes #891
About page does not seem to be responsive, keeps flowing out of the div. Changing the layout to grid ensures that the page is responsive, video auto flows to the next row in case of reduction in screen size.
Tested on Chrome:
Full Page:
Responsive Page:
Iphone 5:
Tested on Firefox:
Full page:
Responsive:

Responsive about page!

---

package.json

Reverts LLK/scratch-www#2241
Moving back to having scratch-www @develop point to scratch-gui @develop

Revert "Track scratch-gui@latest "

---

package.json

we want to use latest gui with smoke www

use scratch-gui @latest for smoke branch

---

src/views/microbit/l10n.json

an --> a 
(ps it wanst marked but im pretty sure it would be)

fix small typo

---

src/views/preview/project-view.jsx

Resolves: https://github.com/LLK/scratch-www/issues/2349
Include clearing the comments data when remixing projects.
Tested locally by remixing a project that had comments. See linked issue for full repro.

Remove comments when remixing, they do not exist on the new project

---

src/views/splash/hoc/middle-banner.jsx

A hotfix to fix #2370.
Fixes #2370
NOTE: It's a pr against master, since I saw it on real website.

[Master] No localhost allowed on HoC Banner

---

src/views/splash/hoc/top-banner.jsx

/cc @chrisgarrity @christanbalch

[Master] Add project data to adventure game tutorial

---

src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Fixes the issue where the endpoint was implemented out of spec 😉
Update the shape of the object returned from the visibility endpoint to conform to the server.

Use message instead of censorMessage for the censor message.

---

bin/configure-fastly.js

Reverts LLK/scratch-www#2373
Was breaking travis
/cc @chrisgarrity

Revert "Add tip_bar fastly config"

---

src/views/credits/people.json
src/views/credits/supporters.json

Not 100% sure the image path fix is right but it does seem to fix things in staging....
Fixes #2397 Fixes #2396.

Fix image path bug and capitalization CBs name.

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

In my last refactor I forgot to ensure non-admins _don't_ see the pane on the project pagel.  I also screwed up the width of the panel somehow. This fixes those issues.

Fix admin panel visibility and style

---

src/views/preview/project-view.jsx

My linter doesn't catch prop order for some reason. So fix linting so the build works.

Fix lint issues

---

src/views/preview/project-view.jsx

From testing: Show addToStudio for all logged in users on shared projects

Show addToStudio for all logged in users on shared projects

---

src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Fixes an issue where admins could not disable comments.

Allow admins to toggle comments

---

src/components/page/www/page.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

/ht @paulkaplan for the idea to move it below the nav bar.

Don't occlude page content with the admin panel

---

src/views/preview/l10n.json
src/views/preview/presentation.jsx

Fixes #2432 
Translate the placeholders.

Translate placeholder

---

src/lib/project-info.js
src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

Scratch 3 project implementation of the warnings for cloud vars when you are logged out or username block when you are logged in.

Show username and cloud var alerts on projects that use them.

---

src/views/preview/preview.scss

Resolves https://github.com/LLK/scratch-www/issues/2203
CSS to make placeholder text in instructions, credits vanish (and reappear) when those textareas are clicked on (or blurred)

Placeholder text go away

---

src/views/preview/preview.scss

Fixes https://github.com/LLK/scratch-www/issues/2411
Makes the remix button spin the (galacticly accurate) direction.

Make the remix button spin the correct the direction

---

src/components/thumbnailcolumn/thumbnailcolumn.jsx
src/views/preview/remix-list.jsx

Fixes https://github.com/LLK/scratch-www/issues/2444
Makes the itemType `projects` so that the URLs are correct

Fix hard-coded /preview/id url for remix list.

---

static/svgs/project/studio-add-white.svg

Resolves https://github.com/LLK/scratch-www/issues/2466
/cc @carljbowman

Update add to studio icon

---

src/views/preview/comment/comment.scss
src/views/preview/extension-chip.scss
src/views/preview/mod-info.jsx
src/views/preview/mod-info.scss
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/stats.scss
src/views/preview/subactions.scss

Probably worth looking at the commits one by one, but mostly minor CSS changes.
Only code change is reordering the mod info below the extension chips.

Minor style fixes to the project page

---

src/views/preview/project-view.jsx

This way it will take us to where we expect on staging and production.
Resolves #2296
Companion to https://github.com/LLK/scratch-gui/pull/4039

Hook up onClickLogo in GUI

---

src/views/teachers/landing/landing.scss

minor educator pages fixes

---

src/components/modal/addtostudio/modal.scss

Resolves https://github.com/LLK/scratch-www/issues/2360
Reorder some of the heights to fix the scrolling behavior

Fix scrollbars for add-to-studio modal

---

src/views/teachers/landing/l10n-static.json
src/views/teachers/landing/landing.jsx

Fixes #2421 
Updates the links to not be hard coded. That was the last thing on the list to fix this issue!

Add proper links to cards and guides instead of hard coding them.

---

.tx/config

Also remove cards view.
I've already pushed the update manually, this change ensures that the next time someone syncs translation sources it'll be the correct set.

Add ideas page to tx/config, and remove cards view

---

src/views/splash/presentation.jsx

fixes #2493 
Just link to the editor without a tutorial id

Remove tutorial for logged in users.

---

package.json
src/views/preview/stats.jsx

Resolves https://github.com/LLK/scratch-www/issues/2496

Remove approx liking/favoriting format

---

src/views/preview/mod-info.jsx
src/views/preview/mod-info.scss
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
static/svgs/project/username.svg

Resolves https://github.com/LLK/scratch-www/issues/2503
Adds author's username to Moderation Info section of project page
None.

added author username to moderation info area

---

src/components/crashmessage/crashmessage.jsx
src/components/errorboundary/errorboundary.jsx
src/l10n.json

@colbygk @rschamp equivalent of https://github.com/LLK/scratch-gui/pull/4151 for www.

Show error ID and report React errors to Sentry

---

src/lib/storage.js

Fixes https://github.com/LLK/scratch-www/issues/2522
Updates the storage in www to mirror the changes made by @rschamp in https://github.com/LLK/scratch-gui/commit/5c83d603d6ece1fc2c97d7fc0233799bdf4d8a22#diff-5aebe64595405c2eb4c5b85385a51da2 for GUI.

Update storage to get 3.0 projects.

---

src/template.ejs

thanks @picklesrus for this idea, i'll revert this once we confirm GA is working correctly when connected with GUI

[REVERT ME] Turn up GA sampling to 100% for testing on staging

---

src/routes.json

Master version of https://github.com/LLK/scratch-www/pull/2560

[MASTER] Fix the regexp that allows for query params on faq and download

---

src/views/preview/project-view.jsx

Fixes an issue where every time you click the green flag a POST is made against the API. only do that once per session.
/cc @rschamp, tested locally.

[Master] Only track green flag once

---

src/views/splash/presentation.jsx
src/views/splash/splash.jsx

Master version of https://github.com/LLK/scratch-www/pull/2569
/cc @thisandagain

[Master] remove project count api request

---

src/components/modal/addtostudio/modal.scss

Resolves #2566 
Makes more font choices so that serif doesn't display on devices

Fix font in add to studio modal

---

package.json

Update to bring in one of the bluriness fixes

Update to latest GUI to partially fix bluriness

---

package.json

Bump scratch-gui

---

src/lib/decorate-text.jsx

[Develop] Fix hashtag search

---

src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/remix-list.jsx
src/views/preview/studio-list.jsx

[Develop] Show link to view all remixes on project page

---

src/views/preview/presentation.jsx
src/views/preview/preview.scss

fixes #2605 
restores the character limit to 5000, and ensures that the validation error message is visible when the limit is exceeded

restore 5000 character limit for description fields

---

src/lib/api.js
src/redux/preview.js
src/views/preview/project-view.jsx

Counterpart of master PR https://github.com/LLK/scratch-www/pull/2615

[Develop] love and favorite proxy, and use x-requested-with header

---

package.json

Bump GUI version to bring in asset saving race condition fixing

---

package.json

Bump scratch-gui to bring in renderer and audio fixes

---

src/l10n.json
src/lib/supported-browser.js

Reverts LLK/scratch-www#2630
We are going to take a softer approach on this, @thisandagain will follow up with an issue

Revert "Check for recommended browser version"

---

src/components/not-available/not-available.jsx

Resolves #2607 
Wear a helmet! (to set title)
Build and lint successful

Set title for 404 pages

---

package.json

Bump GUI to bring in unsupported browser error states

---

package.json

Bump GUI to bring in performance and BSOD fixes

---

test/localization/check_valid_json.js

Reduces the spam in Travis for visibility
Approved by @chrisgarrity in person
/cc @thisandagain @benjiwheeler

Don't create a separate test for each l10n json

---

src/components/modal/addtostudio/modal.scss
src/components/modal/addtostudio/presentation.jsx
src/components/modal/addtostudio/studio-button.jsx
src/views/preview/add-to-studio.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
src/views/preview/subactions.jsx

Reverts LLK/scratch-www#2682
We saw unexpected errors and realized there were missing cache invalidations.

Revert "Add to studio modal should only show studios user can actually change"

---

src/views/credits/credits.jsx

Resolves #2681 
If the logoDistination is null, don't link.

Don't link if destination is null

---

src/components/modal/addtostudio/modal.scss
src/components/modal/addtostudio/presentation.jsx
src/components/modal/addtostudio/studio-button.jsx
src/views/preview/add-to-studio.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
src/views/preview/subactions.jsx

Reverts LLK/scratch-www#2693
Since @colbygk and I tracked down the bug causing unexpected 403 errors on the backend, we're ready to give this another try!

Revert "Revert "Add to studio modal should only show studios user can actually change""

---

src/views/preview/formsy-project-updater.jsx
src/views/preview/l10n.json
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/preview/project-view.jsx

[Master] Wrap project inputs to show server validation

---

src/views/preview/formsy-project-updater.jsx

See https://github.com/LLK/scratch-www/pull/2718 for description

[master] Pass updates up from project updater to top-level redux store

---

src/views/about/about.jsx
src/views/about/about.scss

Resolves #2611 
Changes the video. (Also small fix for ideas/credits links)
Due to the autoplay setting (Wistia side), it starts without doing anything. I'm not sure if I should use the way on splash, so I just added Video.
Build and test passed

About video

---

package.json

Fix issue where loading the editor in non-english would show some toolbox blocks in english.
https://github.com/LLK/scratch-gui/issues/4476

[Master] Bump GUI to fix loading editor in different language

---

package.json

Bump GUI to bring in VM and file export fixes

---

src/redux/navigation.js

Fixes https://github.com/LLK/scratch-www/issues/2516
This fixes an issue where you could get logged out but then remain on your page by dismissing the window.onbeforeunload prompt when you have unsaved changes. That would put you in a state where you looked logged in but could not save.
Use a dummy form instead of changing the markup to allow callbacks to be passed into components the same way as before, making it more react-y. …

Use a dummy form submission instead of logging out via xhr.

---

src/views/privacypolicy/privacypolicy.jsx

_Resolves Issue https://github.com/LLK/scratch-www/issues/2781_
Changes the Privacy Policy under the "How does the Scratch Team protect my personal information?" section according to the Issue.

Updating Privacy Policy

---

package.json
src/redux/navigation.js
src/views/preview/censored-message.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

Features
- GIF import support for sprites and costumes
- Multiple file import support for sprites, costumes, backdrops and sounds
- Farsi and Central Kurdish language support
Bugfixes
- Fix issue where you could be logged out but remain on the project page
- Fix issue where the message shown on community censored projects was inaccurate
- Fix issue where you could activate a button in the toolbox by dropping a block over it
- Fix issue where the "ask" text input would go behind monitors on the stage
- Fix issue where sliders that used to have a 1/100th step size in scratch 2 would become step size of 1

Release 02/13/2019

---

src/views/faq/faq.jsx
src/views/faq/l10n.json

Resolves #2708
Change the text so that it does not refer to section which does not exist

Don't refer to a section which does not exist

---

package.json

Brings in this fix https://github.com/LLK/scratch-gui/pull/4564

Update GUI to bring in toolbox refresh fix

---

src/views/jobs/moderator/moderator.jsx

_Changed: "Not required, but would be cool: Ability to speak another language." to "Not required, but would be cool: Ability to read and write another language."._
Based on this issue: https://github.com/LLK/scratch-www/issues/2768

Update moderator requirements.

---

src/routes.json
src/views/starter-projects/l10n.json
src/views/starter-projects/starter-projects.json
src/views/starter-projects/starter-projects.jsx
src/views/starter-projects/starter-projects.scss

Resolves #2744 
Migrates the starter projects page to scratch-www.

Migrate Starter Projects

---

webpack.config.js

Same fix as https://github.com/LLK/scratch-gui/pull/4627, but for www's use of scratch-parser

Run pify package through babel loader

---

package.json
src/routes.json
src/views/jobs/moderator/moderator.jsx
src/views/starter-projects/l10n.json
src/views/starter-projects/starter-projects.json
src/views/starter-projects/starter-projects.jsx
src/views/starter-projects/starter-projects.scss
test/integration/smoke-testing/test_footer_links.js
webpack.config.js

Features
- Updated starter projects page
- Several performance improvements for project loading
- Add "Coming Soon" preview for LEGO Boost extension
Bugfixes
- Fix for projects not loading when they have certain control characters in blocks/costume names.
- Update the scratch-link icon in the hardware connection flow to match the current version.

[Master] Release 03/07/2019

---

package.json

Features
- Slider monitors min/max/step-size can be changed via right-click menu on the monitor. (credit to @apple502j)
- Renaming custom block inputs will automatically update argument reporters in the define stack.
- Performance improvements around lazy evaluation of code.
Bugfixes
- Fix for issue where changing inputs on a custom block would cause detached empty text blocks.
- Fix issues around sending too many commands to hardware extensions.

[master] Release 03/14/2019

---

package.json

Release Notes
- Fix issue where panning the costume editor with the trackpad or mouse wheel while you have a brush/eraser tool selected would make the brush/eraser preview circle disappear. 
- Add seven new languages to Text to Speech extension (Chinese (Mandarin), Korean, ~Hindi~, Swedish, Norwegian, Romanian, Turkish, Welsh)
https://github.com/LLK/scratch-vm/pull/2046 (note Hindi was removed, not ready yet)
- Device Scan fixes
- Point in direction block doesn't accept text inputs.

[Master] Release 03/21/2019

---

package.json

Release -> master here: https://github.com/LLK/scratch-www/pull/2855

[DEVELOP] Release/03 21 2019

---

src/redux/preview.js
src/views/preview/project-view.jsx

Reverts changes to comments and studios endpoints, so that we can deploy the 4/4/19 release without deploying API.

[master] Hotfix/revert comments studios urls

---

package.json

[Develop] Hotfix/fix asset id of null

---

package.json

[master] Hotfix SVG renderer parsing issue

---

package.json

Bump scratch-gui dep

---

bin/build-locales
src/views/conference/2019/index/index.jsx
src/views/conference/2019/index/index.scss
src/views/conference/2019/index/l10n.json

Resolves https://github.com/LLK/scratch-www/issues/2761
* revise title of chile conference
* revise description of chile conference
* revise link to eu conference page
* postpone kenya conference with new description
* remove kenya location/date/etc. section
* move kenya section to bottom

revised conference page to postpone kenya, change sur title, eu desc

---

custom-locales.json

fix missing locale data for rapa nui

Add rapa nui to www custom locales

---

package.json

pull in new gui with fixes for rapa nui

Rapanui fixes

---

package.json
src/components/navigation/www/navigation.jsx
src/views/preview/presentation.jsx
src/views/preview/preview.scss
src/views/search/search.jsx
src/views/teachers/landing/landing.jsx
test/integration/selenium-helpers.js
test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_search.js

* Surprise sprite button never gives you a letter or number sprite
* Change to how scratch-storage works: we now fetch assets in a web worker, and we are no longer caching every asset in JS memory
* Fix alignment of remix credit avatar, text
* SVGs containing an invalid mime type should still load
* Search page should not break anymore
Two older changes to scratch-render, which are only now making it in:
* Clicking on a sprite is accurate even with graphical effects
* Pen transparency fix: Clears the pen framebuffer with transparent black instead of transparent white so transparent parts of the pen layer don't show up lighter than they should anymore.

[Master] Release/05-23-2019

---

src/views/download/download.jsx

Points download.jsx to new scratch-desktop file on S3

[Develop] Hotfix: update scratch-desktop link #3008

---

package.json

[RELEASE] Update scratch-gui

---

package.json

* Translation extension has been updated.
* The menu of languages shows only languages that are supported by both Scratch 3.0 and Google Translate
* Fix language code mapping bugs (e.g. es_419: reporter will report 'Spanish' not the locale code)
* Sound tile updates the duration when something the user does in the editor changes the length of the sound (e.g. echo)
* Library (costumes, sounds or sprites) modals appear immediately with a 'loading' spinner before the resources are loaded.

[Master] Release 2019-06-13

---

package.json

Pull in latest changes from scratch-gui.

Pull in latest scratch-gui

---

Makefile

Add options anywhere we run tap to make it work as it did previously

update makefile for new tap

---

package.json

Update scratch-gui to hotfixed version
Includes new tutorials and sprite library updates for ACW

[Master] Hotfix for Africa Code Week resources

---

src/components/modal/join/modal.jsx
src/components/modal/join/modal.scss
src/components/navigation/www/navigation.jsx
src/components/registration/scratch3-registration.jsx

Initial step towards resolving https://github.com/LLK/scratch-www/issues/3053
introduces stub components for new scratch3 join modal

introduce stub components for new scratch3 join modal

---

src/components/card/card.jsx
src/components/card/card.scss
src/components/forms/validation-message.scss

Resolves:
Changes:
Moves validation message css from card to own file, so it can be used in forms not in Cards

Moved validation message css from card to own file

---

src/components/join-flow/join-flow.jsx
src/components/modal/join/modal.jsx

Resolves:
Changes:
stub for join-flow component within modal

stub for join-flow component within modal

---

package.json
src/components/join-flow/join-flow.jsx
src/components/registration/join-flow-steps.jsx

Adds formik dependency, adds join flow steps file using formik

added formik dependency, join flow steps using it

---

src/components/formik-forms/formik-input.jsx
src/components/forms/validation-message.jsx

Adds initial formik input component, form validation message component that goes with it

added initial formik input component, form validation message component

---

src/components/join-flow/join-flow-step.jsx
src/components/join-flow/join-flow.jsx
src/components/join-flow/next-step-button.jsx
src/components/registration/join-flow-steps.jsx

* introduces join-flow-step component
* introduces next-step-button component
* moves join-flow-steps from registration dir to join-flow dir

introduce join-flow-step, next-step-button

---

package.json

Update scratch-gui to hotfixed version
Includes new tutorials and sprite library updates for ACW

[Develop] Hotfix for Africa Code Week resources

---

src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow.jsx

moves join-flow-steps.jsx from registration dir to join flow dir

moved join-flow-steps to join flow dir

---

test/integration/smoke-testing/test-join.js

Resolves https://github.com/LLK/scratch-www/issues/3078
Adds test to check that join window shows scratchr2 join flow.

added test to check that join window shows scratchr2 join flow

---

test/integration/smoke-testing/test-my-stuff.js
test/integration/smoke-testing/test_project_page.js
test/integration/smoke-testing/test_signing_in_and_out_homepage.js

Several tests frequently, but irregularly, failed when run on travis.  
This skips those flakey tests so we can fix them later.  This will allow us to treat failed tests as failures rather than ignoring them.

Skip tests that occasionally failed on travis

---

src/components/formik-forms/formik-input.jsx

Corrects the way that we pass message text to the ValidationMessage component.

fix passing text to validation message

---

src/components/join-flow/join-flow-steps.jsx
src/lib/validate.js
test/unit/lib/validate.js

Adds form code and handlers to make username/password step of join flow work.

working username step of join flow

---

package.json

Develop version of #3101 hotfix to correctly show an error when projects fail to save

[Develop] Hotfix for asset saving errors

---

src/components/modal/addtostudio/presentation.jsx
src/components/modal/base/modal-title.jsx
src/components/modal/base/modal-title.scss
src/components/modal/base/modal.scss
src/components/modal/report/modal.jsx
src/components/modal/social/presentation.jsx

Resolves https://github.com/LLK/scratch-www/issues/3106
Introduces `ModalTitle` component, which contains its own styling instead of having its styles referenced by other components, out of scope.

created ModalTitle component

---

src/components/formik-forms/formik-input.jsx
src/components/forms/row.scss
src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow-steps.scss
src/components/modal/base/modal-inner-content.scss

Resolves https://github.com/LLK/scratch-www/issues/3115
* Adds `validationClassName` parameter to `FormikInput` component
* Set formatting of validations in join flow using `validationClassName`

Format and position validation error messages in join flow

---

src/components/formik-forms/formik-input.jsx
src/components/forms/row.scss
src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow-steps.scss
src/components/modal/base/modal-inner-content.scss

Revert "Format and position validation error messages in join flow"

---

package.json
src/components/formik-forms/formik-input.jsx
src/components/forms/row.scss
src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow-steps.scss
src/components/modal/base/modal-inner-content.scss

Revert 3116 format validation

---

src/components/join-flow/join-flow.jsx

In `join-flow.jsx`, track the current step in the flow, and pass function to steps for advancing to next step.

handle join flow state for tracking, advancing current step

---

src/components/formik-forms/formik-select.jsx

Introduce `formik-select.jsx` component, modeled on `formik-input.jsx` but handling an `options` prop

introduce formik select component

---

src/components/join-flow/join-flow-step.jsx
src/components/join-flow/join-flow-step.scss
src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow-steps.scss
src/components/join-flow/next-step-button.jsx
src/components/join-flow/next-step-button.scss
src/components/modal/base/modal-title.scss

* introduce `join-flow-description` class 
* add `join-flow-steps.scss` to stylize join flow form
* improve formatting of "Next step" button

Improve formatting of join flow title, description, next step button

---

package-lock.json

Fixes build from missing package lock update

update package lock to fix the build

---

src/components/formik-forms/formik-select.jsx
src/components/join-flow/birthdate-step.jsx
src/components/join-flow/join-flow-step.jsx
src/components/join-flow/join-flow-step.scss
src/components/join-flow/join-flow-steps.jsx
src/components/join-flow/join-flow-steps.scss
src/components/join-flow/join-flow.jsx
src/components/join-flow/username-step.jsx

* introduce join flow birthdate step
* localize birth month strings
* set initial values to header strings
* layout select elements to roughly match design spec
* add header image (particular image TBD)
* validate birthdate before continuing

Join flow add birth date step

---

package-lock.json
package.json

- Fix an issue where custom procedure parameters were getting their values read as 0 if used more than once inside a custom procedure definition.

[MASTER] - Hotfix regression with custom procedure parameters

---

src/components/join-flow/join-flow-step.scss
src/components/join-flow/join-flow-steps.scss

* corrects width of select components in birthdate step
* corrects vertical spacing of descriptions in join flow

Join flow design tweaks

---

src/views/preview/comment/comment.jsx

Resolves https://github.com/LLK/scratch-www/issues/3129
Provides `key` props for reply comments, and top level comments

provide key to comments

---

README.md

Resolves https://github.com/LLK/scratch-www/issues/3187
Update translation command in README to `npm run translate`

update translation command to npm run translate

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190731154138

---

src/components/registration/registration.jsx
src/components/registration/registration.scss

This is needed for https://github.com/LLK/scratchr2/pull/5417. It can be deployed independently.

[Master] Adjust height when displaying reCAPTCHA challenge

---

src/components/join-flow/join-flow-steps.scss
src/components/join-flow/join-flow.jsx
src/components/join-flow/welcome-step.jsx
src/l10n.json

Add instructions string with email prop to join flow welcome step

add instructions text to join flow welcome step

---

bin/configure-fastly.js

[Master] Add concurrency limits to async Fastly API requests

---

src/views/preview/project-view.jsx

develop version of https://github.com/LLK/scratch-www/pull/3211
Not sure why this includes the previous hotfix commits, this branch was based on master...

[Develop] Hotfix/report project thumbnails

---

package.json

Brings in new version of scratch-vm

Update scratch-gui to new release

---

package.json

I ran into this problem (the build just hangs and times out on 
travis)trying to add a new view. It was unintentionally removed as part 
of 
https://github.com/LLK/scratch-www/pull/3137#pullrequestreview-273869913.
Thanks to @paulkaplan for finding it.

Add back the max_old_space_size flag.

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190812124346

---

package-lock.json
src/routes.json
src/views/join/join.jsx

Page that contains the Join Flow modal.
Before committing I need to setup a config so this isn't visible in production. I want to double check that we're all in agreement about where this page should live too.  I put it on the agenda for our Tuesday meeting.

Standalone join flow page.

---

src/components/info-button/info-button.jsx
src/components/info-button/info-button.scss
src/components/join-flow/birthdate-step.jsx
src/components/join-flow/gender-step.jsx
src/components/join-flow/join-flow-step.jsx
src/l10n.json
test/unit/components/info-button.test.jsx

* format info button in join flow 
* use info button in birthdate step, gender step
* add strings for the above
1. in a follow up, we should replace the css/text-formatted question mark with an svg to make the appearance more consistent
2. note that the placement of the info button can be weird if it happens to make the text wrap right there... not sure what to do about that

Join flow info button

---

src/components/formik-forms/formik-checkbox.jsx
src/components/formik-forms/formik-checkbox.scss
src/components/formik-forms/formik-forms.scss
src/components/formik-forms/formik-radio-button.jsx
src/components/formik-forms/formik-radio-button.scss
src/components/join-flow/join-flow-steps.scss
src/components/join-flow/username-step.jsx

* adds formik checkbox component
* makes username step of join flow have checkbox by "Show password"
* standardize the formatting of formik labels
Doesn't seem like any of this is testable, really...

Add formik checkbox component, Show password checkbox

---

test/unit/components/join-flow-step.test.jsx

Now that we have enzyme, add unittest tests for join flow component.
That's all it does :D

Add unittest for JoinFlowStep.

---

package-lock.json
package.json

updated gui

---

src/components/join-flow/gender-step.jsx
src/l10n.json

Step towards resolving #3053 
Adds "Non-binary" option to gender select in new join flow

add nonbinary option to gender step of join flow

---

src/components/formik-forms/formik-checkbox.jsx
src/components/formik-forms/formik-checkbox.scss
src/components/formik-forms/formik-input.scss
src/components/formik-forms/input.scss
src/components/join-flow/email-step.jsx
src/components/join-flow/join-flow-steps.scss
src/l10n.json

* updates wording of terms of use message
* updates wording of "Create Your Account"
* adds checkbox for email subscribing
* formats email placeholder
* makes checkbox label able to be formatted -- not actually needed here, but an improvement
* speeds up css transitions for checkbox, so tabbing in and out of focus feels more responsive
None -- not sure how to test email step

Join flow email improvements

---

package-lock.json
package.json

Hotfix of https://github.com/LLK/scratch-gui/pull/5106 to fix https://github.com/LLK/scratch-gui/issues/5105.
This corresponds to the GUI build of https://github.com/LLK/scratch-gui/tree/hotfix/svg-renderer
Merge https://github.com/LLK/scratch-gui/pull/5106 before merging this to make sure things stay consistent

[Master] Update scratch-gui to hotfix renderer

---

test/unit/components/formik-input.test.jsx
test/unit/components/formik-select.test.jsx

Add simple tests for a couple of Formik components.

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190819150121

---

src/components/formik-forms/formik-input.jsx
src/components/formik-forms/formik-radio-button.jsx
src/components/join-flow/gender-step.jsx

* gets ref to custom gender input
* if custom gender option is clicked on, focuses cursor on input field
* corrects incorrect `htmlFor` value in `formik-radio-button` pointed out by @paulkaplan in https://github.com/LLK/scratch-www/pull/3178#discussion_r310618224
n/a

Join flow gender custom focus

---

src/components/join-flow/birthdate-step.jsx
src/components/join-flow/country-step.jsx
src/components/join-flow/join-flow-steps.scss

* use "Country" instead of "select country" in country dropdown
* make width of birthdate description wider, so it doens't wrap
* add light hover color on gender radio options
n/a

Join flow misc UI improvements

---

src/components/join-flow/email-step.jsx
src/components/join-flow/welcome-step.jsx

* adds missing init values to email-step
* removes unnecessary init section from welcome step

add missing initial values, remove unnecessary one

---

src/views/credits/credits.jsx

Update "Other Contributors" section to remove person at their request.

Update credits page

---

src/views/microbit/microbit.jsx

Proposed fix to make the microbit pdf download open in a new tab
Made this PR against the release branch for testing before release

Use new tab for PDF download button

---

src/views/ideas/ideas.jsx

Changes string id to correct one, for "Download PDF" on ideas page

Add missing string

---

test/unit/components/email-step.test.jsx

Add a unittest for the EmailStep.

---

package-lock.json
package.json
src/components/formik-forms/formik-checkbox.jsx
src/components/join-flow/country-step.jsx
src/components/join-flow/email-step.jsx
src/components/join-flow/join-flow-steps.scss
src/components/join-flow/join-flow.jsx
src/components/join-flow/registration-error-step.jsx
src/components/join-flow/registration-error.jsx
src/l10n.json
test/unit/components/join-flow.test.jsx
test/unit/components/registration-error-step.test.jsx

* add yesno checkbox
* allow checkbox to be hidden
* add registration error, waiting prop to join flow steps
* use redux to dispatch session refresh
* call register function in join flow
* make join flow modal stay showing even when session is refreshed
none... are there tests we could add here?

join flow register user function, registration error component

---

src/components/join-flow/join-flow.jsx

Sends capatcha token to create new user request for new join flow

Add captcha token to ther request. It was left out of #3291.

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190916225740

---

src/components/join-flow/join-flow-steps.scss
src/components/join-flow/welcome-step.jsx

Changed vertical spacing in Welcome step, made it flexible for localization:
Before:
After:

fix welcome vertical spacing in Welcome step, make it flexible for localization

---

src/components/formik-forms/formik-input.jsx
src/components/formik-forms/formik-input.scss
src/components/join-flow/birthdate-step.jsx
src/components/join-flow/country-step.jsx

* Makes text input boundaries darker, 20% of normal gray instead of 10%
* Slightly lightens input placeholder text, from 75% of normal gray to 60%
* Makes text input background white, not light gray
* Made birtdate's Month and Year placeholders disabled as selectable options

Join flow placeholder fixes

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190918163722

---

src/views/teachers/landing/landing.jsx

Resolves #3379
Updates the link to Code Club

Update Code Club Link

---

src/components/join-flow/birthdate-step.jsx
src/components/join-flow/country-step.jsx

* in birthdate and country steps, when select dropdown is focused, clear any validation errors

when select dropdown is focused, clear any validation errors

---

src/components/join-flow/country-step.jsx
src/l10n.json

* changes placeholder for country to "Select country"

Join flow country placeholder

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20190925145604

---

src/components/modal/join/modal.scss

move join flow modal down in small window widths

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191001155549

---

src/components/formik-forms/formik-radio-button.jsx
src/components/join-flow/email-step.jsx
src/components/join-flow/join-flow-step.jsx
src/components/join-flow/username-step.jsx

Reverts LLK/scratch-www#3422
Sorry, I merged this erroneously!

Revert "turn off automplete and autocorrect for join-flow inputs"

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191009140622

---

src/views/faq/l10n.json

ChromeOS/Android is not released yet, so don’t mention in the FAQ yet.

Remove reference to Chrome/Android in FAQ

---

package-lock.json
package.json

Hotfix the two VM updates that fix video motion:
1. Fix transparency so that 100% transparent is not visible for the video layer
2. Fix the video detection code so that updates to sprite positions are propagated correctly.

[Master] Hotfix video motion fixes

---

src/routes.json

Resolves #3390 - add shortcut redirects for HOC tutorials
/cc @kosiecki17 @ntlrsk @zoebentley

[Master] Add redirects for Make it Fly and Imagine If tutorials

---

src/components/intro/intro.jsx
src/components/navigation/www/navigation.jsx
src/redux/navigation.js
test/unit/components/navigation.test.jsx
test/unit/redux/navigation.test.js

makes join button on splash page either open existing join flow, or (if flag set to true) navigate user to /join.

splash page join button works with new join flow

---

package-lock.json
package.json

Pull in latest changes from scratch-gui.

Greenkeeper/scratch gui 0.1.0 prerelease.20191021202911

---

src/routes.json

Redirect link for Code a Cartoon, which opens editor with project containing Cartoon Network assets.
Redirect for Talking Tales tutorial

HoC Redirect to Talking Tales and Code a Cartoon

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191031171928

---

package-lock.json
package.json

Greenkeeper/eslint plugin json 2.0.1

---

package-lock.json
package.json

brings in LLK/scratch-svg-renderer#84 via scratch-gui

Greenkeeper/scratch gui 0.1.0 prerelease.20191102003322

---

src/components/join-flow/email-step.jsx
test/unit/components/email-step.test.jsx

Corrects misspelled join flow intl id
Updated tests

correct misspelled join flow intl id

---

src/lib/validate.js
test/unit/lib/validate.test.js

revise, add to join flow username validation tests
added test for underscore; revised username local tests to make them clearer

revise join flow username validation tests

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191105010907

---

src/components/join-flow/username-step.jsx

Resolves https://github.com/LLK/scratch-www/issues/3511
Removes truncation of password and passwordConfirm input values, effectively allowing them to be any arbitrary length
None, this area did not have tests written

remove truncation of password, passwordConfirm

---

src/components/join-flow/username-step.jsx

Fix of something broken in #3512

Put the right value in the password field. This got mixed up in #3512.

---

src/redux/navigation.js
test/unit/redux/navigation.test.js

Flag flip to switch links in navbar to point to /join.

Roll out new Join Flow.

---

src/components/join-flow/welcome-step.jsx
src/redux/navigation.js
test/integration-legacy/smoke-testing/test-join.js
test/unit/redux/navigation.test.js

Enables new join flow
Points link at the end of the flow to the homepage

[Master] Hotfix/join flow 

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191119160115

---

src/lib/feature-flags.js

Features:
- Show ChromeOS and Android options in download and extension pages

HOTFIX [master] Enable feature flag for chrome app download

---

src/lib/feature-flags.js

Develop version of https://github.com/LLK/scratch-www/pull/3549
Will remove the tech debt around the feature flag https://github.com/LLK/scratch-www/issues/3548 in regular release cycle

HOTFIX [develop] Enable feature flag for chrome app download

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191120175131

---

package-lock.json
package.json
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

In most cases, resolves the error screen seen when creating, remixing, or copying projects when our databases are experiencing replication lag.  If the lag is longer than 7.5s, the behavior remains the same (appears broken).
Makes sure api can get the project before considering the project create to be complete. We ought to refactor gui and www so that we can use the project data we get back from the project create instead.
_Please …

[Master] Work around replication lag problems on project creation

---

src/routes.json

[Develop] Support url parameters for 3 redirects

---

src/components/page/www/donor-recognition.jsx
src/components/page/www/donor-recognition.scss
src/components/page/www/page.jsx
src/l10n.json
src/views/credits/credits.jsx
src/views/splash/splash.jsx
test/unit/components/page.test.jsx

Adds a prop to the Page component so each page can say whether or not it 
wants them to appear.

Add recognition text and links to the bottom of the page.

---

src/components/page/www/donor-recognition.jsx

add a missing t.

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191210153720

---

package.json

Bump GUI version to fix render bug.

---

package.json

Fixes bug in scratch-svg-renderer

[MASTER] Hotfix/render bugfix

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20191217220616

---

package-lock.json
package.json

Pull in latest changes from scratch-gui.

Greenkeeper/scratch gui 0.1.0 prerelease.20191227193508

---

src/lib/validate.js
test/unit/lib/validate.test.js

count unicode characters as single characters
added tests for unicode; split tests up to be clearer

count unicode characters as single characters

---

src/redux/messages.js
src/redux/splash.js

https://github.com/LLK/scratch-www/issues/2103
* fixes error messages that erroneously mentioned session, to instead describe more accurately what's going on!
Note that these still don't seem to be actually logged anywhere.

corrected error messages that wrongly mentioned session

---

.travis.yml

Reverts LLK/scratch-www#3651
Something about this travis yml seems to have been malformed -- possible the two-word stage name?

Revert "attempt to get travis cron job to only run translations"

---

.travis.yml

Reverts LLK/scratch-www#3656
@chrisgarrity and I determined that the problem was in the stage section, where we had added a conditional to the `test` stage; need to explicitly specify that `test` is the `name` of the stage.

Revert "Revert "attempt to get travis cron job to only run translations""

---

package.json

Fix to https://github.com/LLK/scratch-www/pull/3643 which points to the correct path for the new tx-push-www script

correct file location of tx-push-www script

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20200129184440

---

.travis.yml
package-lock.json
package.json
src/components/languagechooser/languagechooser.jsx
src/init.js
src/views/preview/project-view.jsx

[Master] Release/2020-01-29

---

package-lock.json
package.json

Update gui dep

---

package-lock.json
package.json

Bring in round gradient strokes in 2.0 projects for compatibility

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20200210182220

---

package-lock.json
package.json

Update gui to bring in paint centering fade update

---

package-lock.json
package.json

Update to the latest scratch-gui

Update to the latest scratch-gui

---

package-lock.json
package.json

- It’s now easier to center selections in the paint editor (Thanks in part to adroitwhiz!)
- Gradient-stroked lines from 2.0 now have rounded corners again (Thanks adroitwhiz!)

[Master] Release 2020-02-13

---

package-lock.json
package.json

use latest version of gui and the latest l10n.

update gui version

---

package-lock.json
package.json
src/lib/validate.js

**Release Notes**
- Update asset library contents (many small fixes to sprites, costumes and backdrops)

[Master] Release/2020-02-27

---

package-lock.json
package.json

Update gui to bring in changes to pen line drawing

---

package-lock.json
package.json

pull in revert scratch render

---

src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json

Resolves #3708 
Removes request for proposal and adds links for registration and hotel information. Removes old strings.
Static content updates. But to confirm, compare the content and links to the PDF in #3708.

[Master] Update conference page to open registration

---

src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json

[Develop] Update conference page to open registration

---

src/views/preview/subactions.jsx
src/views/preview/subactions.scss

Hotfix version of this https://github.com/LLK/scratch-www/pull/3725 which was LG'd. I'll close that without merging when this is in.

[Master] hotfix reduce report prominence

---

src/views/preview/subactions.jsx
src/views/preview/subactions.scss

Develop version of https://github.com/LLK/scratch-www/pull/3726

[Develop] Reduce report prominence

---

src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json

Resolves #3708
Adds a line break to make the delay in registration more apparent.
Static content changes.

[Master] Split out message about conference registration delay

---

src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json

[Develop] Split out message about conference registration delay

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20200310205953

---

package-lock.json
package.json
src/components/helpform/helpform.jsx
src/components/informationpage/informationpage.scss
src/components/install-scratch/install-scratch.jsx
src/routes.json
src/views/contact-us/contact-us.jsx
src/views/contact-us/l10n.json

Release Notes:
- Migrate contact us page  from legacy

[Master] Release/2020 03 12

---

src/components/extension-landing/extension-requirements.jsx
src/components/install-scratch/install-scratch.jsx
src/views/download/download.jsx
src/views/ideas/ideas.jsx

Resolves #3748 
Adds `/` to all `<img>` tags' `src` attributes.
Manually tested and all images were shown (no 403)

Fix image links

---

src/components/modal/base/modal.scss
src/components/modal/report/form-step.jsx
src/components/modal/report/modal.jsx
src/components/modal/report/modal.scss
src/components/modal/report/report-options.js

Develop version of https://github.com/LLK/scratch-www/pull/3747

[Hotfix/Develop] Split project report flow into two steps

---

package-lock.json
package.json
src/components/extension-landing/extension-requirements.jsx
src/components/install-scratch/install-scratch.jsx
src/views/download/download.jsx
src/views/ideas/ideas.jsx

Bugfixes
- Images now load on several pages with a trailing `/` in their URLs (thanks @apple502j!)
- List monitors are now renamed when lists are renamed (thanks @apple502j and @adroitwhiz!)

[MASTER] Release/2020-03-18

---

package-lock.json
package.json

Bugfixes
- Images now load on several pages with a trailing `/` in their URLs (thanks @apple502j!)
- List monitors are now renamed when lists are renamed (thanks @apple502j and @adroitwhiz!)

[DEVELOP] Release/2020-03-18

---

package-lock.json
package.json

Pull in latest changes from scratch-gui

Greenkeeper/scratch gui 0.1.0 prerelease.20200325184934

---

src/components/captcha/captcha.jsx
src/components/join-flow/email-step.jsx
test/unit/components/captcha.test.jsx
test/unit/components/email-step.test.jsx

It'll get used in another spot later.

Move reCaptcha code to a component

---

package-lock.json
package.json

Update gui for Release 2020-04-09

update gui version for releae

---

src/views/splash/l10n.json
src/views/splash/presentation.jsx

Resolves #3709
Moves the two activity-related message from defaultMessage to l10n.json
You can run `npm run translate` and check `intl/splash.intl.js` manually.

Localize activity messages

---

src/views/credits/people.json

- Remove last names from people grid on credits page

[Master] Hotfix: Remove last names from credits page

---

package-lock.json
package.json
src/components/helpform/helpform.jsx
src/components/helpwidget/helpwidget.jsx
src/l10n.json
src/lib/feature-flags.js
src/lib/route.js
src/routes.json
src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json
src/views/contact-us/contact-us.jsx
src/views/contact-us/contact-us.scss
src/views/contact-us/l10n.json
src/views/splash/l10n.json
src/views/splash/presentation.jsx
src/views/studentregistration/studentregistration.jsx
test/unit/lib/route.test.js

Release Notes: 
Features
- Student usernames in lists of students are smaller, more readable
- Student sign-up URLs use new short format
- Update to the conference page
Bugfixes
- Default activity messages for new users are translated (Thanks @apple502j)

[Master] Release/2020 04 16

---

src/components/registration/steps.jsx
src/components/registration/steps.scss
src/l10n.json
src/views/studentregistration/studentregistration.jsx

Make the "don't use your real name" a blue info message and give some suggestions on how to choose a username.
Old version:

Change up the messaging in student registration. 

---

src/components/extension-landing/extension-requirements.jsx
src/components/install-scratch/install-scratch.jsx
src/components/os-chooser/os-chooser.jsx
src/l10n.json
src/lib/detect-os.js
src/lib/feature-flags.js
src/views/download/download.jsx
src/views/download/l10n.json

Resolves #3548 
(also resolves #3515 )
Removes CHROME_APP_RELEASED flag, and some unused l10n texts.

Remove app flag

---

package-lock.json
package.json

Fixes https://github.com/LLK/scratch-gui/issues/5678
Updates render to not redraw the stage if the canvas hasn't changed size
Tested manually

[Master] Update gui to fix flicker in firefox

---

src/views/splash/presentation.jsx

I made a mistake on previous PR and now I made a bug that causes actor to be invisible and the studio link to be wrong. This fixes the issue.

Fix invisible actor on FollowStudio

---

src/views/credits/people.json

It resolves #3820 
It adds new Scratch Team member Kait's name to the Credits page.

Add new member's name

---

package-lock.json
package.json

Merge develop into release

---

src/views/credits/people.json

Put the credits page in order by first names as opposed to last names which are no longer present.
Resolves #3813 by putting the credits page in alphabetical order by first name instead of last name
Rearranges people.json so that it's in alphabetical order by first name

Alphabetize the credits page

---

src/views/teachers/landing/l10n.json
src/views/teachers/landing/landing.jsx

Adds link to teacher account setup guide on the educator page where you sign up for an educator account.
I will double check the link destination is the final one before committing.

Educator page mini update

---

package-lock.json
package.json

Greenkeeper/scratch gui 0.1.0 prerelease.20200506191157

---

package-lock.json
package.json
src/components/registration/steps.jsx
src/views/contact-us/contact-us.jsx
src/views/studentregistration/studentregistration.jsx

**Release Notes**
Features
- Added new people to the sprite and costume libraries: Characters 1, Characters 2, Kia, Luca, Noor, Sasha, Tatiana, Taylor and Trisha
- Added support for Armenian language (հայուհի)
- Contact Us page uses a new help widget
- Add “Mean or Disrespectful” project report category
- Student's country selection automatically defaults to their educator’s country
Bug fixes
- Improvement to saving/exporting on iOS 12.x: now exports will open in a new tab, rather than taking over current tab
- Fix centering of stage in full-screen mode: the top of the stage will no longer be cut off, and there’s no longer a white line at the bottom of the stage
- “Color is touching color” now works properly on sprites with the ghost effect
- Latin-1 characters (letters with accents) now …

[Master] Release 2020-05-14

---

package-lock.json
package.json

Paint editor fills available space

[Master] Hotfix/stretchy paint

---

package-lock.json
package.json

Update gui to pull in latest VM

---

.github/CONTRIBUTING.md

Update contributor guidelines with new version from 3rd party contributor group

Update contributor guidelines with new version

---

README.md

Update README with link to new contributor guidelines

Add README link to contributor guidelines

---

.github/CONTRIBUTING.md
README.md
package-lock.json
package.json

* Renaming a variable now doesn’t break code running "(var) of (sprite)" sensing blocks
* The blue box that flashes around selected sprites now fits more tightly around the sprites
* Clicking on Code/Costume/Sound tabs will now work, even when alerts are showing
* Update dependencies

[Master] Release/2020-06-03

---

package-lock.json
package.json

Bring in revert svg-renderer

---

package-lock.json
package.json

Revert change to what happens when graphics effect is set to infinity

Pull in revert from vm via gui

---

package-lock.json
package.json

- Clicking and dragging sprites should be more efficient now (Thanks @Ryuurock!)
- In the pen color selector, if you set brightness or saturation to 0, and then away from 0, it should no longer change the color to red
- Think bubbles are now truncated to 2 decimal point precision, to match the say bubble behavior

[Master] Release 2020-06-17

---

package-lock.json
package.json
src/components/registration/steps.jsx
src/lib/country-data.js
test/unit/lib/country-data.test.js

- Pen blocks are no longer shown when the stage is selected, except for “erase all”
- Shapes should no longer get corrupted or disappear if you scale them to 0 width or height (Thanks @Jacco!)
- Reset “answer” and “timer” when you create or load a new project (thanks @apple502j!)
- Sprite tiles should now turn blue on Edge when you drag things into the sprite selector area
- Dragging sprites in the editor no longer causes the sprite to double up for a split second
- The fill color selector should no longer turn white after selecting mixed gradients

[Master] Release 2020-06-24

---

src/views/download/l10n.json

Resolves #3802
Adds iconAltText to l10n json

Add iconAltText

---

src/components/join-flow/username-step.jsx

Resolves #3850 by changing the way new users' usernames are handled.
The way new users' usernames are currently handled changes.

Change the way usernames are handled

---

src/routes.json

One step toward https://github.com/LLK/scratchr2/issues/5720 and eventually removing the code.

Redirect the old join flow to the new one.

---

package-lock.json
package.json

Reverts LLK/scratch-www#4195
It has <<< HEAD tags and whatnot in the package-lock.

Revert "Update gui"

---

test/integration-legacy/smoke-testing/test_footer_links.js

Pull in fix to footer test

---

package-lock.json
package.json
src/lib/jar.js
test/integration-legacy/smoke-testing/test_footer_links.js
test/unit/lib/jar.test.js

Release notes:
Bug fixes
* Pen dots no longer appear as large, blurry circles on certain Apple devices (“huge thanks” to Apple)
* “Touching sprite” is around twice as fast and “touching color” is around 50% faster
* You now won’t add points in reshape mode unless you click near the blue outline highlight

[Master] Release/2020-07-30

---

package-lock.json
package.json
src/components/thumbnail/thumbnail.scss

Release Notes:
Bug fixes
- Touching color works better with the pixelate effect (thanks @adroitwhiz!):
https://github.com/LLK/scratch-render/issues/573
- Touching color works better with color and brightness effects (thanks @adroitwhiz!)
https://github.com/LLK/scratch-render/issues/578
- Dragging sprite tiles in RTL to reorder them is less broken (thanks @noamraph!)
https://github.com/LLK/scratch-gui/issues/6020
- Fixed issues with outlines showing the incorrect width when one of the gradient colors is transparent
- Use ... instead of truncating strings on project titles in carousels (thanks @R4356th!)

[master]Release/2020 08 20

---

package-lock.json
package.json

Bug fixes
- Video sensing extension detects motion (thanks @apple502j!)
- Say and think bubbles should no longer count when using touching color blocks (thanks @adroitwhiz!)
- Touching a transparent background will now consistently count as touching white (thanks @adroitwhiz!)

[Master] Release/2020-08-27

---

package-lock.json
package.json

The release broke something with touching mouse pointer.
Reverts LLK/scratch-www#4359

Revert "[Master] Release/2020-08-27"

---

test/integration/my-stuff.test.js
test/integration/selenium-helpers.js

Makes the my-stuff tests pass when running using saucelabs
Updates how the "Expect" statements work so that they correctly work in async functions.

Fix my stuff tests

---

package-lock.json
package.json

Separate video motion fix from the release

[Master] Bring in video motion fix

---

package-lock.json

Release notes:
Features:
* When adding a gradient to a transparent color, the color now changes to a black to white gradient
Bug fixes:
* When switching to the ellipse/rectangle tools, the color should no longer sometimes show the three circles
* The stroke color should show up as transparent if the outline width is 0
* When touching a transparent backdrop, sprites should consistently report that they’re touching white
* Touching color should not detect say/think bubbles
* Previously if you uploaded a large gif or a lot of sounds, and switched sprites while they were uploading, some of the uploads would end up on the second sprite. Now they should all be attached to the original sprite.
* When reordering asset tiles in RTL, the asset is now visible

[Develop] Release/2020-09-03

---

package-lock.json
package.json

- Update translations in scratch blocks

[Master] Hotfix - Update Blocks Translations 2020-09-09

---

package-lock.json
package.json

Bring in hotfix changes back into develop.

[Develop] Hotfix - Update Blocks Translations  2020-09-09

---

package-lock.json
package.json
src/routes.json

Release notes:
Features:
* Add Getting Started video in 7 languages
* Add redirects for Animate a Character and Video Sensing Tutorials (Thanks, @Accio1 !)
Bug fixes:
* Putting invalid colors in color blocks should not freeze the editor (Thanks @adroitwhiz!)

[Master] Release 2020-09-16

---

.travis.yml
test/integration/selenium-helpers.js

This worked a little too well -- the smoke tests aren't running on release or develop anymore so reverting.

Revert 4435 stop smoke on prs

---

package-lock.json
package.json

Dependabot seems to not be producing the PR to update the gui version to the latest release. This PR does that manually.

updated gui to latest release

---

src/views/credits/credits.scss

Fixes padding on people grid on credits page

Add padding on top of people grid on credits page

---

src/views/annual-report/annual-report.jsx

Fixes a broken link in the annual report.

Fix BLM studio link

---

src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx

This is more progress toward #4447
Still todo:
- l10n
- Time needs formatting
- Compose box needs to be shown/formatted correctly based on mute status
- Blue comment status box need to be sticky

Skeleton of code to show mute modal and comment status.

---

package-lock.json
package.json

Change the version of gui to the one that has the ask block autofocus change reverted.

Revert disabling ask block autofocus

---

src/routes.json

#4708 Annual report pass through
allow links to annual report with extra parameters

[release] gh-4708 

---

src/main.scss

Resolves #2729
Changes the min height at main.scss to reduce unwanted space.

Change min height

---

src/views/dmca/dmca.jsx

Addresses on this page were not updated. 
I have updated both of the addresses so they are correct.

Updated addresses on DMCA

---

src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx

Rename state's muteExpiresAt to muteExpiresAtMs so units are explicit.

Fix isMuted so it doesn't do an extra unit conversion.

---

src/views/credits/people.json

Resolves #4541 
Adds new scratchteam member.

Add "FloralSunset" to Credits Page

---

src/views/annual-report/people.json
src/views/credits/people.json

Updates to the credits page and annual report team section.

Add Tracy to credits page and Annual Report team section.

---

src/components/modal/mute/modal.scss
src/views/preview/comment/compose-comment.jsx
src/views/preview/l10n.json
test/unit/components/compose-comment.test.jsx

Revert "Add new mute message types"

---

src/template.ejs

Resolves #3759 
Adds "JavaScript is required to display this page. Please enable JavaScript in order to continue." message.

Add noscript tag

---

package-lock.json
package.json
src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx

Release Notes: 
- Bug fixes
- Older projects with assets that were made in Inkscape should no longer have their assets replaced with question marks (huge thanks to @adroitwhiz!)

Release/2021 01 21 

---

src/views/sec/l10n.json

Release the hotfix for the SEC page updates.

[Master] Hotfix SEC Text Update

---

.travis.yml

Update to the release to try and resolve build issues with peer dependencies.

[Master] Update travis.yml to fix build issues on 'master'

---

.travis.yml

Pull in changes from release update into develop.

[Develop] Update travis.yml to fix build issues on 'master'

---

package-lock.json
package.json
src/components/modal/mute/modal.jsx
src/views/preview/comment/comment.jsx
src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx

[Master] Release 2021-02-10

---

src/components/modal/mute/modal.jsx
src/views/preview/comment/compose-comment.jsx
test/unit/components/mute-modal.test.jsx

Resolves the last bullet point of #4747
In testing, we should make sure that you can submit feedback, and that the feedback ends up in ES.

Save automod feedback

---

src/lib/relative-time-polyfill.js

This should hopefully fix the Safari 12 issues we were having.

Fix pluralrules polyfill

---

src/lib/relative-time-polyfill.js

Update relative-time-polyfill.js to include localedata

---

src/components/modal/mute/modal.jsx
src/l10n.json
src/lib/relative-time-polyfill.js
src/views/preview/comment/compose-comment.jsx
test/unit/components/mute-modal.test.jsx

[Master] Hotfix/automod feb16

---

src/views/about/about.jsx
src/views/credits/credits.jsx

Update link on Credits and About pages to LLK to new Media Lab url

Fix LLK link

---

src/components/modal/mute/modal.jsx
src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx
test/unit/components/mute-modal.test.jsx

Prevent feedback when not just muted

---

src/components/modal/mute/modal.jsx
src/views/preview/comment/compose-comment.jsx
test/unit/components/compose-comment.test.jsx
test/unit/components/mute-modal.test.jsx

Ensure moderation feedback is not confusing for the moderation team.

[Master] Hotfix - automod everyone (mar15)

---

src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json

Update the Conference page to look like this doc:
https://docs.google.com/document/d/1-veTXYDlckOry1gKH8RzTp4dPkNrqmThUC27ST1kE1A/edit?ts=60419837#heading=h.3qwdbj2wz8u9

Made changes to conf 2020 page (fixed dependencies)

---

package-lock.json
package.json
src/routes-dev.json
src/views/conference/2020/index/index.jsx
src/views/conference/2020/index/l10n.json
src/views/studio/studio-activity.jsx
src/views/studio/studio-comments.jsx
src/views/studio/studio-curators.jsx
src/views/studio/studio-info.jsx
src/views/studio/studio-projects.jsx
src/views/studio/studio-tab-nav.jsx
src/views/studio/studio.jsx

- Content updates to the footer, the credits page, and the about page

[Master] Release 2021-03-17

---

package-lock.json
package.json

CircleCI reports errors for TODO comments during lint tests.  
implements changes made in eslint-config-scratch that removes TODO comment warnings

update eslint-config-scratch to 7.0.0

---

src/components/carousel/carousel.json
src/views/components/components.jsx

The components page is a dev route meant to display a library of reusable UI components. It currently has errors that prevent it from loading. This change fixes it just enough so that it loads.

Fix components page

---

src/components/grid/grid.json
src/views/components/components.jsx
src/views/components/components.scss

Added a few more things to the components page:
- Nav bubbles (SubNavigation component)
- Grid of projects (Grid component)
- Drop-down menu (Select component)
- Text area (TextArea component)

Add more components to the components page

---

package-lock.json
package.json
src/redux/studio-comment-actions.js
src/redux/studio.js
src/views/studio/studio-comments.jsx
test/unit/redux/studio.test.js

Resolve conflicts with package.json and package-lock.json. Use the version of GUI that's on develop.

Fix merge conflicts on release branch for 04/15/2021

---

package-lock.json
package.json
src/redux/studio-comment-actions.js
src/redux/studio.js
src/views/studio/studio-comments.jsx
test/unit/redux/studio.test.js

Prepare release branch with updates from `develop`

Prepare release branch

---

src/redux/session.js

Resolves #3698 
Adds privacy policy and terms of use to allowlist. (Should the variable names be changed?)

Add privacy policy and terms of use to allowlist

---

src/redux/session.js

Redo of https://github.com/LLK/scratch-www/pull/5220
* update method of checking goodlist of pages for banned user to see
* update goodlist contents to add terms of use, privacy policy
1. log in as a banned user
2. you SHOULD be able to view these pages:
* https://scratch.ly/community_guidelines
* https://scratch.ly/privacy_policy
* https://scratch.ly/terms_of_use
3. you should NOT be able to view these pages:
* https://scratch.ly/credits
* https://scratch.ly/discuss

update method of checking goodlist of pages for banned user to see (2nd try)

---

package.json

manually update gui

---

package.json

Revert "manually update gui"

---

src/components/forms/toggle-slider.jsx
src/views/studio/l10n.json
src/views/studio/studio-comments-allowed.jsx
src/views/studio/studio-comments.jsx
src/views/studio/studio-open-to-all.jsx
src/views/studio/studio-projects.jsx
src/views/studio/studio.scss

Depends on https://github.com/LLK/scratch-www/pull/5403
Replace the "Anyone can add projects" checkbox with a toggle

Studio open toggle

---

src/views/studio/l10n.json
src/views/studio/studio-activity.jsx
src/views/studio/studio-curators.jsx
src/views/studio/studio-managers.jsx
src/views/studio/studio.scss

A few minor fixups on studio header styling and translations
/cc @fsih I think there is something wrong with using figma dimensions directly, the pixel offsets seem wrong and the font weights definitely do not match... we might have to talk to kathy about it.

Fixup header styling

---

src/views/studio/l10n.json
src/views/studio/lib/studio-project-actions.js
src/views/studio/modals/user-projects-modal.scss
src/views/studio/studio-curator-inviter.jsx
src/views/studio/studio-project-adder.jsx

Fixes include:
- Correct placeholders for project/curator inputs
- Ability to add projects from URLs
- Prevention of duplicate project addition on the client side
- Prevention of empty input submission on the client side
- Prevent project browser modal from extending beyond screen height when screen is <700px tall

Bug fixes from studio playground test on May 12

---

src/views/studio/studio-follow.jsx
src/views/studio/studio-report.jsx
src/views/studio/studio.scss

A few minor CSS issues before testing today.

Minor style cleanups for studio page

---

src/views/splash/donate/donate-banner.jsx
src/views/splash/splash.jsx

Set up donate banner button with analytics. Remove end time for donate banner as per conversations offline.
Tested locally with changing date & time on my computer and using the Google Analytics Debugger chrome extension.

[Master] Hotfix Donate Banner Update

---

src/views/studio/studio-description.jsx
src/views/studio/studio-image.jsx
src/views/studio/studio-title.jsx
src/views/studio/studio.scss

Resolves #5411
Studio descriptions now get "linkified". This PR also adds CSS to match the behavior for editable descriptions.
Note the `height` - textarea has `rows=20`, but this does not include things like line height, so I had to take that into account.
Manual testing.

Linkify studio descriptions

---

src/routes.json

Revert "Bump conference URL one year"

---

test/integration/footer-links.test.js

Revert "Fix integration test broken in #5476"

---

package.json

Dependabot will take care of updates from now on.

Fix the l10n version.

---

src/views/studio/l10n.json
src/views/studio/modals/user-projects-modal.jsx
src/views/studio/modals/user-projects-modal.scss
static/svgs/studio/add-to-studio-empty.svg

In the "add to studio" modal, add empty state styling, and a done button at the bottom

"Add to studio" modal empty states and done button

---

src/views/studio/studio-tab-nav.jsx
src/views/studio/studio.scss

Also remove that weird tiny bit of resizing when you click on them, was that intentional?

Make the default nav button state white

---

src/views/studio/studio.scss

- Increase the padding in and around tab nav buttons
- Change the color of the hover states

Studio tab nav button styling

---

src/routes.json

Reverts LLK/scratch-www#5631
Not quite ready yet ;)

Revert "Switch studios route to real version for testing on staging"

---

src/views/studio/modals/promote-modal.scss

Reduce the manager modal from 780px to 680px.

Change manager modal width

---

package-lock.json
package.json
test/integration/homepage-rows.test.js
test/integration/my-stuff.test.js
test/integration/studios-page.test.js

Some integration tests that link to the studio page will break when we switch to the new studio page.  Also there are no tests for the new studio page.
Updates some of the old tests that pointed to the old studios page.  Also, Adds a few integration tests for the new studios page.
Also updates Chromedriver.

Studio page integration tests

---

src/views/download/scratch2/download.jsx
src/views/download/scratch2/l10n.json

Resolves #5132. Thanks to @carljbowman for support

Update link to download AIR, remove outdated content

---

test/integration/my-stuff.test.js

Adds an integration test to test the rate limiting of studio creation.
It also rearranges the tests slightly and removes a wait that is no longer necessary.

Add studio rate limit integration test

---

package-lock.json
package.json
test/integration/footer-links.test.js
test/integration/homepage-rows.test.js
test/integration/join.test.js
test/integration/my-stuff.test.js
test/integration/navbar.test.js
test/integration/project-page.test.js
test/integration/selenium-helpers.js
test/integration/sign-in-and-out.test.js
test/integration/studios-page.test.js

Adds tests for studios.
* invite curators
* accept curator invite
* promote curators to be managers
Creates a reusable Sign in function that takes a username and password
Updates Chromedriver

Studio management integration tests

---

src/redux/studio-permissions.js
src/views/studio/lib/studio-member-actions.js
src/views/studio/modals/transfer-host-confirmation.jsx
src/views/studio/modals/transfer-host-modal.scss
src/views/studio/modals/transfer-host-selection.jsx
src/views/studio/studio-member-tile.jsx
test/unit/redux/studio-member-actions.test.js
test/unit/redux/studio-permissions.test.js

Reverts LLK/scratch-www#5988
due to a bug that caused the "load more" button to break (to be fixed in #5992)

Revert "Transfer host modal updates"

---

src/redux/studio-permissions.js
src/views/studio/lib/studio-member-actions.js
src/views/studio/modals/transfer-host-confirmation.jsx
src/views/studio/modals/transfer-host-modal.scss
src/views/studio/modals/transfer-host-selection.jsx
src/views/studio/studio-member-tile.jsx
test/unit/redux/studio-member-actions.test.js
test/unit/redux/studio-permissions.test.js

Revert "Revert "Transfer host modal updates""

---

src/views/studio/l10n.json
src/views/studio/lib/studio-member-actions.js
src/views/studio/modals/transfer-host-confirmation.jsx
test/unit/redux/studio-member-actions.test.js

Adds UX for the error when a user has made too many password attempts in the studio transfer flow.
Also adds unit testing for the various error types for studio transfer.

Too many password attempts error

---

test/integration/studios-page.test.js

Adds an automated test for transferring the host roll on studios.

Add studio transfer test

---

test/integration/comments.test.js

There are currently no tests that leave comments
Adds integration tests that leave a comment on:
- a project page
- a profile page
- a studio page
More comment tests will be added later.

Add integration tests leaving comments on projects, studios, and profiles

---

package-lock.json
package.json
test/integration/comments.test.js

Adds more automated integration tests.  Includes coverage of getting notifications and messages.
Also updates Chromedriver to version 94

Add comment and notification integration tests

---

src/views/studio/studio-member-tile.jsx

Including last week's release branch changes.

Update release branch with develop (again)

---

test/integration/comments.test.js

Improves integration tests
Adds an integration test that replies to a comment on the project page and on the studio page.
The profile page will be coming later.

Add project and studio reply integration tests

---

src/components/text-and-media-snippet/text-and-media-snippet.jsx
src/components/timeline-card/timeline-card.scss
src/components/video-preview/video-preview.jsx
src/views/annual-report/2020/annual-report.jsx
src/views/annual-report/2020/annual-report.scss
src/views/annual-report/2020/l10n.json

some fixes from the bughunt yesterday

Annual report 2020

---

src/views/about/l10n.json

Annual Report 2019 -> Annual Report

Fix annual report link text

---

.circleci/config.yml
src/template-config.js
src/template.ejs

Conditionally outputs Google Tag Manager code in the head and body of generated html.

[Master] Add configuration for GTM

---

src/components/modal/email-confirmation/modal.jsx

Reverts LLK/scratch-www#6429 (merged into the wrong branch)

Revert "Unconfirmed user link hotfix"

---

src/components/modal/email-confirmation/modal.jsx

Updates link to redirect to the `#accounts` id

Updates link in email confirmation modal

---

src/components/modal/email-confirmation/modal.jsx

Reverts LLK/scratch-www#6430
All of the other stuff we tried didn't bring the original changes back from #6429 (accidental merge to Develop instead of the release branch, and then got reverted in #6430) so trying again to put these changes back into Develop.

Revert "Revert "Unconfirmed user link hotfix""

---

src/components/modal/email-confirmation/modal.jsx
src/components/modal/email-confirmation/modal.scss

Modal CSS Issues on Project Page (thanks to @BarelySmooth for the catch!) 
https://github.com/LLK/scratch-www/issues/6521
Specifies a more precise css class for the email confirmation modal

modal css fix

---

src/redux/session.js
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
src/views/search/search.jsx

Makes new flag available to our website; doesn't do anything else.

Add new feature flag

---

test/integration/footer-links.test.js

Fix conference integration test

---

README.md

Fix suggested Node version to be up to date

---

src/views/studio/studio.jsx
test/unit/views/studio.test.jsx

Created with @picklesrus and @tomlum 
fixes #5952 - Add RTL support for studio pages
Adds dir tag for RTL languages to studio shell div
Adds unit tests for studio view in a new unit/views directory.

Display studio RTL for RTL languages

---

src/views/annual-report/2021/annual-report.jsx
src/views/annual-report/2021/l10n.json

Change placeholder name to reflect content

Change placeholder name in AR string

---

README.md
test/integration/project-page.test.js

Also update the readme with the info for
Adds tests that load scratch2 projects.
Updates readme

Add integration tests loading scratch2 projects

---

src/views/preview/project-view.jsx

Fixes issue where newly created projects would not load without a token (even though it's not needed)

Adds check for newly created project to not require token

---

src/views/preview/project-view.jsx

Reverts LLK/scratch-www#6822  
File load is broken so we're reverting to have more time to fix.

Revert "Adds check for newly created project to not require token"

---

src/lib/storage.js
src/views/preview/embed-view.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
src/views/preview/projectshape.jsx

Reverts LLK/scratch-www#6773
This breaks uploading via file upload so reverting til we can figure out a better fix.

Revert "Send fastly token to gui"

---

test/integration/project-page.test.js

Skip project upload test because it isn’t working

---

src/views/credits/people.json

Resolves #6843 
Removes ray, carl, karishma, bryce, katelyn, sarah from credits page

removed ray, carl, karishma, bryce, katelyn, sarah. <3 <3 <3

---

src/l10n.json

#7006 
There is a duplicate key in src/l10n.json, where `general.monthDecember` is duplicated. This pull request removes the duplicate JSON key in src/l10n.json.
nil. All tests passed.

removed duplicate json key in src/l10n.json

---

src/components/footer/www/footer.jsx
src/routes.json
src/views/about/about.jsx
src/views/annual-report/2019/annual-report.jsx
src/views/annual-report/2020/annual-report.jsx
src/views/annual-report/2021/annual-report.jsx
src/views/developers/developers.jsx
src/views/faq/faq.jsx
src/views/splash/donate/donate-banner.jsx

Updates donation URL to be https://www.scratchfoundation.org/donate

CE-224 Updates Donation Url

---

src/components/navigation/www/navigation.jsx

I added an aria label to the search icon in the main nav-bar so that the screen reader will describe it properly to screen reader users. Resolves #7174.
No new tests have been added. All current automated tests still pass and nothing breaks in the original design of the application.

Fix gh -7174: Missing ARIA attribute for the search icon in the nav-bar

---

src/components/join-flow/join-flow.jsx
src/components/page/www/page.jsx
src/components/registration/scratch3-registration.jsx
src/views/join/join.jsx

Resolves:
Resolves #7170 
Adds `nav`, `main`, and `footer` elements to primary page template components to improve navigation for assistive technologies. Changes have no visible impact or break any existing design components. 
No tests have been added and no breaking changes to existing design are introduced as a result of these changes. All current automated tests still pass. Below is a screenshot that attempts to illustrate how elements of the home page are now wrapped in the new semantic tags:

CE-272: Implement semantic landmark elements to improve Screen Reader navigation

---

src/views/teachers/landing/landing.jsx

Fixes raspberry pi link on educators page

REQ-17 fixes educators page raspberry pi link

---

src/views/preview/project-view.jsx

- Resolves [ENA-262](https://scratchfoundation.atlassian.net/browse/ENA-262)
As part of LLK/scratch-gui#8811, the `isTotallyNormal` attribute needs to be passed to the editor.
Manual testing
[ENA-262]: https://scratchfoundation.atlassian.net/browse/ENA-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pass isTotallyNormal to gui

---

src/views/splash/presentation.jsx

Undoes hiding of community rows from this commit https://github.com/LLK/scratch-www/commit/2444b29914eeab87be013063db321730c1c0ac59

[Master] hotfix/unhide-community-rows 

---

src/redux/session.js

Honor IP Ban info from session.

Handle generic ipban redirect if session says so

---

README.md
package-lock.json
package.json
src/components/join-flow/join-flow.jsx
src/template-config.js
src/template.ejs
src/views/splash/donate/donate-banner.jsx
test/unit/components/join-flow.test.jsx

Resolves ENA-317
Replace UA with GA4 through GTM, for both scratch-www and scratch-gui.
For details, see #7702 and scratchfoundation/scratch-gui#9040

hotfix for GA4

---

src/views/about/about.jsx
src/views/developers/developers.jsx
src/views/download/scratch2/download.jsx
src/views/download/scratch2/l10n.json

Update URLs (especially root URL which does not redirect)

LLK -> scratchfoundation

---

src/l10n.json
src/views/bad-username-splash/bad-username-splash.jsx

CE-445 : new design for the FAR flow
CE-448 : Bug where changing the admin message would affect the FAR message

New FAR design and bug fix

---

src/routes.json

Temporarily break/redirect about pages in staging environment

Testing out upcoming changes

---

package-lock.json
package.json
src/lib/user-guiding.js
src/views/preview/comment/compose-comment.jsx
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx
webpack.config.js

Add support for Userguiding survey integration
Tests and lint pass, change has been verified manually

feat: Userguiding integration

---

.github/workflows/ci-cd.yml

_We still need to actually supply these values - should probably do that pre-merge_

Include vars and secrets for user guiding in CI build

---

src/lib/user-guiding.js

See: https://scratchteam.slack.com/archives/C07CT9C9325/p1724939334621739

Update user-guiding survey IDs

---

src/components/footer/www/footer.jsx
src/l10n.json
test/integration/footer-links.test.js

https://scratchfoundation.atlassian.net/browse/UEPR-72?focusedCommentId=14257
Add DSA footer link

Feat: uepr-72: Add dsa requirements link to footer

---

src/components/journeys/editor-journey/editor-journey.jsx
src/lib/onboarding.js
src/views/preview/presentation.jsx
src/views/preview/project-view.jsx

[UEPR-51](https://scratchfoundation.atlassian.net/browse/UEPR-51)
Added events:
- `editor-journey-step` - when user goes through steps during editor journey recording the picked step as parameter
- `tutorial-played` - when user plays tutorial project, sends the name of the played project as parameter
- `tutorial-remixed` - when user remixes tutorial project, sends the name of the remixed project as parameter
[UEPR-51]: https://scratchfoundation.atlassian.net/browse/UEPR-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UERP-51] Google Analytics events for onboarding journeys

---

src/components/journeys/editor-journey/editor-journey.scss

hotfix: fixed title background issue

---

src/components/journeys/editor-journey/editor-journey.scss

fix: fixted title background issue

---

src/views/guidelines/guidelines.jsx
src/views/ideas/ideas.jsx
src/views/ideas/ideas.scss
src/views/ideas/l10n.json

refactor: [UEPR-90] fixed gap between components and how pdfs open

---

src/components/youtube-video-button/youtube-video-button.jsx
src/components/youtube-video-button/youtube-video-button.scss

Added missing text to Youtube button

fix: [UEPR-116] added missing views text

---

src/components/cards-modal/cards-modal.jsx

Fix swapped links in cards modal

fix: [UEPR-88] fix swapped links

---

package-lock.json
package.json
src/lib/storage.js

Equalize scratch-storage versions between applications.

fix: revert previous version of scratch-storage

---

src/components/cards-modal/cards-modal.scss
src/views/ideas/ideas.jsx
src/views/ideas/ideas.scss

[UEPR-121](https://scratchfoundation.atlassian.net/browse/UEPR-121)
Added an embedded project to page banner.
[UEPR-121]: https://scratchfoundation.atlassian.net/browse/UEPR-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: [UEPR-121] add embedded ideas project to banner

---

src/components/youtube-video-modal/youtube-video-modal.jsx

[UEPR-116](https://scratchfoundation.atlassian.net/browse/UEPR-116)
Enable youtube videos to be watched in full screen
[UEPR-116]: https://scratchfoundation.atlassian.net/browse/UEPR-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [UEPR-116] allow full screen of video

---

package-lock.json
package.json

Update gui reference

---

src/views/ideas/ideas.scss

**Ticket:**
[UEPR-132](https://scratchfoundation.atlassian.net/jira/software/c/projects/UEPR/boards/92?selectedIssue=UEPR-132)
Changes:
This pull request adds a border-radius to the `.ideas-project` class.
[UEPR-132]: https://scratchfoundation.atlassian.net/browse/UEPR-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [UEPR-132] Corner radius ideas project

---

src/components/modal-navigation/modal-navigation.jsx
src/views/become-a-scratcher/become-a-scratcher.jsx

https://scratchfoundation.atlassian.net/browse/UEPR-146
* Pass next/prev button text in become a scratcher screen
* Don't make buttons invisible if text isn't passed

fix: make next and back buttons in become a scratcher screen visible

---

src/views/credits/people.json

**Ticket:**
[UEPR-82](https://scratchfoundation.atlassian.net/jira/software/c/projects/UEPR/boards/92?selectedIssue=UEPR-82)
Changes the team members
[UEPR-82]: https://scratchfoundation.atlassian.net/browse/UEPR-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UEPR-82] Update Our team page

---

package-lock.json
package.json
src/lib/storage.js

Revert scratch-storage and scratch-gui versions

revert: scratch-storage and scratch-gui versions

---

src/components/video/video.jsx
src/views/starter-projects/starter-projects.jsx
src/views/starter-projects/starter-projects.scss

[UEPR-149](https://scratchfoundation.atlassian.net/browse/UEPR-149)
Adds an embedded video to Starter projects page. Adds option to set autoplay to wistia embedded videos.
[UEPR-149]: https://scratchfoundation.atlassian.net/browse/UEPR-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [UEPR-149] add embedded video to starter projects page

---

src/views/starter-projects/starter-projects.scss

Changed width of text paragraphs on starter page

fix: [UEPR-47] change width of text paragraphs

---

src/components/modal/feedback/qualitative-feedback.scss

- Between radio button and label there should be 12px, not 1rem
- Right padding of every radio row should be 8px, not 1rem

fix: styles for feedback modals

---

src/views/become-a-scratcher/become-a-scratcher.jsx
src/views/contact-us/contact-us.jsx
src/views/messages/message-rows/comment-message.jsx
src/views/messages/message-rows/favorite-project.jsx
src/views/messages/message-rows/love-project.jsx
src/views/messages/message-rows/remix-project.jsx
src/views/splash/activity-rows/favorite-project.jsx
src/views/splash/activity-rows/remix-project.jsx
src/views/splash/activity-rows/share-project.jsx
src/views/studio/studio-activity.jsx
src/views/studio/studio-member-tile.jsx
src/views/studio/studio-project-tile.jsx

Limit the number of redirects we are making in scratch-www by stripping "/" from paths.

[hotfix] 2025-04-24

---

src/views/teachers/faq/faq.jsx
src/views/teachers/faq/l10n.json

https://scratchfoundation.atlassian.net/browse/UEPR-232
Update teachers faq copy

feat: update teacher faq student limit copy

---

src/views/explore/explore.jsx

https://scratchfoundation.atlassian.net/browse/POD-273
Remove 'recent' tab from explore page

hotfix: temporarily remove recent tab from explore page

---

src/views/splash/presentation.jsx

feat: [POD-265] Add link to BAC

---

src/routes.json

- Related to [UEPR-184](https://scratchfoundation.atlassian.net/browse/UEPR-184)
- Add redirects for the Face Sensing tutorial
[UEPR-184]: https://scratchfoundation.atlassian.net/browse/UEPR-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Add redirects for the face sensing tutorial

---

src/lib/project-info.js

- [UEPR-335](https://scratchfoundation.atlassian.net/browse/UEPR-335)
- Add dummy implementation for the `faceSensing` function for v2 projects. The function returns `false` always, as there are no v2 projects that use face sensing
[UEPR-335]: https://scratchfoundation.atlassian.net/browse/UEPR-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UEPR-335] Fix console error when loading v2 projects with cloud variables

---

package-lock.json
package.json
src/views/preview/project-view.jsx
src/views/preview/project-view.scss

https://scratchfoundation.atlassian.net/browse/UEPR-331
Pass feature callout param to GUI.
Ensure we override driver.js' pointer-events:none

feat: pass feature callout param to gui
